### ISSUE TITLE
Cleanup buildCesiumViewer build step

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1230]
Copy and pasting this for a new app is a bit of a pain since more than the `cesiumViewerDirectory` and `cesiumViewerOutputDirectory` properties need to be changed.  Names and paths are hardcoded in a few other places.

**Comment by adi2412** [comment]
We can add a separate target for building a new app and passing the directory as a command line argument to the task. Just need to rewrite some of the hardcoded values in `cesiumViewerDirectory` to the argument values. However, this would require the app to be following the same conventions as `CesiumViewer`(like the name of the css, js and config files).

It's a very simple task and I could send a pull request for this if nobody is working on it.

**Comment by pjcozzi** [comment]
Thanks for the interest.  @mramato is the best person to advise here.

**Comment by mramato** [comment]
I'm not really sure what the goal is here and judging from the age of this bug, I don't think it's any more relevant. User apps shouldn't be using our build system to build their app and the only app we build ourselves is Cesium Viewer (and that's unlikely to change any time soon).  I also don't want to add more complexity to our build system unless we need it because we plan on moving away from java/ant (the sooner the better).

**Comment by pjcozzi** [comment]
Let's just close this.
