### ISSUE TITLE
Orbit line morph artifact

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1593]
* Open the [CZML Sandcastle example](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=CZML.html&label=Showcases).
* Pause it (useful, but not necessary).
* Morph to 2D.  Take note of the yellow orbit line.
* Morph to 3D or CV.  When the morph starts, the orbit line shrinks and grows.

Before morph to 3D/CV:

![image](https://cloud.githubusercontent.com/assets/782098/2570030/faeebb46-b8f3-11e3-8930-7a948fe203a8.png)

Right when morph starts:

![image](https://cloud.githubusercontent.com/assets/782098/2570035/0f0f9190-b8f4-11e3-928b-375b06b8412c.png)

This has been around for a while AFAIR, well before b26.  I'm not sure yet what we can reasonably do about this.

**Comment by mramato** [comment]
I believe the problem here is that the `PathVisualizer` switches inertially visualized paths to fixed paths the moment SceneMode is anything by Scene3D. The correct way to address this would be to interpolate between the inertially computed path and the fixed computed path when morphing.  Since we can't interpolate the transform matrix, this would involve generating both fixed and inertial paths and then interpolating between the computed positions.  It wil be CPU intensive and I'm not sure it's worth it, but if we really want to fix this, that's what we'll have to do.

**Comment by bagnell** [comment]
I think this was fixed by #3768. I can't reproduce this.
