### ISSUE TITLE
Gltf node instancing not supported in Cesium.

### ISSUE THREAD

**Issue by vinjn** [AnalyticalGraphicsInc/cesium#1754]
https://github.com/KhronosGroup/glTF/issues/276

Dae file uploaded as https://cloud.githubusercontent.com/assets/558657/3093329/694702ee-e5b1-11e3-9c48-138430dd89c6.jpg
You can download the `jpg`, and rename the extension to `7z` and extract it.

The expected rendering result should be like
![](https://cloud.githubusercontent.com/assets/1211226/3093904/d23f97c0-e5b6-11e3-91c7-25f7a6170677.png)

However the result from Cesium is like
![](https://cloud.githubusercontent.com/assets/558657/3094419/3b9ba1aa-e5bc-11e3-80e5-ddae32aee9e3.png)

**Comment by pjcozzi** [comment]
Thanks again @vinjn.  This is a good catch since Cesium was trying to handle this case but was not doing so correctly; it had a separate draw call for each instanced node, but they all used the "last" parent's transform.

I hacked up a partial fix in [gltf-instancing](https://github.com/AnalyticalGraphicsInc/cesium/compare/gltf-instancing) but it is ugly and only works for multiple immediate parents, not older ancestors.  Instead, I'm pretty sure I am going to expand the glTF DAG into a tree, but this will be some work since I will need to map the original glTF node ids (e.g., for animation and show/hide) to the new nodes.  @fabrobinet I imagine this is how your renderer works?

![image](https://cloud.githubusercontent.com/assets/782098/6427627/eb28a1ba-bf53-11e4-986f-95582e44a9da.png)

**Comment by fabrobinet** [comment]
I confirm but it's not a big overhead as you can share the same geometry.

**Comment by pjcozzi** [comment]
Agreed, I'm not concerned about the overhead, just the time I need to update the code :)

**Comment by pjcozzi** [comment]
@satishkashyap also reported this bug with a different model: https://github.com/KhronosGroup/glTF/issues/363

**Comment by pjcozzi** [comment]
Fixing this _might_ also fix #2387.

**Comment by slozier** [comment]
I'm also running into this issue when trying to convert some models. From the glTF issue it seems like the plan is to fix this at the converter level?

**Comment by pjcozzi** [comment]
Exactly, this will be fixed in the converter.  We decided that the glTF spec will not allow DAGs, so DAGs will be converted to a tree offline.  See https://github.com/KhronosGroup/glTF/issues/401

This conversion will be part of https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/1.  Work will begin in the new year.

**Comment by lilleyse** [comment]
The updated converter that should be deployed soon fixes this model.
![tree](https://cloud.githubusercontent.com/assets/915398/16342597/033cb4b6-3a01-11e6-8df4-74420f980e3f.JPG)
