### ISSUE TITLE
Official support for mobile and desktop Safari

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#1805]
* [x] Anything using Entities appears to be broken.
* [ ] Like we've seen on old version of Chrome (and current versions of IE) the tests cause the browser to stop creating new WebGL contexts partway through, causing stuff to start failing.  Running the tests individually seems to work.

CC #1804

**Comment by pjcozzi** [comment]
Should this be closed and #1804 be opened?

**Comment by mramato** [comment]
Doesn't really matter to me.  What we do need to decide is at what point do we put actual effort into supporting Safari.

**Comment by mramato** [comment]
I think #2533 is the best we are going to do for Safari anytime soon.  Tests still bomb because it stops creating contexts halfway through; and overall Safari likes to get crashy after a while; but all of the demos work and I think for normal application usage we're probably in pretty good shape.  With some more testing, I think we might be able to say we support Safari (at least as well as we support IE or Chrome on Android)

**Comment by mramato** [comment]
I vote we close this.  Our users are already using Cesium on desktop and iOS devices and Safari support is as good as it's going to get until Apple starts taking WebGL more seriously.  Cesium works, but our unit tests barf because of bugs in Safari.  It can't even make it through the real WebGL conformance tests without crashing (and has tons of failures before doing so).  I'm fairly certain there is nothing we can do on our end to improve things, other than submitting bugs to the Webkit team.

**Comment by pjcozzi** [comment]
Agreed.
