### ISSUE TITLE
Moon rendering on top of foreground geometry

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#1964]
The black dot on the surface of California in the below picture is the moon being rendered through Geometry; for some reason it is being drawn on top (though it correctly goes behind the ellipsoid).

![image](https://cloud.githubusercontent.com/assets/1495196/3697244/538ac034-13a2-11e4-86fd-f15412cf2ff7.png)

[Sandcastle link](http://localhost:8080/Apps/Sandcastle/index.html?src=GeoJSON%20and%20TopoJSON.html&label=Showcases) to the demo.

**Comment by mramato** [comment]
This seems to be fixed (though I'm not sure what changed).  @emackey can you still reproduce this?

**Comment by mramato** [comment]
Never mind.  This still happens but not in Chrome.  It does happen in IE.  Maybe a missing extension in IE?

**Comment by pjcozzi** [comment]
I think this is because moon is updated in `updatePrimitives` as a generic primitive, instead of in `executeCommands` like the special case stars, atmosphere, and sun so it is rendered after the atmosphere.  The downside of moving it is that we would lose its depth, but I don't think that is a problem for our current use cases.

@bagnell what do you think?
