### ISSUE TITLE
Export stand-alone sample from Sandcastle

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#1998]
Sandcastle should have the ability to export the editor code into a completely stand-alone sample based on pre-built Cesium or even CDN-hosted Cesium.

The current "Save As..." behavior is good for saving to the Sandcastle gallery folder, and indeed those demos run directly from within the gallery via baked-in calls to Require.js.  But a new "Export to..." type function could save the same demo a different way, referencing pre-built Cesium either locally or from a CDN, and allow the demo to be hosted on a website that wasn't hosting the Sandcastle folder structure.  Code from `sandcastle-header.js`, `bucket.html`, and `bucket.css` files would need to be baked into the exported sample directly, breaking it free of Sandcastle.

I'm thinking that such an exported file will still be unable to operate from a `file:///` protocol due to Cesium's extensive use of XHR.  But if someone could stick the file on their personal website, without a Cesium source tree or Sandcastle install on that website, I think that would lower the bar for simple deployments of small apps, reducing the barrier to entry for new users of Cesium.

This is for after 1.0.  Previous versions of this idea were talked about in #1083 and #1747.

**Comment by chriswingler** [comment]
Has there been any progress on this I could implement?  I just ran into problems when inserting code from Sandcastle into a modification of the Hello World example in /Apps.

**Comment by emackey** [comment]
I think the plan is to tackle this as part of the Sandcastle refresh going on this summer with Google Summer of Code.  But you can post the details of the problem you're having on [the forum](https://groups.google.com/forum/#!forum/cesium-dev) or [Stack Overflow](http://stackoverflow.com/questions/tagged/cesium) and usually get a quick answer.

**Comment by pjcozzi** [comment]
For more info on the Sandcastle refresh, see: http://cesiumjs.org/2015/06/01/GSoC-Sandcastle-Overview/

**Comment by fasiha** [comment]
Looking at http://google-opensource.blogspot.com/2015/10/google-summer-of-code-wrap-up-cesium.html — did Aditya Raisinghani's efforts not pan out?

**Comment by mramato** [comment]
Unfortunately the Sandcastle refector did not get completed.  I'm also not really sure this idea is valid anymore given the goals of Sandcastle.  It's not an application building tool but merely a demo, testing and prototype tool.  People should not be building anything they wish to put into production via Sandcastle.

If you want to host a Sandcastle demo for demo purposes, you just have to host the whole source tree and link directly to the HTML file.  We also have blog post about using Sandcastle with GitHub pages: http://cesiumjs.org/2015/10/07/Hosting-Cesium-Sandcastle-with-GitHub-pages/

**Comment by fasiha** [comment]
Thanks for the update @mramato! I completely understand where you're coming from.

At the same time, Sandcastle (and Cesium.js in general, come to think of it) is too successful 😋. It's so easy to tweak Sandcastle examples to get something compelling—many, many lazy/busy people are going to pine for an easy way to bake the example with their tweaks into a standalone tool they can throw on gh-pages or a static server with a URL like http://mramato.github.io/cesium/manipulation/ instead of http://mramato.github.io/cesium/Apps/Sandcastle/index.html?src=Imagery%20Layers%20Manipulation.html&label=Showcases! It's too embarrassing to publish the latter in a tweet 😅.

Luckily I seem to have some time and knowledge to roll my own standalone app, taking pointers from a Sandcastle demo, understanding how Knockout works for real, etc. Which is of course more useful in the long-term. But I was momentarily excited at the possibility of having something magical like a Sandcastle exporter. 🍻

**Comment by shunter** [comment]
It's worth pointing out that the current Sandcastle files are already very easy to make standalone.  I recently deployed some sandcastle examples to github pages and found that the minimum set of changes are:

 * Add a base tag to head so that the relative URLs work, regardless of where the HTML file is deployed to.  This can point to any URL that hosts the Cesium release files, but you can also just point to cesiumjs.org.  I used:

```html
<base href="http://cesiumjs.org/releases/1.16/Apps/Sandcastle/gallery/">
```

Additionally, using a built version of Cesium is another small change.  Remove the script tag for require.js and the script that calls `require.config`, and replace it with a script tag for Cesium.js.  I used

```html
<script type="text/javascript" src="http://cesiumjs.org/releases/1.16/Build/Cesium/Cesium.js"></script>
```

Those are the only changes necessary.  The rest of the code will automatically work with the built version.

**Comment by mramato** [comment]
The main problem is that users (particular those new to web development) rely on things like the `Sandcastle.addToolbarButton`, which (unless I'm mistaken) does not work with the method you describe.

**Comment by shunter** [comment]
It does.  Sandcastle-header.js is fetched from the server that is configured as base.

**Comment by mramato** [comment]
I thought that might be the case, good to know.

**Comment by pjcozzi** [comment]
I would be fine closing this.  Also see @mramato's comment: https://github.com/AnalyticalGraphicsInc/cesium/issues/1998#issuecomment-163677671

**Comment by jumpjack** [comment]
if by "standalone" you mean "you double click it on PC and it works".... it does not.
Not with Win10, Chrome and Cesium 1.75.

`Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://cesiumjs.org/releases/1.16/Apps/Sandcastle/templates/bucket.css".
Points005.html:19 GET https://cesium.com/downloads/cesiumjs/releases/1.16/Apps/Sandcastle/CesiumUnminified/Cesium.js net::ERR_ABORTED 404
Points005.html:28 GET https://cesium.com/downloads/cesiumjs/releases/1.16/Apps/Sandcastle/templates/bucket.css net::ERR_ABORTED 404
Points005.html:14 GET https://cesium.com/downloads/cesiumjs/releases/1.16/Apps/Sandcastle/Sandcastle-header.js net::ERR_ABORTED 404
Points005.html:19 GET https://cesium.com/downloads/cesiumjs/releases/1.16/Apps/Sandcastle/CesiumUnminified/Cesium.js net::ERR_ABORTED 404
cesiumjs.org/releases/1.16/Apps/Sandcastle/gallery/:1 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://cesiumjs.org/releases/1.16/Apps/Sandcastle/templates/bucket.css".
cesiumjs.org/releases/1.16/Apps/Sandcastle/gallery/:1 GET https://cesium.com/downloads/cesiumjs/releases/1.16/Apps/Sandcastle/templates/bucket.css net::ERR_ABORTED 404`
