### ISSUE TITLE
CZML - how can I make height relative to ground of first interval?

### ISSUE THREAD

**Issue by utillity** [AnalyticalGraphicsInc/cesium#2075]
Hi,

the GPS Module sends ground relative to initialization (ground). I can get the elevation data elsewhere and add it when generating the CZML, but that still does not make for correct visualization when activating terrain/height-model and the flight-path is visualized way too high, if I don't load the terrain model. So the perfect solution would be to specify 2d reference coordinates which serves as a reference for relative height data being sent.

or is there a solution already available?

regards, Tilli

**Comment by mramato** [comment]
@utillity, I'm sorry that no one ever got back to you on this.  We recommend these types of questions be asked on [our forum](https://groups.google.com/forum/#!forum/cesium-dev) since they will reach a larger audience and are much more likely to get a response.

To answer your question, we are in the process of adding support for `heightReference` to CZML, which will allow you to specify position data as being clamped to ground, height above terrain, or an absolute value, but there's no exact ETA on when this will be available in CZML, hopefully before the end of the year.

**Comment by utillity** [comment]
ok, thanks! that would be great!
