### ISSUE TITLE
Evaluate Fast.js

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2307]
Optimized versions of some JavaScript functions (with some constraints)

https://github.com/codemix/fast.js/tree/master

**Comment by mramato** [comment]
I looked into this and nothing really jumped out at my in terms of use cases where this would help Cesium, since the feature set doesn't include many functions that we use.  It's also optimized for Chrome and doesn't guarantee it won't slow down other browsers, so I think that makes it a non-starter for us. (I'm also not sure if the project is still alive since there have been no commits in the last 3 months).

If you have any specific use cases in mind where you think this would help, we can leave this open to investigate them; but otherwise I would just close this.  We can always revisit later if the library takes off.
