### ISSUE TITLE
Remove Rectangle.intersectWith and Rectangle.isEmpty

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2314]
From #2313:

* `Rectangle.intersectWith` was deprecated in Cesium 1.5. It will be removed in Cesium 1.6. Use `Rectangle.intersection`, which is the same but returns `undefined` when two rectangles do not intersect.
* `Rectangle.isEmpty` was deprecated in Cesium 1.5. It will be removed in Cesium 1.6.

**Comment by bagnell** [comment]
@kaktus40 Is it possible to use `tileXYToRectangle`? If not, you might run into the same problem as the linked issue when a tile crosses the IDL.

For your remark about the result parameter, do you mean that we should set the results properties to undefined? Because it would be impossible to set the parameter to undefined. I know the use of a result parameter is odd, but we use it throughout Cesium to reduce the amount of memory used and garbage collection overhead. In this case its not required, so I expect the most common use to be
```javascript
var intersection = Cesium.Rectangle.intersection(rectangle1, rectangle2);
if (Cesium.defined(intersection)) {
    // handle intersection
}
```
The pattern we use throughout Cesium is
```javascript
var scratchRectangle = new Rectangle(); // declared in file scope and used for intermediate values
// ...
var intersection = Cesium.Rectangle.intersection(rectangle1, rectangle2, scratchRectangle);
if (Cesium.defined(intersection)) {
    // handle intersection
}
```
This is consistent with other intersection tests as well (see [IntersectionTests](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/IntersectionTests.js)).
