### ISSUE TITLE
double touch events

### ISSUE THREAD

**Issue by chris-cooper** [AnalyticalGraphicsInc/cesium#2348]
Should double touch on mobile devices be interpreted as ScreenSpaceEventType.LEFT_DOUBLE_CLICK?  In Cesium 1.4 it is interpreted as two separate ScreenSpaceEventType.LEFT_CLICK events on Nexus 5.  This may be related to https://github.com/AnalyticalGraphicsInc/cesium/issues/1847

**Comment by pjcozzi** [comment]
@emackey do you know what is expected here?

**Comment by emackey** [comment]
Good question.  For mouse-based interactions, `DOUBLE` click speed is defined by the browser, which typically gets it from the host OS.  Some users with disabilities may only be able to produce slow "double" clicks on their hardware, other users may set their OS to only accept a rapid double-click as being "double."  Cesium just gets the mouse events from the host, and in the land of JavaScript events, that actually means getting the first `click` followed later by both a second `click` and a separate `dblclick` event.

Touch & Pointer events only have a concept of down/move/up, not `click` nor `double click`.  Typically, touch-enabled browsers will still send a separate `click` event in response to a rapid down/up user touch action, but they may choose to never send a `dblclick` as that's not a typical mobile UX pattern (native mobile apps that follow standard mobile UX guidance don't expect the user to double-tap).

My opinion is that it's not Cesium's place to get involved.  Cesium is just passing through the host OS `click` and `dblclick` events without really doing anything special to them.  Mobile chooses not to ever send `dblclick`, so Cesium never processes one.  I think apps should just avoid using this event for anything other than a convenience for things that can be accessed in other ways.  For example, tracking an entity can be done by touching the camera icon instead of double-clicking.

**Comment by pjcozzi** [comment]
OK, let's close.
