### ISSUE TITLE
Use Semver (Semantic Versioning)

### ISSUE THREAD

**Issue by adius** [AnalyticalGraphicsInc/cesium#2422]
You should consider using [semantic versioning](http://semver.org) for cesium.
It makes it a lot easier for other others to manage cesium as a dependency.
This is also important for publishing on npm. (See #1438)

**Comment by pjcozzi** [comment]
We have considered it, but many of our users have a hard time upgrading to new major version releases (think governments), which prevents us from moving forward with breaking API changes as fast as we would like.  I hope one day this changes, but I don't see it in the near-term.  If we embrace node more, we may be able to make a stronger case here.

**Comment by adius** [comment]
…and what does this have to do with semver? ^^

**Comment by mramato** [comment]
Cesium already mimics semver, with one important exception.

For reference, according to http://semver.org/, the rules are as follows:
1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards-compatible manner, and
3. PATCH version when you make backwards-compatible bug fixes.

For 3: We release monthly so we rarely get to the patch level, but if there was a major problem with 1.6, for example, we would release a 1.6.1 shortly after that.  So this is cut and dry semver.

For 2: Every release of Cesium has new functionality in a BC manner, and this is reflected in our versioning, 1.4 -> 1.5 -> 1.6 all contain new features.  We simply leave off the .0 in our names and tags, but it's implied.  For node or bower, it would most likely be there.

For 1. This is the exception. Cesium is not just a library, it's an engine.  This means there is a rather large API surface area.  Most of the time we make a breaking change, it doesn't affect 99.9% of our users.  We have no desire to bump the major version number in these cases.  We have never made big sweeping breaking changes from release to release and there is always a deprecation period for pending breaking changes.  If we ever do need big changes, it would certainly warrant a 2.0.

So calling how we version Cesium semver is inaccurate, but we are close enough that for most practical purposes you can just treat it like it is. Whether semver itself is good or bad for versioning packages is an entirely different discussion.  In our case, Cesium releases too often and is still under heavy development in many areas to make strict semver a good choice.

**Comment by jony89** [comment]
> For 1. This is the exception. Cesium is not just a library, it's an engine. This means there is a rather large API surface area. Most of the time we make a breaking change, it doesn't affect 99.9% of our users. We have no desire to bump the major version number in these cases.

Why not? this is not an issue. even if cesium will get to version 80.4.2, this is totally fine. see chrome versions for example.

bumping major version is not only for not breaking users projects (although it is the main reason) but also allowing the users to keep track on the project changes. this is a worldwide convention that everyone are using these days. Also, you can't actually determine what is the percentage of the affected users, since you are not exposed to their source code.

I really suggest that we re-think this approach as for example, version 1.63 - moving to es6, many are gonna get  their build broken and it seems that this was missed.

I've written more in details here : https://github.com/AnalyticalGraphicsInc/cesium/issues/8389#event-2795799277

**Comment by ezze** [comment]
Spending an half of a day I'm also finally here because my development environment was broken today for some reason...due to Cesium versioning!

Introducing ES modules in 1.63 breaks the things, and it was impossible to have some deprecation period to migrate safely in this case. I agree that if a change doesn't affect 99.9% of users it's ok to have minor or patch update. But migrating to ES affects 100% of users relying on Cesium sources in their project. So `1.63.0` had to be `2.0.0` instead!

@pjcozzi @mramato Guys, please reconsider switching to semver used by almost all JavaScript (including Node.js) libraries nowadays. For example, dropping support of specific Node.js version is a breaking change for many (if not all) widely used libraries not changed for years (and their maintainers don't hesitate to increase major version number). As a Cesium user for years, I still need an extra time to spend to fix new introduced incompatibilies in my projects relying on it. Imagine if most of libraries would not use semver. It would cost a lot of efforts for people to maintain their projects. Keeping `1` as a major number in each version of Cesium gives you really nothing but unpredicted headaches for people using it in their usual daily development environment. Looking at this, it would be better to have `0` there instead of `1` because each minor update which you publish each month is a breaking change in this case.

As soon as you decide to use npm to publish your package it's [considered a good practice to use semver](https://blog.npmjs.org/post/162134793605/why-use-semver). If Cesium project is large enough, probably, it's time to split it into smaller core libraries following semver, e.g., corresponding to root directories in `Source` such as `Core` (`@cesium/core`), `DataSources` (`@cesium/data-sources`), `Scene` (`@cesium/scene`), `Renderer` (`@cesium/renderer`), etc. At least, we could use them separately and it would give us a much more flexibility than we have today.
