### ISSUE TITLE
Remove Camera.setTransform and Camera.transform

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#2423]
* `Camera.setTransform` was deprecated in Cesium 1.6. It will be removed in Cesium 1.8. Use `Camera.lookAtTransform`.
* `Camera.transform` was deprecated in Cesium 1.6. It will be removed in Cesium 1.8. Use `Camera.lookAtTransform`.

**Comment by pjcozzi** [comment]
Deprecated in #2416

**Comment by lioneldelmo** [comment]
I'm getting a different behavior of 1.6 Camera.transform vs 1.8 Camera.lookAtTransform.
Is there a way to simulate the old behavior of Camera.transform? Basically, I have a model Airplane following a flight path. So I'm changing the position of the model Airplane inside the Ontick event. It was working beautifully using the Camera.transform because it allows me to reorient the camera, zoom in/out, etc. while the Airplane is moving. And now, with Cesium's 1.8, the Camera.lookAtTransform() behaves differently. The Camera is no longer following the model.


Here's my code snippet, that works perfectly in Cesium 1.6

// initially setup the model and camera
     // ..... position the Airplane model by calling a function ... actual code not included for brevity.
var _airCraftModel;
var _camera;

$(function() {
      positionAircraft(longitude, latitude, altitude); // the _airCraftModel gets created here...

      setupCamera(); // relative to the model and based on the EastNorthUpFixedFrame


// here's the actual code showing different behavior between Camera.transform (1.6) vs Camera.lookAtTransform (1.8)

window.setInterval(function(){
       ....
       positionAircraft();


// update the Camera's position...
var center = Cesium.Matrix4.multiplyByPoint(_aircraftModel.modelMatrix, _aircraftModel.boundingSphere.center, new Cesium.Cartesian3());
 var transform = Cesium.Transforms.eastNorthUpToFixedFrame(center);
 
// in Cesium 1.6 (this follows the model aircraft)
_camera.transform = transform; // note: this allows me to zoom in/out, reorient the camera while the aircraft is moving and works beautifully.

// in Cesium 1.8 (this does not follow the model aircraft)
_camera.lookAtTransform(transform);

}, 5000);
});

The question is, is this a known issue? Or is there a way to mimic the behavior of Camera.transform in 1.6 in Cesiume 1.8? Using the Camera.lookAtTransform() does not cut it?
