### ISSUE TITLE
Support CORS in Cesium's development server

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2457]
At least when it is running locally.

After

```
app.use(compression());
```

add

```
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});
```

**Comment by pjcozzi** [comment]
The similar [server.js](https://github.com/AnalyticalGraphicsInc/3d-tiles-samples/blob/master/server.js) in the `3d-tiles-samples` repo already has this.

**Comment by bampakoa** [comment]
@pjcozzi I would like to take on this, if is still relevant.

**Comment by hpinkos** [comment]
Thanks @bampakoa, that would be great!  You can find information for contributing a pull request here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#opening-a-pull-request

**Comment by pjcozzi** [comment]
Go for it, @bampakoa!

**Comment by bampakoa** [comment]
I have made some tests and it seems that requests from different domains are handled correctly from the express server, with the current configuration. Could you please give some more info about the issue?

**Comment by hpinkos** [comment]
@bampakoa I think all we want to do is add this code:
https://github.com/AnalyticalGraphicsInc/3d-tiles-samples/blob/master/server.js#L50-L56

to the copy of `server.js` in master.
https://github.com/AnalyticalGraphicsInc/cesium/blob/master/server.js#L49-L50

**Comment by bampakoa** [comment]
@hpinkos I agree but..is it needed? I mean, even without this code, CORS requests seem to be handled correctly. Sorry about the trouble, but I really need to understand before I act :smile:

**Comment by hpinkos** [comment]
I just tried to use an asset cross origin and it didn't work.  

1. In one console, `node server.js --port 8080`
2. In a second cosole, `node server.js --port 8082`
3. Navigate to `http://localhost:8082/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases`
4.  Paste and run this code sample: 
``` javascript
var viewer = new Cesium.Viewer('cesiumContainer', {
    baseLayerPicker: false,
    imageryProvider: Cesium.createTileMapServiceImageryProvider({
        url : require.toUrl('http://localhost:8080/Source/Assets/Textures/NaturalEarthII')
    })
});
```

You will see CORS errors in the console because the server at localhost:8080 does not allow cross origin access to the server at localhost:8082 that is trying to load the tiles from the first server

Adding the access control headers should fix this

**Comment by bampakoa** [comment]
@hpinkos You were right! I wasn't testing it properly. Thanks for the info.
