### ISSUE TITLE
Cesium does not play well with Normalize.css?

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2479]
@emackey, hopefully this is an easy fix.

I'm using Cesium is a bootstrap-based page and the InfoBox title looks like the below:

![image](https://cloud.githubusercontent.com/assets/1495196/6119990/fe7669ba-b09d-11e4-9ed4-fbb590f4dc09.png)

Bootstrap uses normalize.css under the hood.  Order or css inclusion seems to have no effect.  Given the enormous popularity of these libraries, we should probably look into this sooner rather than later.

**Comment by emackey** [comment]
Bootstrap thinks it's cool to switch the default box-sizing computations for all elements.

```
* {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
```

This makes it "easier for everyone to understand" or something like that, but also makes it different from the old default behavior (which is `box-sizing: content-box;`).

The fix is, we should explicitly specify a box-sizing model on any Cesium widgets that depend on `width`, or `height`, or a combination of `top` / `bottom`, or combo `left` / `right`.  This will take some searching through the CSS to make sure we got all the places, but it's the only way to be tolerant of different global default box-sizing settings.

In the specific example above, the fix is: `.cesium-infoBox-title { box-sizing: content-box; }`
