### ISSUE TITLE
Cesium should stop rendering when the browser is not active

### ISSUE THREAD

**Issue by mmacaula** [AnalyticalGraphicsInc/cesium#2504]
Wondering if it might be useful to use the Visibility API to pause rendering of cesium while the page is not visible to save battery life? 

http://www.smashingmagazine.com/2015/01/20/creating-sites-with-the-page-visibility-api/

**Comment by mramato** [comment]
@mmacaula it's a possibility but the user may not want to stop processing just because it's in the background (for example if you are loading a large data set).  And browsers already stop rendering if you are on a separate tab or minimized.

In either case, we already have #1865 for this issue, so I'm going to close this.  There's also a mailing list discussion about it at https://groups.google.com/forum/#!topic/cesium-dev/cGXhVoUacMg

**Comment by mmacaula** [comment]
Fair enough, thanks as always for the super fast response @mramato !
