### ISSUE TITLE
Billboards sandcastle not working on Safari

### ISSUE THREAD

**Issue by asimps** [AnalyticalGraphicsInc/cesium#2517]
We are aware that Safari is not officially supported by Cesium.  Nevertheless, our Safari implementation is fully working with the exception of billboards.  The billboards sandcastle does not work in Safari (http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Billboards.html&label=Showcases), even when WebGL is enabled.  Your FAQ indicates that Safari should be supported by early 2015.  Is there any update on this?

**Comment by mramato** [comment]
We are constantly monitoring and re-evaluating Safari in order to determine at what point we can officially support it.  Unfortunately the browser seems to be just plain buggy and has several showstopping issues.  Some of these are fixed in the latest webkit nightly builds, but that doesn't help us until it is in an official Safari release (on both iOS and Desktop).  Even the Nightly still has major issues. Please keep an eye on #1805 if you wish to track progress.  

As always, we are completely willing to accept pull requests if you would like to put the effort in to make Safari improvements (even if they are just incremental ones, like fixing the billboard example to work).

In the future, please start a [forum topic](https://groups.google.com/forum/?fromgroups#!forum/cesium-dev) for questions like this.  GitHub issues should only be created for actual bugs; and even then be sure that a similar bug does not already exist (such as #1805).
