### ISSUE TITLE
pick() not returning position in 3D

### ISSUE THREAD

**Issue by JayBlanchard-FugroSDES** [AnalyticalGraphicsInc/cesium#2566]
In local tests as well as the sandbox pick() does not return a position. To repeat use the following code:

    var width = viewer.scene.canvas.clientWidth;
    var height = viewer.scene.canvas.clientHeight;

    var left = viewer.scene.camera.getPickRay(new Cesium.Cartesian3((width / 2) | 0, height - 1));
    var right = viewer.scene.camera.getPickRay(new Cesium.Cartesian3(1 + (width / 2) | 0, height - 1));

    var globe = viewer.scene.globe;
    var leftPosition = globe.pick(left, viewer.scene);
    var rightPosition = globe.pick(right, viewer.scene);

    console.log(leftPosition);  // returns 'undefined'

**Comment by mramato** [comment]
@JayBlanchard-FugroSDES I can't reproduce this.  Your code is picking the bottom center of the screen.  The code works fine when the Earth is actually occupying a pixel at that location and `pick` correctly returns `undefined` when it is not.

It also looks like you are passing a `Cartesian3` to `getPickRay` instead of a `Cartesian2`, that will work (since both have `x` and `y` properties), but it's probably a good idea to change it.

Here's the code I used in Sandcastle:
```javascript
var viewer = new Cesium.Viewer('cesiumContainer');

Sandcastle.addToolbarButton('Pick', function() {
    var width = viewer.scene.canvas.clientWidth;
    var height = viewer.scene.canvas.clientHeight;

    var left = viewer.scene.camera.getPickRay(new Cesium.Cartesian2((width / 2), height - 1));
    var right = viewer.scene.camera.getPickRay(new Cesium.Cartesian2(1 + (width / 2), height - 1));

    var globe = viewer.scene.globe;
    var leftPosition = globe.pick(left, viewer.scene);
    var rightPosition = globe.pick(right, viewer.scene);

    console.log(leftPosition);
    console.log(rightPosition);
});
```

**Comment by JayBlanchard-FugroSDES** [comment]
Changed to picking pixels in the center of the screen which solves the issue. Also changed to Cartesian2.
