### ISSUE TITLE
Rename jsonp to loadJsonp?

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2579]
Or is there a reason it is just `jsonp`?

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/jsonp.js

Compare to 

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/loadJson.js

**Comment by manujain** [comment]
@pjcozzi , if it requires renaming then I would like to take this up. Thanks!!

**Comment by pjcozzi** [comment]
Thanks @manujain.  @shunter what do you think?

**Comment by abhishekvp** [comment]
@pjcozzi Can I try this?

**Comment by pjcozzi** [comment]
@manujain @abhishekvp one of you is welcome to this (please follow the [deprecation guide](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Deprecation-Guide)), but this is not high priority so I would suggest a Cesium demo over this.

**Comment by highcode** [comment]
hello everyone, i am new to cesium, but going through their Idea list for GSOC 2015 i found a project(Refactor Cesium Sandcastle) which i am sure i can work on because i am proficient in the required skills.but the point is i don't know where to start from. I will appreciate any help you can render concerning my request, the application closes tomorrow and i am yet to complete my proposal.
Thanks in anticipation.

**Comment by pjcozzi** [comment]
@highcode Try starting with a small Cesium demo.  Start here: http://cesiumjs.org/2013/04/12/Cesium-up-and-running/
