### ISSUE TITLE
License for data like 3D models

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2588]
Apache 2.0 is for code so it does not cover our 3D models, for example.  The license should allow unlimited use in Cesium-based apps.

**Comment by shunter** [comment]
Out of curiousity, what makes you think Apache is for only for code?  It is perfectly reasonable for content & documentation as well.

**Comment by pjcozzi** [comment]
I always see separate licenses for data and doc - and our tutorials don't have anything explicit.

What do you suggest?  Do nothing?

**Comment by emackey** [comment]
Perhaps we could explicitly state that the terms of Apache 2.0 apply to our code, assets, doc, and test suite.

**Comment by mramato** [comment]
I'm with @shunter here, I'm not sure I see a need for a separate license for data or doc and I wouldn't worry about changing anything until we have an actual reason to do so.  Even more so for #2589, since the reference doc is embedded in and generated from our code, so it would be really confusing to have a separate license there. I did some quick research and lots of projects ([including Android](http://developer.android.com/license.html)) put as much as possible under Apache, including doc and other content.  So as far as Cesium source goes, I think we're clear and I would close both these issues.

As for the Cesium website, we've never really discussed a license there, and I think that it might be worth stating it explicitly, but it's going to be a hassle.  We would need to track down anyone that contributed to it externally (such as guest blog posts) in order to actually put everything under the same license.  We would also have to explicitly mention anything that isn't under the license, such as logos for other products.

**Comment by pjcozzi** [comment]
I'm OK with doing nothing right now.
