### ISSUE TITLE
Modifying polyline entities

### ISSUE THREAD

**Issue by FREEZX** [AnalyticalGraphicsInc/cesium#2595]
Hello,
I'm experimenting with Cesium, trying to create and animate polylines.
In order to animate the polylines i need to change it's positions.
I tried several methods, including changing the `polyline` property on the entity as well as changing the `polyline.positions` property, but in both cases the line disappears, even though the internal values look the same.

Check these gists for Sandcastle that demonstrate this behaviour
[Working](https://gist.github.com/FREEZX/12d4b2144c4471b8b5da)
[Not Working](https://gist.github.com/FREEZX/9bd667aba73bbdf55d02)

Am i doing something wrong or is this a bug?

**Comment by mramato** [comment]
See [this forum post](https://groups.google.com/d/msg/cesium-dev/cgxVE1fBq7M/kPSlpFYqJ48J) for help with animating lines.

In the future, please use the [forum](https://groups.google.com/forum/?fromgroups#!forum/cesium-dev) for support instead of creating new issues on Github, you'll likely get an answer faster that way.
