### ISSUE TITLE
CallbackPositionProperty

### ISSUE THREAD

**Issue by speigg** [AnalyticalGraphicsInc/cesium#2597]
A CallbackPositionProperty with `referenceFrame` and `getValueInReferenceFrame` would be useful.

**Comment by hpinkos** [comment]
@speigg Sorry it took so long to respond to this
This is an interesting idea, but I'm not sure if it's something we would implement.  Can you explain a little bit more about your motivation for wanting this?

**Comment by pjcozzi** [comment]
Closing since there is no update in 1.5 years.  Please reopen with more details if this is still of interest.

**Comment by nsorin** [comment]
I second this, a CallbackPositionProperty would be a useful addition, and I don't understand why it doesn't exist already.
I am using a polyline with a PolylineDashMaterialProperty as material to link 2 entities whose position is determined by a non constant CallbackProperty. To reference the 2 entities' positions in the polyline, I have to use a PropertyArray instead of a PositionPropertyArray (because the latter needs a referenceFrame).
This somehow causes the dashes of the polyline to stretch in a strange way at some angles. This did not happen when I didn't need the callback and simply used a PositionPropertyArray.

Any chance this feature can be implemented in a future version ?
