### ISSUE TITLE
Camera.transform deprecated in Cesium 1.6 equivalent in Cesium 1.8 is Camera.lookAtTransform()

### ISSUE THREAD

**Issue by lioneldelmo** [AnalyticalGraphicsInc/cesium#2627]
I've been using Camera.transform property in Cesium 1.6 and it's working perfectly for me. It allows the camera to follow the model while it's moving and at the same time keeping the camera's state (orientation etc.) while the user is changing the camera on the fly (while the model is moving) such as zooming in/out, rotation, etc. Now in Cesium 1.8 the equivalent is to use Camera.lookAtTransform() function but this does not keep the camera settings. Is this a bug or issue or is there a way to mimic the the behavior of Cesium's 1.6's Camera.transform?

**Comment by WarpDrive** [comment]
Looking at https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Camera.js#L1581

If offset is not defined it simply sets the camera's offset then returns. Maybe instead it should check how many arguments are passed, if for some strange reason offset is defined but not passed? Try calling camera._setTransform(transform) instead camera.lookAtTransform and see if you get the same behavior.

**Comment by lioneldelmo** [comment]
It is exactly what I did after looking at the code by calling the "private method" camera._setTransform(transform) instead of the camera.lookAtTransform() unfortunately it's the same behavior. The good news is, I was able to mimic the 1.6 behavior (camera.transform = transform) in 1.8 by literally copying the old logic which is camera._transform = transform; camera._transformChanged = true;

**Comment by WarpDrive** [comment]
in the updatemembers function:
camera._transformChanged == true invokes the if statement here
https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Camera.js#L418
then camera._transform is used in that if statement

in the _setTransform function
https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Camera.js#L781
it does set those vars then calls updatemembers, but does some other stuff as well. I suppose that other stuff messes with the camera settings? That other stuff seems to be transforming the camera rotation matrix to the new transform.

Is there anyway to invoke updatemembers from the outside? When I type viewer.scene.camera in the console I don't see it. I tried doing Cesium.Camera as well but couldn't find it there either.

**Comment by bagnell** [comment]
The reason transform was remove is because there weren't many use cases for it and it was confusing to have so many ways to set the same property. Many of our code examples that set the camera reference frame also were followed by a lookAt. So, I combined the two. There were only a very few cases where I needed the old behavior, but it is still possible:

`camera.setTransform(transform, Cartesian3.clone(camera.position));`

See the ICRF example in the Sandcastle.

By the way, you shouldn't use any property of function that begins with an underscore. Those are private and we reserve the right to change them at any time. I'm not saying that I know those properties and functions will change, but they could and will most likely break any code that is using them.

This is not an issue so I am closing it.

**Comment by WarpDrive** [comment]
I'm a bit confused by camera.setTransform(transform, Cartesian3.clone(camera.position));
The non-underscore version was deprecated. Also I don't see where either version uses a second argument. I'm guessing that's a typo, and you meant lookAtTranform, which makes sense considering the ICRF example.

**Comment by bagnell** [comment]
@WarpDrive Yes, sorry, I meant `lookAtTransform`.

**Comment by WarpDrive** [comment]
Thanks for the clarification. I see that will retain the position, but not orientation, which snaps to looking at the new origin. Though it would be weird if it didn't snap to looking at the new transform origin.
