### ISSUE TITLE
KML - Double click point and left click functionality breaks

### ISSUE THREAD

**Issue by ckoster22** [AnalyticalGraphicsInc/cesium#2649]
https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=KML.html&label=Showcases

The KML showcase in the Cesium Sandcastle shows 3 sample KML files. Allow it to load the default selected KML, KML - Global Science Facilities, and double click one of the points displayed on the map.

After you are zoomed into that point (is this an intended feature?) you can no longer left click and drag to pan the map. Left click behaves like middle click in that it rotates and tilts the camera. Middle click no longer works.

**Comment by mramato** [comment]
Yes, that is the intended behavior.  Cesium has first class support for time dynamic and moving objects, so when you are double click on something, the default behavior is to go into tracking mode.  You can disable the default double click handling and add your own.  Here's an example that zooms to the entity rather than tracking it.

```javascript
viewer.screenSpaceEventHandler.setInputAction(function(e) {
    var picked = viewer.scene.pick(e.position);
    if (Cesium.defined(picked)) {
        var id = Cesium.defaultValue(picked.id, picked.primitive.id);
        if (id instanceof Cesium.Entity) {
            var entity = id;
            if (Cesium.defined(entity)) {
                viewer.zoomTo(entity);
            }
        }
    }
}, Cesium.ScreenSpaceEventType.LEFT_DOUBLE_CLICK);
```

In the future, please start a [forum discussion](https://groups.google.com/forum/?fromgroups#!forum/cesium-dev) for any questions you might have rather than opening a GitHub issue.  You are likely to get faster responses on the forum (it was a fluke that I answered this so quickly) and more people will see it.  We try to reserve GitHub issues for confirmed bugs.

If you're new to Cesium, I also recommend you check out the [Visualizing Spatial Data](http://cesiumjs.org/2015/02/02/Visualizing-Spatial-Data/) tutorial.  Which will hopefully answer a lot of questions up front.
