### ISSUE TITLE
Entities with bounding spheres do not make use of EntityView.defaultOffset3D.

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#2716]
For example, load the CZML demo in Sandcastle, and try double-clicking some objects to track them with the camera.  The initial view when tracking a new object should have the horizon or the limb of the Earth visible in the default view.  The Molniya in particular should not be shown floating in space with no trace of the Earth anywhere.  It would be great if a unit test would check for Earth visibility in default views of things.

Git bisect shows this broke in 6a507f2e5.  Things work fine in the commit before, ea27cb7c0.

**Comment by mramato** [comment]
This is by design and is a stop gap until EntityView is rewritten or deprecated for a new class that better handles bounding spheres and tracking them.  It's going to have to happen soon because of the vector data on terrain changes.  

I took a quick look and we can make it respect defaultOffset3D, but it should be the same default that the Camera uses for `adjustBoundingSphereOffset`, in Camera.js line 2347.  We can just update defaultOffset3D to match those values for now, ultimately they will probably be unified.  A slightly down looking view oriented north is an optimal default for most of our users.

This change may be wrapped up in larger changes for 1.10, but if not I'll look into opening a PR for just this at some point.

**Comment by emackey** [comment]
A reasonable workaround was merged into 1.10.  Closing.
