### ISSUE TITLE
DeveloperError in new Picking example

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2761]
@bagnell can you look at this for 1.10?

From this horizon view:
- Grabbing the model to zoom towards it moves the camera too quickly like it picked through the model.  Did this break recently?
- Grabbing the model (or sky) can result in a `DeveloperError`:

![image](https://cloud.githubusercontent.com/assets/782098/7871024/345c238c-055b-11e5-9a00-44953ce383d5.png)

**Comment by pjcozzi** [comment]
This is with the left mouse button, not the right, which is probably what I was testing before.  Models should work just like grabbing the globe.

**Comment by bagnell** [comment]
When you look up at the model like that and move towards it, the camera would go under the terrain. The collision detection prevents that so it appears to move faster.

The developer error occurs because for one frame the depth read back for each frustum is 0. I'm not sure why that happens, but I can add a check for `undefined`.

**Comment by pjcozzi** [comment]
#2769 fixes this:

> Grabbing the model (or sky) can result in a DeveloperError:

Leaving this issue open for:

> Grabbing the model to zoom towards it moves the camera too quickly like it picked through the model. Did this break recently?

which is a priority post 1.10

**Comment by hpinkos** [comment]
Could not reproduce this
