### ISSUE TITLE
KML LineStyle not being applied

### ISSUE THREAD

**Issue by maikuru** [AnalyticalGraphicsInc/cesium#2770]
KML line style is not showing up in Cesium (GE KML support shows it's supported already)
The forum has a link to the example KML file.
https://groups.google.com/forum/#!topic/cesium-dev/X2l6vw7ET0g

![screen shot 2015-06-01 at 3 57 17 pm](https://cloud.githubusercontent.com/assets/1457734/7921942/01f2b324-0877-11e5-898b-70bcd912bc79.png)
![screen shot 2015-06-01 at 3 57 51 pm](https://cloud.githubusercontent.com/assets/1457734/7921943/01f2eaec-0877-11e5-8d22-46b512fa9a5d.png)

**Comment by mramato** [comment]
The provided KML is using `StyleMap`, which only has partial support right now.  We have an item on the roadmap to finish implementing it.  I'll try to get to this for 1.11.

CC #2598 #873

**Comment by DylanTusler** [comment]
@mramato I'd like to take a look at this issue, as it is a pain point for my users. Can you point me to the relevant area and I'll see if I can work out what's going on?

Also, was this working in a previous version (prior to 1.10?) I'm not 100% certain, but I think it used to work.

**Comment by mramato** [comment]
@DylanTusler I think the bug is specifically triggered by local style maps (non #id referenced ones).  If you look in `KmlDataSourceSpec.js` there is already a test for these that is excluded because it fails.  If you change `xit` to `it` on line 1190, you can then run that test and debug the problem.

The style handling code itself is in the `processStyles` function (around line 746 in `KmlDataSource`).  That's where you'll need to add support for locally defined styles.  Once that test passes I'm fairly confident your case will work as well.

You'll also need to email in a signed CLA so that we can accept your code, see CONTRIBUTING.MD for the details.

Hope that helps, let me know if you have any questions.

**Comment by mramato** [comment]
Fixed in #3538
