### ISSUE TITLE
Changing the color of an entity

### ISSUE THREAD

**Issue by rtemplin15** [AnalyticalGraphicsInc/cesium#2780]
Is there a way in cesium to dynamically change the color of an entity or part of an entity? Or dynamically changing the color of a mesh or node of the entity?

**Comment by mramato** [comment]
@rtemplin15 it depends on the type of visualization.  See the [Visualizing Spatial Data](http://cesiumjs.org/2015/02/02/Visualizing-Spatial-Data/) tutorial for a good overview of the Entity API.

In the future, please ask questions on [the forum](https://groups.google.com/forum/?fromgroups#!forum/cesium-dev), rather than opening an issue.  More people will see your question and you'll get a faster response.  We try to reserve GitHub issues for confirmed bug reports.
