### ISSUE TITLE
Multiple SVG icons rendering into each other with billboards

### ISSUE THREAD

**Issue by bmckilligan** [AnalyticalGraphicsInc/cesium#2907]
In the following sandle castle example, Using Chrome 32-bit on Windows, latest stable v44,  billboards are created with SVG images.  The images have some fill opacity 

The first billboard image renderes properly, the second renders with the first layered under the third with all three combined.

Clicking on the billbord and viewing the description will show what the billboard icon should be.

things will not run in the latest Firefox version 39
 
```javascript
var viewer = new Cesium.Viewer('cesiumContainer', {timeline : false, animation : false});

var b64 = "data:image/svg+xml;base64,";

var pinkCrossSVG = ['<?xml version="1.0" encoding="iso-8859-1"?>', '<svg width="32px" height="32px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" style="stroke:rgb(0,0,0); stroke-width:2; width:32px; height:32px;" xml:space="preserve">', '<circle cx="16" cy="16" r="14" style="fill-opacity:0.5;fill:#fc99fd;"/>', '<line x1="16" y1="2" x2="16" y2="30"/>', '<line x1="2" y1="16" x2="30" y2="16"/>', '</svg>'];

var circleXSVG = [ '<?xml version="1.0" encoding="iso-8859-1"?>' , '<svg width="32px" height="32px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" style="stroke:rgb(0,0,0); stroke-width:2; width:32px; height:32px;" xml:space="preserve">', '<circle cx="16" cy="16" r="14" style="fill-opacity:0.3;fill:#ffffff;"/>', '<path style="fill:#0000ff;stroke-width:0;" d="M 6.7 6.7 A 13 13 0 0 1 25.3 6.7 L 16 16 Z"/>', '<line x1="6" y1="6" x2="26" y2="26"/>', '<line x1="6" y1="26" x2="26" y2="6"/>', '</svg>'];

var circleX2SVG = [ '<?xml version="1.0" encoding="iso-8859-1"?>' , '<svg width="32px" height="32px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" style="stroke:rgb(0,0,0); stroke-width:2; width:32px; height:32px;" xml:space="preserve">', '<circle cx="16" cy="16" r="14" style="fill-opacity:0.3;fill:#ffffff;"/>', '<line x1="6" y1="6" x2="26" y2="26"/>', '<line x1="6" y1="26" x2="26" y2="6"/>', '</svg>'];

var circleX = b64 + btoa(circleXSVG.join(''));
var circleX2 = b64 + btoa(circleX2SVG.join(''));
var pinkCross = b64 + btoa(pinkCrossSVG.join(''));

var circleXBB = viewer.entities.add({
    name : 'circle X',
    position : Cesium.Cartesian3.fromDegrees(-75.169, 39.922),
    billboard : { image : circleX },
    description: '' + circleXSVG.join('') + '' });

var pinkCrossBB = viewer.entities.add({
    name : 'Pink Cross',
    position : Cesium.Cartesian3.fromDegrees(-75.170 , 39.922),
    billboard : { image : pinkCross },
    description: '' + pinkCrossSVG.join('')+ '' });

var circleXBB2 = viewer.entities.add({
    nme : 'circle X2',
    position : Cesium.Cartesian3.fromDegrees(-75.171, 39.922),
    billboard : { image : circleX2 },
    description: '' + circleX2SVG.join('') + '' });

viewer.zoomTo(viewer.entities); 
```

![image](https://cloud.githubusercontent.com/assets/3451886/8940631/ed239168-3538-11e5-8480-dede10533234.png)

**Comment by hpinkos** [comment]
Thanks @bmckilligan!  This is definitely unusual behavior.

**Comment by mramato** [comment]
This is a bug in Chrome, not Cesium.  Cesium does not do anything special in treatment of SVGs and simply loads the image using browser functionality.  We have no control over the behavior you are seeing.  I would recommend you file the above code as a [Chrome bug](https://code.google.com/p/chromium/issues/list).  If you do, please add the link to this issue.

Your code sample had a bug preventing it from working in Firefox.  `width` and `height` need to be specified as [top-level attributes to the svg element](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/width) and not part of the style.  Since it was not specified, Firefox assumed the SVG width and height were huge (which made it impossible to create as a texture).  I edited your post to fix the code and everything now works perfectly in Firefox.

Note it still won't work in IE because of it's aggressive security policies on SVG data uris which results in them being marked as tainted by the browser (preventing usage in WebGL).

I'm closing this issue, but please let me know if you have any other questions and if you decide to file a Chrome bug, let us know.  Thanks.

**Comment by bmckilligan** [comment]
quickly looking through the chrome bugs I cam across this

https://code.google.com/p/chromium/issues/detail?id=500180

**Comment by mramato** [comment]
@bmckilligan thanks!  That definitely looks like the culprit.  It's disappointing that SVG is still inconsistent from browser to browser.
