### ISSUE TITLE
3d-tiles branch: get BatchId from property Value 

### ISSUE THREAD

**Issue by jbo023** [AnalyticalGraphicsInc/cesium#2937]
Hi Cesium Team, 

we started to investigate the 3d-tiles spec and the cesium 3d-tiles branch and we are really happy with the first internal results. 

To manipulate the model, we would like to have a function to retrieve the batchID based on a property-value. 
Do you plan to add a function like this, or did i overlook another existing solution?

```javascript
 /**
     * returns an array of batchIds for a given property and property-value
     * @param {String} property
     * @param {String|Number} value
     * @return {Array} 
     */
    Batched3DModel3DTileContentProvider.prototype.getBatchIdsByProperty = function(property, value) {
        //>>includeStart('debug', pragmas.debug);
        if(!this.hasProperty(property)){
            throw new DeveloperError('property: ' + property + ' does not exist in this batchTable');
        }
        //>>includeEnd('debug');
        var batchIds = [];

        if (!defined(this._batchTable)) {
            return batchIds;
        }
        var propertyValues = this._batchTable[property];

        if(defined(propertyValues)){
            for(var i = 0; i < propertyValues.length; i++){
                if(value == propertyValues[i]){
                    batchIds.push(i);
                }
            }
        }
        return batchIds;
    };
```

I can also create a pull request if requested.

Jannes

**Comment by pjcozzi** [comment]
@jbo023 thanks for the interest, the team is at SIGGRAPH this week.  I'll get back to you about this next week.

**Comment by pjcozzi** [comment]
@jbo023 sorry for the delay, I agree this is useful.

Please send in a [CLA](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md) and open a pull request.

Instead of returning batch IDs, return `BatchedModel` instances like [getModel](https://github.com/AnalyticalGraphicsInc/cesium/blob/3d-tiles/Source/Scene/Batched3DModel3DTileContentProvider.js#L404).  Perhaps name this `getModels`.

Also, use `===` instead of `==` and allow the array to be passed in as a `result` parameter so the user can save on memory allocations.

**Comment by pjcozzi** [comment]
See https://github.com/AnalyticalGraphicsInc/cesium/pull/3080#issuecomment-166707331

Please open a new pull request if there is something else you want to contribute.
