### ISSUE TITLE
Add WebStorm setup to the Contributor's Guide

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3007]
@lilleyse has a list of recommended settings and there is the [webstorm](https://github.com/AnalyticalGraphicsInc/cesium/compare/webstorm) branch.

**Comment by mramato** [comment]
The branch has a configuration that mostly matches Eclipse auto-formatting that we already use.  Since ant build targets aren't supported in webstorm, there's no way to run tasks currently.  We could probably build a gulp task that call through to the ant tasks (and in the long run, just switch over to npm/gulp tasks as we port the ant ones.

**Comment by mramato** [comment]
The guide was updated after #3041 was merged.  WebStorm has very little configuration necessary but if we run into things that we need to tweak, we'll expand the guide.
