### ISSUE TITLE
Fix sandcastle development links in reference documentation

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3020]
There are a bunch links in the reference documentation to sandcastle demos that got moved to the development folder.  This includes all of the outline geometry types, material/appearance examples and some primitive examples.

For example,

`* @demo {@link http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Box%20Outline.html|Cesium Sandcastle Box Outline Demo}`

needs to be changed to

`* @demo {@link http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=development/Box%20Outline.html|Cesium Sandcastle Box Outline Demo}`

or removed from the documentation entirely.

**Comment by emackey** [comment]
Note the development demos are not hosted on cesiumjs.org, so just changing the path of the link won't work.  You have to point to localhost, or remove the link.

**Comment by hpinkos** [comment]
@emackey The tab isn't there to click to get to the link, but the demos are still hosted and still work.  Maybe that's a mistake, but go to http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=development/Box%20Outline.html&label=undefined to see

**Comment by emackey** [comment]
Is there good reasoning to display this tab locally and hide it from the main website?  I know we prefer folks to use Entity API where possible, but the graphics primitives are still public API.

**Comment by mramato** [comment]
We should just get rid of the links.  Most of those examples will be changing and going away.  They do not ship with the zip file.  The only reason the website direct link works is because we host the entire source tree.

**Comment by rutsky** [comment]
@mramato, will demos of using Primitive API will be removed?

Removing working examples of Primitive API will make using low-level interfaces of Cesium one step harder.

I understand that for most end users Entity API should be enough and more desirable than low-level Primitive API, but some users still need to be able to do low-level stuff, like writing custom shaders.

Recently I needed to [show polygons only on some distance range](https://groups.google.com/forum/#!topic/cesium-dev/3AneXDTuvTU) and I spent some time lurking through old Cesium blog posts about Renderer and Appearances, and Cesium source code to find what it is and how to use `czm_sceneMode`, `czm_encodedCameraPositionMCHigh`, `czm_encodedCameraPositionMCLow`, etc.

Currently specifying shaders in Appearances is documented in API, but what can be inside shaders are not documented (most probably because it's subject to change between releases).
Will low-level API will be released/documented (at least as experimental API that can and will be changed between releases)?

**Comment by pjcozzi** [comment]
> will demos of using Primitive API will be removed?

No, we use them for testing during Cesium development.  They are not visible in the released Sandcastle  because we want to encourage use of the Entity API.

> Will low-level API will be released/documented (at least as experimental API that can and will be changed between releases)?

If the low-level API is public, it should already be documented, but there may be some gaps as you noted with the GLSL.

If it is not public, like today's Renderer, it will not be documented since it may change from release to release.  For example, we are making significant changes to the Renderer over the next several months for WebGL 2.

**Comment by rutsky** [comment]
> If the low-level API is public, it should already be documented, but there may be some gaps as you noted with the GLSL.

Should GLSL `czm_*` uniforms/functions be documented or they are considered as part of Cesium internals?

If currently public API should be enough to write custom vertex/fragment shader it would be nice to have working example for it (at least simple, like how to change color/size through uniform controlled from JavaScript).

**Comment by AmayAgrawal** [comment]
So sir we want to remove or update the links as shown by @hpinkos.

**Comment by pjcozzi** [comment]
Hi @AmayAgrawal - it is fine to just remove them.

**Comment by hpinkos** [comment]
Fixed in #3480
