### ISSUE TITLE
Update eclipse to latest version of JSHint

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3208]
Until we stop supporting Eclipse, we should keep it up to date.  After #3202, there are a bunch of JSHint warnings in the tests:

![image](https://cloud.githubusercontent.com/assets/782098/11182754/2e9c10d0-8c3b-11e5-9ef3-4c04e659704a.png)

Do we have instructions for upgrading?

**Comment by mramato** [comment]
I'm looking into this.  It's my fault for not checking Eclipse after my changes.  Apparently we have an entirely separate jsHint configuration in Eclipse instead of the jshintrc files.

**Comment by mramato** [comment]
This isn't a version issue.  If you "Check for software updates" on the Eclipse help menu, you'll have the latest version of everything, including the `jshint-eclipse` plugin that we use.

The problem is that the `jshint-eclipse` project plug-in doesn't support multiple .jshintrc files, which is a pretty big flaw.  We might be able to work around this restriction but I need to think about it some more.
