### ISSUE TITLE
Toggling map 2D / 3D while there is a tracked entity results issues

### ISSUE THREAD

**Issue by ZacBrownBand** [AnalyticalGraphicsInc/cesium#3215]
While a viewer has a set tracked entity, if the map is changed from 2D to 3D or 3D to 2D the camera does not continue following the entity. It gets stuck at a single location that is not where the entity is.

Reproduce: 
1 - Start a sandcastle with the attached code snippet (From this [post](https://groups.google.com/forum/#!topic/cesium-dev/Q4i9jEJ4Sjg) curtesy of Hannah)
2 - Zoom in a little to ensure the entity is moving and that the camera is following the entity
3 - Using the widget in the upper right, select the 2d view

Result: The camera is no longer tracking the entity, and is not able to be panned.
```javascript
var viewer = new Cesium.Viewer('cesiumContainer', {timeline : false, animation : false});

var pinBuilder = new Cesium.PinBuilder();
var lon = -70;
var lat = -39;

var bluePin = viewer.entities.add({
    name : 'Blank blue pin',
    position : Cesium.Cartesian3.fromDegrees(lon, lat),
    billboard : {
        image : pinBuilder.fromColor(Cesium.Color.ROYALBLUE, 48).toDataURL(),
        verticalOrigin : Cesium.VerticalOrigin.BOTTOM
    }
});

viewer.trackedEntity = bluePin;

setInterval(function(){
    lon += 0.00001;
    bluePin.position = Cesium.Cartesian3.fromDegrees(lon, lat);
}, 30);
```

**Comment by hpinkos** [comment]
Hello @ZacBrownBand! Thank you for reporting this.

You're seeing the behavior because we are still tracking the entity after the scene mode change.  If you zoom all of the way back in to the entity in 2D, you'll see that the camera is moving along with it.

However, since the camera doesn't zoom back in automatically, I don't think that is really the expected behavior.  I submitted #3321 to clear the tracked entity on scene mode change instead.

Eventually, we do want to return to the same camera position after scene mode change, but it may be a while until we implement that.  We have an issue to do it here: #2647.
