### ISSUE TITLE
Replace shadowed properties with property getter/setters

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3298]
Before Cesium had property getter/setters, it used shadowed properties to avoid computation unless a property actually changed, e.g.,
```javascript
// in the constructor function:
this.modelMatrix = Matrix4.clone(defaultValue(options.modelMatrix, Matrix4.IDENTITY));
this._modelMatrix = Matrix4.clone(this.modelMatrix);

// then later in update():
if (!Matrix4.equals(this._modelMatrix, this.modelMatrix)) {
    Matrix4.clone(this.modelMatrix, this._modelMatrix);
    // Do slow stuff
}
```
I'm pretty sure we can replace all these use cases with a dirty flag and property getter/setters, and improve or maintain performance (well, some pathological cases would be slower) and use less memory, e.g.,
```javascript
// in the constructor function:
this._modelMatrix = Matrix4.clone(defaultValue(options.modelMatrix, Matrix4.IDENTITY));
this._modelMatrixDirty = false;

// then
defineProperties(Model.prototype, {
    viewport : {
        get : function() {
            return this._modelMatrix;
        },
        set : function(value) {
            if (!this._modelMatrixDirty && !Matrix4.equals(value, this.modelMatrix)) {
                Matrix4.clone(this.modelMatrix, value);
                this._modelMatrixDirty = true;
            }
        }
    }
});

// then later in update():
if (this._modelMatrixDirty) { // Just check flag now, not basically linearly search to compare elements
    this._modelMatrixDirty = false;
    // Do slow stuff
}
```
This would be a good beginner issue.  Is there a reason we didn't do this yet?  Just time?

**Comment by mramato** [comment]
> Is there a reason we didn't do this yet? Just time?

We haven't done it because it will likely destroy performance. For example, the Entity API uses getters/setters everywhere but the visualizers "cheat" and use the hidden raw property to avoid calling the getters every frame because performance tanks otherwise.  We can get away with this because outside of the visualizer, entity getter/setters aren't accessed very often.  If we wanted to produce exact numbers, it only takes 5 seconds to change BillboardVisualizer over to getter/setters and then we can profile with a a large amount of billboards. (I just tried it and there was definitely a noticeable difference in performance for our example facilities.kml in Chrome). On browsers that are already slow (Safari and IE) I'm guessing the performance hit will be even worse.

Now in this specific case, the performance hit of the getter/setter may help offset the equals/clone call every frame, however that assumes that the getter is almost never called, which is unlikely.  At the very least, you would want to avoid using `this.modelMatrix` anywhere in the object.  For example, in your setter example code calls it twice and instead should be `this._modelMatrix`.

Also, it just occurred to me that this is a breaking change that will subtle and hard to track down in user's code if there's a problem.  That's because right now you can use properties as result parameters and change them directly, where as in your new code you can't do that and have to create a new instance, which will be another hit to performance unless you start doing tricks like caching and swapping.  For example in the ModelVisualizer we have code like:

```javascript
//Shared scratch
var scratch = new Matrix4();

models.forEach(function(model){
    //calculate model modelMatrix using scratch parameter.
    ...
    ///clone scratch into primitive
    model.modelMatrix = Matrix4.clone(scratch, model.modelMatrix);
}
```

The above code will not work with the changes you are suggesting because the dirty flag will never get set.

Finally, `get` should return the exact value that supplied to `set`, not doing this is another breaking change and also considered universally bad API design.  You would also want to get rid of the equals comparison in set and always set to dirty, otherwise there could be additional odd semantics for the property, such as getting it, modifying it, and setting it back not working.  If you want to keep equals, you would have to add back a shadow property.

When I started writing this up, I was going for "try and see", but after thinking about it some more and for all of the reasons I laid out above, I don't think we should make this change and instead keep what we have now (and standardize when to use shadow properties in the coding guide).

**Comment by pjcozzi** [comment]
> That's because right now you can use properties as result parameters and change them directly...

Ah yes, I forgot about this.  It bit me before.  It could be reason enough to not do anything.  Cesium as a whole is inconsistent here, but it is not pressing.

Are get/set slow because the JavaScript compilers are not good at inlining them?  If this is the main problem, perhaps we can reevaluate in a year or so.

**Comment by mramato** [comment]
> Are get/set slow because the JavaScript compilers are not good at inlining them?

I honestly don't know for sure, but I would guess yes.  Even on Chrome and Firefox, where they have done optimization work, they still have the same overhead as a function call (at best).  On IE and Safari performance was pretty terrible last time I checked.

Using more properties to make our codebase cleaner is definitely something we revisit all of the time but I'm not sure it's worth keeping this issue open for that purpose.

**Comment by pjcozzi** [comment]
I agree.
