### ISSUE TITLE
Capability of point cloud module

### ISSUE THREAD

**Issue by ShineSong** [AnalyticalGraphicsInc/cesium#3353]
Hi devs,
    I want to know the capability of CESIUM on point cloud support.How big dataset it can visualize?I have a MLS dataset,include 2.17 bilion points,and trajectory is about 29 km long,average point density is 551 point/m^2.Total size of these .las files is about 61.5GB.
    Can CESIUM deal with such big dataset?
    Thank you very much!!!
    kind regards.

**Comment by pjcozzi** [comment]
Hi @ShineSong - this is on the roadmap.  See [3D Tiles](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/README.md).

Also, please post questions on the [forum](http://cesiumjs.org/forum.html) since a lot more people will see it.  See [CONTRIBUTING.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md).
