### ISSUE TITLE
DAE to glTF conversion problem

### ISSUE THREAD

**Issue by harryxue1999** [AnalyticalGraphicsInc/cesium#3377]
![screen shot 2015-12-26 at 4 26 09 pm](https://cloud.githubusercontent.com/assets/12103898/12008413/cd86e428-abed-11e5-9fdb-742d4f2547dd.png)
### Conversion Problem   
The left part is a model in .dae COLLADA format, while the right part is one in .glb glTF format. This happened multiple instances where the converter does not pick up the components/mirrored parts/aliases while converting. Is there a solution?

**Comment by pjcozzi** [comment]
Thanks for the report.  This is most likely the same issue as #1754.

Since that issue was written, we actually changed the spec to be strictly a tree, not a graph, so the fix will be in the converter (https://github.com/KhronosGroup/glTF/issues/401), not Cesium proper.

I'm going to close this as a duplicate.  Please let us know if you think it is another issue.
