### ISSUE TITLE
Allow custom crs function for GeoJSONDataSource

### ISSUE THREAD

**Issue by malaretv** [AnalyticalGraphicsInc/cesium#3379]
I'm attempting to use GeoJsonDataSource to load data for a non-earth datum.

There does seem to be the beginnings of support for the `crs` geojson field in the GeoJsonDataSource source, but the `crsNames` object it looks up again only includes variants of epsg:4326. There is no obvious path to extending this object to allow support for custom definitions.

It'd be nice to expose an option such as `crsFunction` when calling GeoJSONDataSource that allows the user to provide their own custom transform function.

**Comment by malaretv** [comment]
Looking into it a bit further I was able to accomplish what I needed with the following

```
// Add custom projection that supports my globe's ellipsoid
Cesium.GeoJsonDataSource.crsNames['customProj'] = (coords) =>
      Cesium.Cartesian3.fromDegrees(coords[0], coords[1], coords[2], customEllipsoid);

// Add crs property to geojson dataset
geojsonData.crs = {
  type: 'name',
  properties: {
    'name': 'customProj'
  }
}

// Load 
Cesium.GeoJsonDataSource.load(geojsonData)
```

It's a bit cumbersome but it works

**Comment by dwhipps** [comment]
I second this. I need to modify the crsFunction for USGS Earthquakes, which pass a "depth in kilometers"  as the third parameter of their coordinates object.

**Comment by mramato** [comment]
@dwhipps I just [replied](https://groups.google.com/d/msg/cesium-dev/U9ROwJKmboE/sPBXe4icCgAJ) to your forum question regarding the USGS data (link goes to the answer).  The problem @malaretv was describing sounds like a different issue. i.e. he has a custom crs in the data and needs Cesium to process it.  This is already supported by simply adding a function to the `crsNames` object

```
Cesium.GeoJsonDataSource.crsNames['myCrsName'] = function(coordinates){
    //return Cartesian3 converted from coordinates array
}
```

@malaretv your original assumption that crsNames were for WGS84 only is incorrect, you can assign any function you want and it will work, as long as the returned Cartesian3 is in the fixed reference frame for whatever your Scene's ellipsoid is using.  It sounds like you already figured that out though.

Since this is not the same issue that @dwhipps was running into,I'm going to reclose it.  I'll open a trivial PR to support his use case some time soon.
