### ISSUE TITLE
Adding Proxy Support in createDefaultImageryProviderViewModels.js

### ISSUE THREAD

**Issue by bellengj** [AnalyticalGraphicsInc/cesium#3398]
In ./Source/Widgets/BaseLayerPicker/createDefaultImageryProviderViewModels.js can Proxy support be added because I have installed Cesium on a non-Internet network and I want to be call a layer that needs a Proxy

This would require the addition after line 3

        '../../Core/DefaultProxy',

and after line 12

        DefaultProxy,

**Comment by mramato** [comment]
`createDefaultImageryProviderViewModels` is a private function meant to create the basic view models used by Viewer.  None of them rely on a proxy.  If you have your own set of imagery providers that you would like to use, you should be passing them into the Viewer constructor (or BaseLayerPicker constructor if you're calling it directly).  The default set is meant for out of the box demo purposes and shouldn't be used as is in a production application.

Perhaps I'm misunderstanding what you are trying to do?  Please explain in more detail.

Also, in the future, please use [our forum](https://groups.google.com/forum/#!forum/cesium-dev) for questions first instead of filing a GitHub issue, you'll get a faster response and it will help us keep our issue list clean.  Thanks.
