### ISSUE TITLE
Figure out why TMS layers generated with gdal2tiles geodetic profile do not work

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3540]
When creating layers with gdal2tiles, using the geodetic profile seems to generate tilesets that are unusable in Cesium. Geodetic is actually the preferred profile because it avoids reprojection (thus providing better performance).

This could be a bug in gdal2tiles or it could be a bug in Cesium, either way we should figure it out to be sure.

Originally discussed as part of #3489

**Comment by Docteh** [comment]
Looks like this is still a bug. Maybe the TileSet statements in the tilemapresource.xml file are being ignored? The tiles that gdal2tiles cranks out are in the wrong zoom level

In Source/Assets/Textures/NaturalEarthII/1 (part of cesium) its got four subdirectories 0,1,2,3

In the tiles I created from nasa blue marble the 1 zoom level only has two subdirectories. 

I then tried tinkering with the units-per-pixel values in  tilemapresource.xml to see if I could convince Cesium to treat the layers differently No go

I moved all the zoom levels up a level and that seems to have fixed things.


![2018-03-07 globe not working](https://user-images.githubusercontent.com/190571/37118702-fb378fa0-2209-11e8-89ad-9507c600bdd0.png)
![2018-03-07 globe working](https://user-images.githubusercontent.com/190571/37118724-07a3bee4-220a-11e8-8b74-1041258fb242.png)

I don't understand this tile map stuff enough to say for sure where the problem is, but tweaking gdal2tiles.py to treat its zoom levels differently might be easier.

**Comment by Docteh** [comment]
According to [this specification](https://wiki.osgeo.org/wiki/Tile_Map_Service_Specification#global-geodetic) the issue is with gdal2tiles, as on the specification they state that 

> This scaling allows an initial zoom level that consists of 2 256x256 pixel tiles covering the whole earth, with an `<Origin>` of (-180,-90). Other combinations of tile size and `<Origin>` are also possible at this scale.

I only got one tile when I asked gdal2tiles for level 0, posting it below

![0](https://user-images.githubusercontent.com/190571/38118642-07810c3c-3371-11e8-8b0d-cc83283c40c7.png)

As a code based work around, this WorksForMe(tm), just need to specify `minimumLevel: 1` or higher when declaring the ImageryProvider

```javascript
var gdalscheme = new Cesium.GeographicTilingScheme({ numberOfLevelZeroTilesX: 1, numberOfLevelZeroTilesY: 1 });
// numberOfLevelZeroTilesY as 0.5 doesn't work, overriding a function to make it so
gdalscheme.getNumberOfYTilesAtLevel = function(level) { return 1 << (level-1); }


```

**Comment by kevinstadler** [comment]
Just to confirm that this is indeed a quirk of `gdal2tiles.py`'s geodetic profile. I spent ages trying to get the tiles to display correctly in OpenLayers 3. Instead of shifting the zoom levels I ended up manually specifying a TileGrid with the `[-180, -90]` origin to get it to parse the existing tiles correctly. Either way, you can probably close this ticket, as it's clearly a gdal2tiles bug!

**Comment by mramato** [comment]
Thanks @kevinstadler, I agree that there's probably not a good way to work around this automatically on the Cesium side and I've used other geographic tiles in Cesium without issue since writing this up.

**Comment by Docteh** [comment]
I know I'm a little late, but if anyone else sees this, but I found a  --tmscompatible option in gdal2tiles, I'm not sure where to put mentions to it, I only found it after reading the code. 

```
  -d, --tmscompatible   When using the geodetic profile, specifies the base
                        resolution as 0.703125 or 2 tiles at zoom level 0.

```

**Comment by mramato** [comment]
Thanks for the follow-up @Docteh, I think this issue is the perfect place for your note.
