### ISSUE TITLE
3d-tiles: billboards with transparent image will not show 3D tiles through transparent parts

### ISSUE THREAD

**Issue by e-andersson** [AnalyticalGraphicsInc/cesium#3550]
I'm not sure to what extent billboards should be expected to work with 3D tiles.

If I add a billboard with a png image, part of which is transparent, the transparent part will show the base map imagery even if there are 3D tile models that in between.

This is the order of things, from the camera:
`Camera ---> billboard --- 3D tile ---- base map imagery (covered from this angle by 3D tile)`

Any idea about why this happens? Should we wait for better integration of billboards with 3D Tiles?

**Comment by mramato** [comment]
This is a bug with billboards in general, see #2130.  @bagnell has had a potential fix for a while but I believe it adds extra draw calls that @pjcozzi wanted to avoid for performance reasons.  Personally, this is near the top of my most wanted list for bug fixes (and is totally worth a performance trade-off if it's not too bad); but I'm no expert in this area so I'll have to defer to them.

Since this is a duplicate, I'm going to close this, but feel free to continue the conversation in the linked bug.  Thanks.

**Comment by e-andersson** [comment]
Thanks @mramato, will keep an eye on the existing issue.
