### ISSUE TITLE
ThirdParty/knockout-3.2.0 not included in built release

### ISSUE THREAD

**Issue by nmschulte** [AnalyticalGraphicsInc/cesium#3628]
I've been playing with Cesium and [jspm](http://jspm.io/)/[SystemJS](https://github.com/systemjs/systemjs), and I think I've stumbled upon an issue with the pre-built flavors of the release (as published to npm).

SystemJS is having trouble resolving the `"ThirdParty/knockout-3.2.0"` dependency.  Looking at the built source (Cesium.js), there is no module definition for `"ThirdParty/knockout-3.2.0"`, but there are references to (dependencies upon) it.  I'm not sure if this is a regression from the Knockout 3.2.0 update; I will test with previous releases (with older Knockout versions) to see and follow up.

**Comment by shunter** [comment]
`ThirdParty/knockout-3.2.0` is indeed defined as a module in the built file (check http://cesiumjs.org/releases/1.18/Build/CesiumUnminified/Cesium.js and search for `ThirdParty/knockout-3.2.0`)

However, because we just pull in the Knockout release file, there is different boilerplate than in most Cesium modules.

Perhaps this Knockout issue is related?  https://github.com/knockout/knockout/issues/1810

**Comment by nmschulte** [comment]
Thanks @shunter; I'm thinking you're on the right path.  I don't know how I missed that `define`.  I'll test your ideas and see what I find.

**Comment by nmschulte** [comment]
@shunter it looks like upgrading to Knockout 3.4.0 did resolve the issue.  I'm running into other issues now so I couldn't test that the upgrade didn't have breaking API changes, but it would be great if a Knockout 3.4.0 was on the radar.  I'll let you close or modify this issue as you see fit; thanks for chiming in!
