### ISSUE TITLE
Billboard can't set the min and max scale

### ISSUE THREAD

**Issue by bicealyh** [AnalyticalGraphicsInc/cesium#3642]
Billboard can't set the minimum  and maximum scale, let it display interval  the minimum  and maximum scale.

**Comment by mramato** [comment]
@bicealyh In the future, please ask questions [on the forum](http://cesiumjs.org/forum.html) instead of filing a GitHub issue.

I think what you are looking for is the billboard [scaleByDistance](https://cesiumjs.org/Cesium/Build/Documentation/BillboardGraphics.html#scaleByDistance) property you can use to give them a min and max scale.
