### ISSUE TITLE
geocoding locations

### ISSUE THREAD

**Issue by MannusEtten** [AnalyticalGraphicsInc/cesium#3686]
i used the simple interface and filled in an address

first in the flat view: margit sziget (in budapest Hungary)
--> wrong location

so i switched to the 3d version:
--> correct location

did i something wrong?

**Comment by hpinkos** [comment]
Thanks for reporting this @MannusEtten!  I've tracked down the problem to an error in our Camera.flyTo function.   I've created an issue here with more details: #3688 

For now, if you set the geocoder's `flightDuration` to zero, it will go to the correct location.
Add this to your code: 
```
viewer.geocoder.viewModel.flightDuration = 0;
```

I'm going to close this issue since it's covered by the issue I opened.  Thanks!
