### ISSUE TITLE
Karma test performance

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3735]
Do I have something set wrong?

The Jasmine tests take 54 seconds to run in Chrome.  Running `npm run test -- --browsers Chrome` takes 9 minutes and includes some async callback failures, but I don't think they are the only performance issue.

**Comment by mramato** [comment]
What OS are you on?

On my Windows machine (though I've run Linux at home without issue as well) `npm run test -- --browsers Chrome` takes 55 seconds. (BTW, `npm run test` will just use Chrome by default and also takes 55 seconds on my system).

1. Can you try `npm run test -- --browsers Electron`  to make sure it's not something weird with how Chrome is configured on your machine. (That took 53 seconds for me).
2. What happens if you run from WebStorm (Just hit the run button in the upper right corner?).
3. Have you tried blowing away `node_modules` and re-running `npm install` to make sure there's not a problem there?
4. What version of Node are you running `node --version`

**Comment by pjcozzi** [comment]
(3) fixed it.  I tried running `npm install` before, but I did not clear out `node_modules`.  Thanks!

BTW this is Windows and they run in 52s.

**Comment by mramato** [comment]
:+1:
