### ISSUE TITLE
projecting units

### ISSUE THREAD

**Issue by MannusEtten** [AnalyticalGraphicsInc/cesium#3742]
i have a webmercator projection with meters as units.
how can i easily and quickly reproject them to degrees?

and for a rectangle (bounding box) i have to define also an ellipsoid which uses radians...

so now i am wondering how to define a bounding box which is originally in meters to one which is proper to use in the rectangle property of ArcGisMapServerImageryProvider(options)

**Comment by hpinkos** [comment]
Hello @MannusEtten.  Please use our forum to ask questions like this: https://groups.google.com/forum/?hl=en#!forum/cesium-dev

This functionality is not included in Cesium.  You can't easily convert meters to a longitude/latitude position because meters per degree changes depending on what part of the ellipsoid you are on.  You might be able to find a formula to help you with this calculation.

**Comment by lilleyse** [comment]
I've used this function before to convert from meters to longitude/latitude in radians, but you have to know the center latitude ahead of time:

```
var longitudeExtent = width * 0.000000156785 / Math.cos(latitude);
var latitudeExtent = length * 0.000000157891;
```

**Comment by hpinkos** [comment]
@MannusEtten Check out the [WebMercatorProjection](http://cesiumjs.org/Cesium/Build/Documentation/WebMercatorProjection.html) class.
I think I misunderstood your question the first time I read it through, but this class might be what you're looking for.
