### ISSUE TITLE
Eclipse workspace errors

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#3786]
I know Eclipse is no longer the primary IDE for Cesium, but, is there a quick fix for this?

![eclipseerrors](https://cloud.githubusercontent.com/assets/1235080/14090379/f9af5ca2-f507-11e5-908f-ca6713623c17.png)

**Comment by mramato** [comment]
This looks like a bug in Eclipse's JavaScript tools, it looks like it's misinterpreting the `.catch` as a `try/catch` catch instead of the function call that it is.

Unless @shunter has any ideas here, I'm not sure what we can do about it or our side.

You might be able to go into the project preferences and disable this specific error check.
