### ISSUE TITLE
Visualizers not releasing removed Entity

### ISSUE THREAD

**Issue by ramosta** [AnalyticalGraphicsInc/cesium#3916]
reported on forum:
https://groups.google.com/forum/#!topic/cesium-dev/wWLO8PmYlFk
https://groups.google.com/forum/#!topic/cesium-dev/Cm2cWe3Z4ew

Visualizers (PointVisualizer, BillboardVisualizer, possibly others) don't release the reference to an entity that was requested to be removed.

In BillboardVisualizer, for example, the billboard primitive's "id" is set to its corresponding entity in the update function.When that entity is removed, _onCollectionChanged calls returnBillboard. The billboard primitive is kept for reuse with show set to false and image to undefined, but the id remains set to the entity, so the entity can't be garbage collected until the billboard primitive is actually reused.

**Comment by mramato** [comment]
Thanks for the report @ramosta.  In most cases, this isn't an issue because removing a datasource will destroy the primitives, which cleans up the id references anyway and allows the data to be GCed. That being said, I don't see why we couldn't more aggressively clean up the `id` references to allow for earlier GC, so I'll open a PR to make that change.  Given the non-deterministic nature of browser GC, however, you might not actually see any improvement in memory usage and even if we left the code alone; I'm not sure of a use case that would actually cause a problem.
