### ISSUE TITLE
CI deploys branches to master?

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3937]
Is it possible that CI deploys branches to the hosted `master` directory?  See #3934.

**Comment by mramato** [comment]
We use the `TRAVIS_BRANCH` environment variable, which apparently has different behavior depending on how the build is triggered, as defined here: https://docs.travis-ci.com/user/environment-variables/

> TRAVIS_BRANCH:For builds not triggered by a pull request this is the name of the branch currently being built; whereas for builds triggered by a pull request this is the name of the branch targeted by the pull request (in many cases this will be master).

I'm not exactly sure what they mean by "triggered by a pull request", vs normal CI operations; however there are two settings in the config gui, one for "Build pushes" and the other for "Build pull requests".  I'm guessing disabling the latter will give us what we want.

**Comment by mramato** [comment]
I disabled the `build pull requests` setting for now and we'll see what happens.

**Comment by pjcozzi** [comment]
Thanks for looking into this.  Feel free to close this once it is confirmed.

**Comment by mramato** [comment]
Actually, I'm not sure the settings change is the right choice.  I just realized it probably means that external pull requests never get built by travis (meaning no jshint or tests get run).  I'm sure we can find a simple solution; I just don't think my first attempt is it.

**Comment by mramato** [comment]
Okay, I have a good understanding of why this all behaves the way it does now.  Since my setting changed, pull requests from forks no longer get built (for example #3955), which is definitely not what we want.  I found it a little odd that travis doesn't expose the branch name during builds from forks; but it just clicked that there can be name conflict between the forked and primary repositories.

So the right solution is to re-enable building pull requests but detect as part of the build process whether or not the build is based on a PR (which they have an environment variable for) and not deploy in those cases.  I thought we were already going this, but apparently not.
