### ISSUE TITLE
Sandcastle Map Pins example broken

### ISSUE THREAD

**Issue by tfili** [AnalyticalGraphicsInc/cesium#3980]
`Chrome Version 51.0.2704.63 m (64-bit)`

![image](https://cloud.githubusercontent.com/assets/1652382/15681739/7ff8c396-2728-11e6-80de-f3876e4b61e0.png)

**Comment by hpinkos** [comment]
This worked when i ran Chrome 50, but not after I updated

**Comment by mramato** [comment]
Okay, this was tricky to track down and is a huge problem.  **All current versions of Cesium are now at least partially broken in Chrome.**

The problem is that in ES6, [Array.values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/values) is a function on Array instances that returns a new ES6 iterator for the values.  We have code that relies on ducktyping that checks for a property names `values` on the object passed into `viewer.zoomTo/flyTo`.  This property used to be `undefined`, but now returns a valid function object as of Chrome 51 (because they implemented the feature).  This specific case should be easy to address, but we really need to do a thorough review of the Cesium code base and see if there is anywhere else we are using ES6 reserved words in a way that could cause problems.  For example, all of the `values` properties on `GeometryAttribute` are probably fine and are at worst confusing to someone who thinks that may be ES6 (it's like having C code with a variable called `string`, only confusing if you work in C++).

JavaScript is terrible.

**Comment by mramato** [comment]
Okay, I narrowed the scope and it's not as bad as I first thought.  `flyTo/zoomTo` are only broken when the argument being passed in is an array, which is still bad but not as common a use case.

**Comment by pjcozzi** [comment]
@mramato no need to re-open this, right?

**Comment by mramato** [comment]
Just to follow up, turns out that Google actually pulled support for `Array.values` because it broke a bunch of other apps too.  I had a link but now I can't find it.  Either way, no need to re-open this.

**Comment by shunter** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=615873
