### ISSUE TITLE
PolygonGraphics (crossing equator?) rendering problems.

### ISSUE THREAD

**Issue by dwhipps** [AnalyticalGraphicsInc/cesium#3995]
I have created an entity using PolygonGraphics with points which cross the equator, and it seems to miss certain points. 

To highlight the issue I have added the positions as point entities, and named them with their index. You can see that the polygon line goes from point 4 to point 10, skipping 5-9.

See here:
http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=ace120c26cee85243bcf9b48dddff52f

**Comment by hpinkos** [comment]
Thanks for the example @dwhipps!  This looks like a polygon triangulation error.  It's most likely related to this problem: https://github.com/AnalyticalGraphicsInc/cesium/issues/2788
We're currently investigating using a new triangulation library that should be able to correctly render some of these more oddly shaped polygons.  We'll make sure it fixes this one as well.
In the meantime, if you break up your polygon into two pieces so it doesn't wrap so much of the globe, it should render correctly.

**Comment by pjcozzi** [comment]
Thanks for the code example, @dwhipps!

The latest triangulation library does not fix this.  I'm pretty sure it is due to the polygon being projected to a tangent plan that distorts a polygon of this size.

I've consolidated this issue with #4871.

In the meantime, a workaround is to break this up into two polygons.
