### ISSUE TITLE
Globe missing

### ISSUE THREAD

**Issue by darrenSchlager** [AnalyticalGraphicsInc/cesium#4012]
I had Cesium working on my system previously, but today, the globe is missing. I have made no changes to my project since it last worked. I downloaded cesium again and the globe is missing even when I view HelloWorld and Sandcastle. The UI elements and entities show up, just not the globe.

**Comment by mramato** [comment]
Hi Darren, the globe is missing because the Bing key that is provided for demo purposes by Microsoft has been revoked. Generating your own Bing key in order to use Bing imagery is required, and has always been.  You must provide your own.  See the documentation:  http://cesiumjs.org/Cesium/Build/Documentation/BingMapsApi.html  The default key is only suitable for development, and as you see from the current situation, may change over time due to factors outside our control.
