### ISSUE TITLE
KML timespan tag issue

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4041]
Reported on the forum: https://groups.google.com/d/msg/cesium-dev/UrMK4Fku_Gk/Q-d6UmuRBAAJ
All of the images appear at once instead of following the timespan they are associated with

See the post for a link to the kmz file

**Comment by dwhipps** [comment]
If you have any clues as to where this might be going wrong in the code, I'm happy to spend an hour or two to look into it. Guess it's all in KmlDataDource.js. Any other details to go on?

**Comment by hpinkos** [comment]
Thanks @dwhipps!  We always appreciate contributions
 
@mramato @tfili do you have any suggestions for where to start?

**Comment by donnaaboise** [comment]
I was the original poster of this bug report, and we are wondering am happy to see interest in fixing this problem.   Is there anything more we can supply on this end?

**Comment by donnaaboise** [comment]
In looking at the post linked above, I wonder if our problem is also related to the GroundOverlay id?  I don't give any of our GroundOverlays ids, but could easily do so.  Here is the code from the attached file (Chile_2010.kmz renamed as Chile_2010.zip so it would attach)

     <GroundOverlay>
      <name>frame0000fig1.png</name> 
      <Icon>
        <href>frame0000fig1.png</href>
      </Icon>
      <LatLonBox>
        <north>0.0</north>
        <south>-60</south>
        <east>-60.0</east>
        <west>-120.0</west>
      </LatLonBox>
    
[Chile_2010.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/442990/Chile_2010.zip)

</GroundOverlay>

**Comment by hpinkos** [comment]
Thanks for attaching the file @donnaaboise!  Sorry we haven't had a chance to look into it yet.
We're planning to focus some attention on bug fixes for a few days in October, and I think this issue would be a good candidate for that.

If anyone else has some time to look into the problem before then, we would love the help!

**Comment by donnaaboise** [comment]
I've attached a simplified set of KML files that will make it easier to debug the timespan issue I am having.   

To recap, the issue is that while Cesium is recognizing the timespan elements (the time slider at the bottom of the Cesium viewer moves and the dates are correct) the GroundOverlays all show up at once, not in their designated time span interval.     

Here is the code I am using : 

    import cesiumpy
    ds = cesiumpy.KmlDataSource('timespan_test/doc.kml')
    v = cesiumpy.Viewer()
    v.dataSources.add(ds)
    v

As suggested in this post #4212 , maybe I need Ids (I am not using any).     I tried adding ids and target ids to the GroundOverlays, but didn't mange to make anything work.   

If @dwhipps would like to look at this, that would be fantastic!  It could be a very simple problem on the KML side, and not with Cesium.   The animation works fine in Google Earth.

I've uploaded a screen shot and the KML files.    There are five PNG files, linked via Network links, and a three levels of doc.kml files.    I validated all the doc.kml files against the official KML schema (ogckml22.xsd) and all validate without error.

![screen shot 2016-08-30 at 8 41 44 am](https://cloud.githubusercontent.com/assets/1406529/18096166/2edac11e-6e8e-11e6-98f9-5fdfaa83a9d5.png)

[timespan_test.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/445326/timespan_test.zip)

**Comment by donnaaboise** [comment]
Has anyone had the chance to look at this problem?  Thanks again for any help!  We are eager to use Cesium, but do need the ability to load time span data.

**Comment by hpinkos** [comment]
Thanks for checking in @donnaaboise!  I've marked this for us to look at during our upcoming Bug Bash, which is October 19-21.  We plan on looking into it then

**Comment by dwhipps** [comment]
All, while I'd love to help out, I think my issue with this has been resolved (I had multiple nodes with the same ID.) Cesium was doing the right thing, per the KML spec. Sorry!

**Comment by donnaaboise** [comment]
Thanks @dwhipps.  Can you tell me how to fix the IDs?  I am not sure where to put them.

**Comment by dwhipps** [comment]
Donna,

The bug, in my case, wasn't that is was missing IDs, but that there were duplicate IDs. I simply renamed the IDs in the KML files themselves, and the problems resolved. Not however that my problem wasn't necessarily the same as yours. Certain KML nodes were not being created in my case, because of the duplicate IDs.

Good luck,

Dave

**Comment by hpinkos** [comment]
Hi @donnaaboise,

The KML timespan issue was just fixed and will be included in Cesium 1.27.  However, when we were working on this we found a few more bugs that keep your Chile_2010 KMZ file from working properly (#4431 and #4477)

We're going to try to fix those before the next release as well.  Thanks!

**Comment by donnaaboise** [comment]
Great news!  Thanks,  @hpinkos !

When is the next release expected?

**Comment by hpinkos** [comment]
@donnaaboise we the first weekday of every month, so 1.27 will be available November 1st

**Comment by donnaaboise** [comment]
Just saw that the Cesium 1.27 is available for download.  Does this include the Python API as well?  The version available at https://pypi.python.org/pypi/cesium was last uploaded on 10/7/2016.  Will this be updated as well?  

I am eager to test the latest fixes!

**Comment by hpinkos** [comment]
Hi @donnaaboise,  we don't publish the Python API so I can't tell you when that will be updated

**Comment by GatorScott** [comment]
I'll point out that is unrelated to CesiumJS (WebGL Virtual Globe and Map Engine) versus Cesium (Machine learning platform for time-series).
