### ISSUE TITLE
Polyline near the ground disappear

### ISSUE THREAD

**Issue by gberaudo** [AnalyticalGraphicsInc/cesium#4081]
When zooming on the red line (bottom) of[ the Sandcastle polylne example](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=CZML%20Polyline.html&label=), the line will disappear at some point (quite close to the ground) and if one continues zooming, it will reappear.

This occurs on all tested browsers: chromium and firefox on linux and chromium and safari on Mac.

**Comment by tianhai82** [comment]
Also, in 2D mode, with mapMode2D = ROTATE, the first and last segments of polylines do not show up at some zoom levels.
http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=9e931bf2e63a06e354ba4e1042e96a44.

**Comment by bagnell** [comment]
It disappears because the line doesn't follow the ellipsoid exactly. The default granularity when subdividing the line to follow the ellipsoid is one degree. If you add `"granularity" : Cesium.Math.toRadians(0.5)` to the polyline, it will subdivide it more and you can zoom closer before it disappears. Setting the granularity to 0.1 degrees will subdivide further and it will never disappear.

**Comment by gberaudo** [comment]
@bagnell, thank you for the explanations.
