### ISSUE TITLE
GLSL Documentation?

### ISSUE THREAD

**Issue by thinkpadder1** [AnalyticalGraphicsInc/cesium#4116]
I found [this old documentation](http://cesiumjs.org/releases/b28/Build/Documentation/czm_antialias.html?classFilter=&show=glsl) for Cesium and it has GLSL docs as well. Where can I find this for the latest Cesium? 

I see the docs at the top of the .glsl files currently, but being able to view it in the docs would be very nice. Thank you.

**Comment by pjcozzi** [comment]
The GLSL doc is not built anymore since the `Renderer` went private for Cesium 1.0 (however, it should be since users want to use Cesium's GLSL functions for custom materials).

In the meantime, see the source and doc comments in https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Source/Shaders/Builtin

**Comment by thinkpadder1** [comment]
Yea, I've been just reading the source code. Thanks though! :smiley:
