### ISSUE TITLE
WMTS problem

### ISSUE THREAD

**Issue by wussup** [AnalyticalGraphicsInc/cesium#4296]
Hello, I have a problem with adding Poland Topographic Map WMTS (http://mapy.geoportal.gov.pl/wss/service/WMTS/guest/wmts/TOPO):

`new Cesium.WebMapTileServiceImageryProvider({
url : 'http://mapy.geoportal.gov.pl/wss/service/WMTS/guest/wmts/TOPO',
layer : 'MAPA TOPOGRAFICZNA',
style : 'default',
tilingScheme : new Cesium.GeographicTilingScheme(),
tileMatrixSetID : 'EPSG:4326',
proxy : new Cesium.DefaultProxy('/proxy/')
})`

![cesium_error](https://cloud.githubusercontent.com/assets/4366584/18349028/2c71274a-75cf-11e6-86da-47c00a03905c.png)

PS: Poland is in Europe, not around the Earth :)

Could you please help me?

**Comment by mramato** [comment]
Hi @wussup, first I'm sorry you never received a reply for this.  We try to handle all support on our forum: https://groups.google.com/forum/#!forum/cesium-dev so you will always have better luck (and much faster responses) 

If you still haven't solved this, it looks like you need to pass the `rectangle` option to the WMTS provider in order to limit the data to the proper location, but it's hard to say without the capabilities document that the server produces.

I'm going to close this, but please start a forum topic if you're still having issues. Thanks.

**Comment by MikosMariusz** [comment]
This problem is solved? Did the author find a solution?

**Comment by OmarShehata** [comment]
@MikosMariusz passing in a `rectangle` option to the imagery provider should produce the correct result here. If you're having trouble with that please post in the Cesium community forum: https://community.cesium.com/.
