### ISSUE TITLE
Cesium 1.18 introduced scaling artefacts for Win7 users who use a non-100% system font

### ISSUE THREAD

**Issue by alfski** [AnalyticalGraphicsInc/cesium#4318]
Hi, realise this is an edge case. Just noticed if Windows 7 user changes the font size on their system  Cesium renders with scaling artefacts.  This is likely a browser devicePixel thing, problem occurs with Firefox and Chrome.

eg. Windows 7 with system font size set at "Medium 125%" using Control Panel > Display > Custom DPI setting > 125%.  Looks like this, note the scaling artefacts in the atmosphere...

![cesium-100percent](https://cloud.githubusercontent.com/assets/979009/18500317/dd08075e-7a89-11e6-8f66-d1f3e2417002.png)

If I set the browser scaling to 80% OR use a Cesium build 1.17 or older no scaling artefacts. Note nice smooth horizon...

![cesium-80percent](https://cloud.githubusercontent.com/assets/979009/18500329/f61459be-7a89-11e6-8d08-50c8be624139.png)

Cheers, Andrew

**Comment by mramato** [comment]
This is actually by (browser vendor) design and is just one aspect of "how browsers work".  Essentially the browser is setting the `window.devicePixelRatio` property which is telling Cesium that all rendering needs to take place at a different resolution. This is important for devices with insane resolutions but lacking the power to render 3D content at those resolutions, this includes a lot of consumer 4K systems and most mobile devices on the market.  So what you are noticing is a lower-resolution rendering of the globe being crisply resized to fill the entire window.  `window.devicePixelRatio` is also used when browser zooming of any kind is employed, so if you are on a system where `window.devicePixelRatio` is `1`, but enable browser/font zooming, you will end up with the same effect.

In 1.17 and earlier, Cesium tried actively worked around this behavior and always rendered at "full resolution", which actually caused a lot of problems on the types of devices I described above.  This is actually mentioned in [CHANGED.MD](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) for 1.18.

With all of that in mind, you should be able to go back to the old behavior with the below code snippet.

```javascript
viewer.scene.preRender.addEventListener(function() {
    viewer.resolutionScale = defaultValue(window.devicePixelRatio, 1.0);
}
```

The above forces Cesium to always render at the actual on-screen resolution and ignore the browser's recommend resolution.  However, keep in mind that ignoring the browser's recommendation like this will decrease performance on mobile devices or 4K monitors that lack a good GPU. (You could always try and detect mobile devices and only disable it then, but I tend to avoid that type of detection via javascript).

While we appreciate all feedback and concerns, in the future please raise issues like this [on our community forum](https://groups.google.com/forum/#!forum/cesium-dev) first, since our responses will be seen by more people (so everyone in our community learns the answer) and we also try to use GitHub exclusively for confirmed bugs and planned features.

Hope that helps, thanks.
