### ISSUE TITLE
3D tiles - tiles invisible and cut

### ISSUE THREAD

**Issue by daniel-hilton** [AnalyticalGraphicsInc/cesium#4333]
I've tried to convert the gltf model of the old city Girona, Spain [from here](betaserver.icgc.cat/cesium/Girona3D.html) and recreated it as b3dm (by adding rtc_center, data as binary, batchId and b3dm header). The tileset that contains all these files has a root tile and 42 children that uses "replace" refine

There are 2 problems in the tile loading and view (both has video below)
1. Sometimes the 3D model is getting cut in certain line - sometimes only the near side is seen and sometimes the opposite - in the video you can see both in the end
2. Sometimes tiles disappears - the Bounding Box is there but the model it should contain does not.

(1)

![start](https://cloud.githubusercontent.com/assets/22270725/18614925/58de45a4-7da1-11e6-88e3-85a58eebd380.gif)

(2) 

![end](https://cloud.githubusercontent.com/assets/22270725/18614998/33e367c8-7da3-11e6-8589-769df7d3a182.gif)

**Comment by lilleyse** [comment]
Thanks for the letting us know about these issues. Would you be able to send over the tileset so that we can debug them?

**Comment by daniel-hilton** [comment]
i'm not sure I can publish it because it's ICGC model. but I cat share it with you in private via email dropbox etc.

**Comment by lilleyse** [comment]
Ok, you can send a dropbox link to slilley@agi.com

**Comment by daniel-hilton** [comment]
shared! If anyone else want this model write your mail here and ill send it ASAP

**Comment by daniel-hilton** [comment]
BTW, this model is generated by acute and was converted from dae to glTF using the COLLADA2GLTF and from glTF to b3dm by [this](https://github.com/daniel-hilton/gltf-b3dm-convertor)

**Comment by lilleyse** [comment]
Quick update: I noticed that the bounding spheres generated for the underlying model are not aligned properly, which causes the view frustum near plane to be incorrect (causing problem 1) and is probably related to problem 2.

Would you also be able to also send over one of the original dae models through Dropbox?

![bounding](https://cloud.githubusercontent.com/assets/915398/18645285/8ac837e4-7e7a-11e6-8f7b-5a83199ad16d.JPG)

**Comment by daniel-hilton** [comment]
I don't have the dae, only the glTF files, I'll send you them shortly. 

As part of the b3dm convert process I have gone threw every vertex (in the POSITION accessor) and multiplied it by the transition matrix. because before the multiplication the model was  directed by the Cartesian plane and not the cartographic. This might have been the problem.

1. doesn't the bounding sphere calculated from the POSITION array? so if I've change the position it should change to. what am I missing?
2. I've tried to use the transition matrix that exist in the tileset scheme, but it didn't effect the model, is there an example of using it?
3. how did you managed to show the bounding sphere?

this is the code:
```javascript
    for (let i = 0; i < count; i++) {
        tempCartesian3.x = buffer.readFloatLE(12 * i + offset);
        tempCartesian3.y = buffer.readFloatLE(12 * i + offset + 4);
        tempCartesian3.z = buffer.readFloatLE(12 * i + offset + 8);
		
        addPointToExtent(tempCartesian3,currentExtent);

        Cesium.Matrix4.multiplyByPoint(transformMatrix, tempCartesian3, tempCartesian3);
        Cesium.Cartesian3.subtract(tempCartesian3, centerRtc, tempCartesian3);

        buffer.writeFloatLE(tempCartesian3.x, 12 * i + offset);
        buffer.writeFloatLE(tempCartesian3.y, 12 * i + offset + 4);
        buffer.writeFloatLE(tempCartesian3.z, 12 * i + offset + 8);
    }
```

**Comment by daniel-hilton** [comment]
I've added the the gltf files to the shared dropbox

**Comment by lilleyse** [comment]
Thanks I'll check them out soon.

The bounding spheres are calculated from the min/max of the position accessor, so if those aren't updated as well that could be a problem. Since you are transforming the positions, you may also need to transform the min and max.

So you tried using a `transform` on the root tile already? That seems like a good alternative to this situation. You can check out an example here: `https://github.com/AnalyticalGraphicsInc/3d-tiles-samples/tree/master/tilesets/TilesetWithDiscreteLOD`. If you go this approach you may not need to modify the glTF positions at all.

To show the bounding spheres, in `Batched3DModel3DTileContent.js` I pass in `debugShowBoundingVolume` as true when creating `new Model`. This is just for debugging purposes and isn't an available option through the API.

As a side note, I noticed that each of your tiles contains two meshes associated with it. One with POSITION, TEXCOORD_0, and BATCHID, and another with just POSITION and BATCHID. So in Cesium your tileset is actually rendering twice the number of commands than it needs.

Anyways I'll take a closer look at the glTFs when I have a chance and get back to you.

**Comment by daniel-hilton** [comment]
Seems that the min-max values was the issue. thanks for your help. 

Continue to do the great things you do!

**Comment by lilleyse** [comment]
Nice! I'm glad it works now.
