### ISSUE TITLE
Add incrementallyLoadTextures to Cesium3DTileset and ModelInstanceCollection

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#4345]
For #3241 

Add an `incrementallyLoadTextures` flag to `Cesium3DTileset` and `ModelInstanceCollection` to override the default setting for `Model`, which is to render a white model before the texture is loaded. This sometimes has a jarring effect for tilesets that use replacement refinement.

@JudyWeng This will be a good one to work on tomorrow.

**Comment by pjcozzi** [comment]
Add this to `ModelInstanceCollection`.

However, I would not add this to `Cesium3DTileset` since it has such limited use cases, basically just additive refinement, which is rarely appropriate for textured tilesets.  Instead, just set this to `false` when creating `Model` and `ModelInstanceCollection` objects.

**Comment by lilleyse** [comment]
Yeah that sounds good to me.
