### ISSUE TITLE
ImageryLayer crash when using imagery provider rectangle option

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4377]
Reported on the forum: https://groups.google.com/d/msg/cesium-dev/wMdmusP1Fu4/Jl_Uk7uABQAJ

It looks like `ImageryLayers` is trying to get an imagery tile that's outside the bounds of the imagery provider rectangle

``` javascript
var provider = new Cesium.WebMapServiceImageryProvider({ 
    url : ' http://ows.terrestris.de/osm/service?', 
    layers : 'OSM-WMS', 
    rectangle : Cesium.Rectangle.fromDegrees(149.0625, -36.5625, 154.6875, -30.93758), 
    minimumLevel : 6, 
}); 

var widget = new Cesium.CesiumWidget('cesiumContainer', {
    imageryProvider: provider
}); 
widget.imageryLayers.addImageryProvider(provider); 
```

**Comment by erikmaarten** [comment]
Looked through the `ImageryLayer.js` code, and (like @hpinkos said above) the problem appears when no intersection is found between imagery provider rectangle and imagery rectangle.  `Rectangle.simpleIntersection` returns undefined if no intersection was found. Since there is no check for this case, I'm _guessing_ it's not supposed to be a valid scenario.
@mramato Is this something you can comment on or have a look at?

**Comment by mramato** [comment]
@shunter or @kring would know for sure, but I'm guessing that we should check for undefined and simply `continue` the loop in that case (which should cover both usages in `ImageryLayer.js`).

**Comment by erikmaarten** [comment]
@mramato I did try that and ended up with a globe with a small rectangle of imagery looking OK, the rest of the globe had the pixels from the edges of that rectangle smeared out in each direction. Is that to be expected when providing a rectangle option to the `Cesium.WebMapServiceImageryProvider` constructor?

**Comment by mramato** [comment]
> Is that to be expected when providing a rectangle option to the Cesium.WebMapServiceImageryProvider constructor?

If it is the base layer, than yes.  We always stretch the outer pixels of the base layer to take up the whole screen.  If you don't make it the base layer, then it should only take up the specified rectangle.

**Comment by erikmaarten** [comment]
Thanks @mramato. I'll submit a PR for this. Just to make sure, when stretching the base layer, is it supposed to look like this? The rectangle itself looks fine, but there seem to be gaps in the stretched base layer. It looks the pixels are stretched to the north pole, and to the west but only to (what looks like) the anti-meridian. The rectangle is around Sydney.
![globe](https://cloud.githubusercontent.com/assets/4586719/19849531/12602294-9f54-11e6-8e58-228af870cd76.png)

**Comment by mramato** [comment]
Normally I think it stretches in all directions, so that does look a little weird, but if there is a problem it's probably unrelated to the layer and instead to the stretching.  As long as it looks correct when it's not the base layer, I think we're okay (but I'll let someone who knows more about this area of the code review the PR).  Thanks.

**Comment by mramato** [comment]
I also just realized the sample code in the original post is a little odd, it adds the provider twice.  Here's one that adds it as a non-base layer:

```javascript
var provider = new Cesium.WebMapServiceImageryProvider({ 
    url : ' http://ows.terrestris.de/osm/service?', 
    layers : 'OSM-WMS', 
    rectangle : Cesium.Rectangle.fromDegrees(149.0625, -36.5625, 154.6875, -30.93758), 
    minimumLevel : 6, 
}); 

var widget = new Cesium.CesiumWidget('cesiumContainer'); 
var layer = widget.imageryLayers.addImageryProvider(provider); 
```
