### ISSUE TITLE
Oriented Bounding Box frustum check is too loose

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#4387]
The current OBB vs plane algorithm is an approximation that works best with more evenly-sized dimensions. As a result we sometimes see results like below, which cause tiles to be selected that aren't actually visible.

![image](https://cloud.githubusercontent.com/assets/915398/18972341/c24cbd04-8666-11e6-9523-defc858b1342.png)

**Comment by pjcozzi** [comment]
To improve this:
* Double check that [OrientedBoundingBox.intersectPlane](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/OrientedBoundingBox.js#L377) is correct.  It probably is, and the screenshot above is probably because the view frustum is huge and this is the classic problem where the bounding volume is outside at the frustum corners but the algorithm still reports "intersecting."
* Try [Correct Frustum Culling](http://www.iquilezles.org/www/articles/frustumcorrect/frustumcorrect.htm).  After the 6 plane test reports intersecting, test all the frustums of the corners against each of the planes of the bounding volumes.
   * Note that the larger the bounding volume (which is common in Cesium terrain and 3D Tiles), the more likely the plane test is to return a false intersection so I suspect these extra checks will more than pay for themselves in fewer draw calls.
   * Given the increase cost, #4787 could be a big win.
* Implement for both OBBs and spheres, and profile for both terrain and 3D Tiles.

**Comment by pjcozzi** [comment]
Above, note that when adding IQ's tests, all 6 planes in the orignial algorithm do not need to be checked.  Just two corners are "created" and tested.

**Comment by pjcozzi** [comment]
Reminder to let @erich666 know our results.

**Comment by pjcozzi** [comment]
@austinEng are you able to reproduce the exact case shown in the screenshot above?  I believe the camera is just west of the initial tileset in the Sandcastle example and looking straight down.  Or was this another bug?

**Comment by austinEng** [comment]
I was not. @lilleyse said that he thinks this specific problem was already solved in another bugfix

**Comment by lilleyse** [comment]
The screenshot was taken before the box debug outlines were fixed https://github.com/AnalyticalGraphicsInc/cesium/pull/4845. Therefore our tilesets just don't have tight fitting bounding boxes, which the 3d-tiles-tools generator will address.

**Comment by pjcozzi** [comment]
OK, thanks for investigating.
