### ISSUE TITLE
Rendering crashes with a 0 width LineRing clamped to ground: "Invalid array length"

### ISSUE THREAD

**Issue by vrittis** [AnalyticalGraphicsInc/cesium#4444]
I'm working with entities that must clamp to the terrain, and I found out that if I'm trying to render a 0 width linering clamped to the ground, I get a "Invalid array length" error

Attached is the kml file I was using when replicating the problem

[Composantes.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/538129/Composantes.zip)

**Comment by mramato** [comment]
Thnks @vrittis, this sounds like an obvious bug in `CorridorGeometry` (which is what's used by KML when line clamping is enabled.  `CorridorGeometry` should gracefully handle invalid geometry (0 width line) and simply not draw.

**Comment by erikmaarten** [comment]
@vrittis What are the steps to reproduce the problem? Which version and build are you using? I don't seem to be able to reproduce the crash using your KML file.

**Comment by vrittis** [comment]
@erikmaarten here is what I did on Cesium 1.26 package downloaded on cesiumjs.org. I set up the sandcastle app, and copied the attached file in the Apps\SampleData\kml directory.

Then I modified the kml exemple to read
```

var viewer = new Cesium.Viewer('cesiumContainer');
var options = {
    camera : viewer.scene.camera,
    canvas : viewer.scene.canvas
};

viewer.dataSources.add(Cesium.KmlDataSource.load('../../SampleData/kml/composantes.kml', options));
 
```

I'm tryign to recreate the exact steps of the situation where I discovered the bug which was a little different; I'm hiding all entities and only displaying them when the user makes changes in a UI. The message is différent, but the reason for the error is the same.

**Comment by hpinkos** [comment]
@vrittis I was able to reproduce the crash in master with the KML file you attached.
@erikmaarten let me know if you are still unable to

**Comment by erikmaarten** [comment]
@hpinkos I think I'm now able to reproduce it, though the error I see is `width must be greater than or equal to one`.
```
DeveloperError: width must be greater than or equal to one.
Error
    at new DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:44:19)
    at new PolylineGeometry (http://localhost:8080/Source/Core/PolylineGeometry.js:128:19)
```
Simply removing the throwing `DeveloperError` will make the KML file load fine, but is that the behavior we want? We could probably avoid creating a Polyline at all if the width is 0, but performance-wise it shouldn't make a big difference unless we're expecting 0-width lines to be commonly used.
I checked `CorridorGeometry` (specifically `CorridorGeometry.createGeometry`) as @mramato suggested, and I don't get any `width < 1.0` scenario there when loading the KML, so I'm not sure where we could catch this kind of geometry before being created.

**Comment by mramato** [comment]
Thanks for the additional debugging @erikmaarten.  `master` has changed since this issue was written, so you are seeing a different manifestation of the same root cause.  add `clampToGround:true` to the KML options when loading and you should see the corridor version.

Input validation like this is a tough one.  In general, the rule in Cesium is "fail early", that is don't hide problems and throw at the first sign of bad data.  This strategy works great when all data is being programmatically generated, but breaks down when you are throwing random external data at it (like KML files) because often times the developer isn't the one creating the external data.  In these cases we normally loosen our restrictions and simply treat it as empty geometry (for example if you specify a polygon with less than 3 positions).

We could change `KmlDataSource` to check for a width of 0 and ignore it. But that doesn't address the root problem and only fixes KML.  It also makes the KML less Google Earth compatible.

I would like to see us make both `CorridorGeometry` and `PolylineGeoemtry` handle a width of 0 or less and just treat it as empty geometry. (they should still throw if width is not typeof Number in the constructor).  Basically, just make each obejcts `createGeoemtry` function check for `width <= 0` and return undefined in those cases.

Thanks.

**Comment by erikmaarten** [comment]
Thanks for the detailed explanation @mramato.  I agree that it's more sensible to have the geometries treat 0 or less widths as empty geometries. Looking at the code, it seems to be done already for `CorridorGeometry` though (see https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/CorridorGeometry.js#L944). I specified clamping like below, but no error. Is there anything else I'm missing? @hpinkos If you have time to check it again, could you post the exception stack trace? (I also checked out `1.26` and tried the same, and no error.)
```
var viewer = new Cesium.Viewer('cesiumContainer');
var options = {
    camera : viewer.scene.camera,
    canvas : viewer.scene.canvas,
    clampToGround : true
};

viewer.dataSources.add(Cesium.KmlDataSource.load('../../SampleData/kml/composantes.kml', options));
```

I've fixed the issue for `PolylineGeometry` in PR referenced above.

One question - is a width of, e.g., `0.5` a valid width for a geometry? The PolylineGeometry constructor was previously throwing an exception if `width < 1.0`, so should we treat anything less than `1.0` or anything less than/equal to `0.0` as empty geometry?

**Comment by hpinkos** [comment]
You know what?  I actually think I mostly fixed this during the bug bash the other week by adding this line: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/CorridorGeometry.js#L683

However, instead of `length === 0` it should be `length < 2`

For polylines the widths are in pixels, so I would think any value less than one pixel would be empty.

**Comment by erikmaarten** [comment]
@hpinkos Oh, then we're almost done :smile:
I fixed the `length === 0` line, and set the `length` variable to actually be the length, and not `length - 1` as it was previously (updated rest of the function accordingly). b1f2a63

Also corrected the pixel width check. 690061b

(PR here: #4562)
