### ISSUE TITLE
Investigate other options for the forum

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4446]
From the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/OLO57b6JpqY

> I get emails from this group when I post something, but the emails have no link back to the group. If I come here and reply to a post it stays here.
> A reply here looks just like an email reply, but if I reply to the email, it doesn't show up here.
> If I want to come back here to post something I have to look up Google Groups, look at 'my groups', go to cesium-dev and then look for the relevant post.
> These seems awfully convoluted. Am I missing something?

Have google groups fallen out of favor?  This is the first feedback like this I've seen, but if the community is dissatisfied with the google group forum maybe we should investigate migrating to something more user friendly.

**Comment by pjcozzi** [comment]
It could be our default settings or the user's settings.  Google groups are very widely used; I also use them for several conferences, classes, tech groups, etc.  Given the archive, I would be hesitant to migrate until there are issues affecting seriously affecting many users.

Perhaps this is a discussion better suited for the forum, not to be too meta about it.

**Comment by mramato** [comment]
I don't think the problem is google groups itself.  The problem is that embedding google groups on the website like we do has quirks that google seems to have no interest in fixing.  If we just sent everyone directly to the groups page (https://groups.google.com/forum/#!forum/cesium-dev) and didn't try and embed it on cesiumjs.org, I think that would minimize a lot of the problems.

**Comment by pjcozzi** [comment]
Double check the analytics to see how many users go from the forum page to another page, but if it is small-ish, +1 from me for the change.

**Comment by thinkpadder1** [comment]
Just wanted to drop some opinions on [Discourse](discourse.org).

- It's heavy both on the front end (very JavaScript intensive) and the back end (Ruby on Rails).
- Loads posts on the fly as you scroll down... quite annoying.
- Hijacks the CTRL + F browser function if the thread has more than 20 (default) posts. You can override it by hitting CTRL + F again... but since the data has not been served to the browser yet, you won't be to actually search an entire thread without using their interface (which has search restrictions like length, common words, etc).

NodeBB has similar problems on top of it having its database being Redis/MongoDB... but it's blazing fast. Long topics in Discourse brings itself to its knees while NodeBB blazes by. The frontend is lighter as well.

There's also Vanilla (PHP + MySQL), but I don't have much experience with it.

What I'm trying to say is... avoid Discourse.

**Comment by jeffwhitty** [comment]
+1 for changing, I can't use the google groups functionality at all from my work environment. The enterprise security settings block it from the cesiumjs.org website and then I have to jump through hoops to sign in to google on the corporate network. Personally my experience with google groups is terrible.

Also from my experience, make sure you enable the anti-spam features of whatever you change to ;)  I set up a vBulletin once, turned my back for a day or two and suddenly it was receiving spam posts at a great enough rate to seriously impact the rest of the server...

**Comment by pjcozzi** [comment]
Thanks for the input here, but given the size of the community, we will stick with google groups in the short- to mid-term.
