### ISSUE TITLE
Change Transforms.headingPitchRollToFixedFrame to use new HeadingPitchRoll

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4468]
https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Transforms.js#L475-L481

Deprecation policy is here: https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/CodingGuide#deprecation-and-breaking-changes

@twpayne low-hanging fruit for the bug bash if you are interested.

CC #4047

**Comment by twpayne** [comment]
I'm looking at this now.

**Comment by twpayne** [comment]
AFAICT we already have [`aircraftHeadingPitchRollToFixedFrame`](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Transforms.js#L504) which implements `headingPitchRollToFixedFrame` but taking a `HeadingPitchRoll` object instead of separate heading, pitch, and roll values.

Which of the following options would you prefer?

* Mark `headingPitchRollToFixedFrame` as `@deprecated` and replace all calls to it in the Cesium codebase with calls to `aircraftHeadingPitchRollToFixedFrame` as per the deprecation policy.
* Modify `headingPitchRollToFixedFrame` to take either a `HeadingPitchRoll` object or separate values (will require some `arguments` munging). This maintains a cleaner API but there will be a performance hit.
* Remove the original `headingPitchRollToFixedFrame`, rename `aircraftHeadingPitchRollToFixedFrame` to `headingPitchRollToFixedFrame`, and use `HeadingPitchRoll` objects throughout the codebae. This is arguably the cleanest but violates the deprecation policy.
* Something else?

**Comment by pjcozzi** [comment]
> Mark headingPitchRollToFixedFrame as @deprecated and replace all calls to it in the Cesium codebase with calls to aircraftHeadingPitchRollToFixedFrame as per the deprecation policy.

The semantics of "aircraft" are a bit awkward to use internally; I would rather deprecate both of these (if the aircraft version has already shipped) and replace with a new more generically named function.

**Comment by twpayne** [comment]
As naming things is one of the [two hard things in computer science](http://martinfowler.com/bliki/TwoHardThings.htm), any suggestions for the new more generically named function?

* `headingPitchRollToFixedFrame` (the existing function name) seems to me to be the most apt, but this will require the `arguments` munging above to maintain backward compatibility.
* `hprToFixedFrame` includes a rarely-used abbreviation and so violates the [naming guidelines in the coding guide](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Documentation/Contributors/CodingGuide/README.md#naming).
* 🤔 ?

Note that the "aircraft" functions were made public in 4aa7eeea, which was only merged into `master` yesterday (#4047), and so they have not yet shipped in a release.

**Comment by pjcozzi** [comment]
> headingPitchRollToFixedFrame (the existing function name) seems to me to be the most apt, but this will require the arguments munging above to maintain backward compatibility

We haven't done this before, but perhaps we could just "deprecate the arguments" instead of the function.  Since this is not a widely used function, I think we should give this a shot and then deprecate over 3 releases since this approach is new to us.
