### ISSUE TITLE
Low fps using cesium

### ISSUE THREAD

**Issue by EladIsraeli** [AnalyticalGraphicsInc/cesium#4526]
When using the Hello World example , i feel like the fps are about 20 , i understand that cesium uses WebGL so i wonder why is it ? I want the map to be simple as possible to works fast and smooth as it cans .
The reason for this is because i want to add dynamiclly like 1million points to the map , so i need the map to be free of useless features that may be influence the smoothness of the app.

**Comment by hpinkos** [comment]
Please ask questions like this on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub issues exclusively for bug tracking and new feature planning

The low fps may be due to your computer specs.  Start with making sure your video card drivers are up to date.
Just to confirm the slowness, you can see FPS onscreen with `viewer.scene.debugShowFramesPerSecond = true;`.
