### ISSUE TITLE
Consistent mouse controls

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#453]
From our Santa experience:

Currently, in Cesium:
* No one can figure out how to tilt with the middle mouse button
* Both middle mouse and right mouse can zoom
* Rotate is inconsistent:  in free-roam, rotate-ish is left mouse button when zoomed out and right mouse button when zoomed in; when following, it is right

In Santa, we tried to address this by swapping middle and right mouse button, but the results are not that great.

What other options can we experiment with?  Perhaps we do nothing since we'll have the navigation widget and apps are free to override the controls.

**Comment by mramato** [comment]
I think it would be pretty hard to change default mouse controls at this point given that Cesium has been around a while so I would recommend closing this.  We will continue to improve the ability to customize controls in Cesium, but I don't see a reason to change the defaults.

If anyone feels otherwise, we can keep this open, but I would recommend tagging it for Cesium 2.0.

**Comment by pjcozzi** [comment]
Agreed
