### ISSUE TITLE
package.json : requirejs 2.3.2

### ISSUE THREAD

**Issue by pasu** [AnalyticalGraphicsInc/cesium#4618]
Hi
Since version 1.26, Cesium modifies the requirejs version from 2.2.0 to 2.3.2
Unfortuanately, it seems there is a bug in this new version when optimizes code, for example:
The code in the  CzmlDataSource.js ::function unwrapInterval(type, czmlInterval, sourceUri) :
` return defaultValue(czmlInterval['boolean'], czmlInterval);`
I compared the results between 2.2.0 and 2.3.2:
2.2.0 :
`return u(n["boolean"], n);`
2.3.2:
`return u(n.boolean, n);`

boolean is a simple data type and it is a syntax issue strictly, when somebody want to compress and obfuscate the Cesium.js, it could be a potential issue and not easy to be recognized
so, I hope you can consider this situation.

**Comment by hpinkos** [comment]
Thanks for bringing this up @pasu 

@mramato what do you think we should do to fix this?

**Comment by mramato** [comment]
I'm fairly certain this isn't a bug.  `n.boolean` is a perfectly valid Javascript property access.  The only reason we actually have `n["boolean"]` in the code is because of a long ago issue with the dojo compiler that we used to use.

@pasu do you have a small test case that shows that this actually affects runtime code behavior?

**Comment by pasu** [comment]
yes, you are right, I test it. Runtime is no problem.
maybe the issue is about yuicompressor

First gulp minify and get the Cesium.js
Then, using yuicompressor and there are so many errors and I could not get the compressed file, 

So, in my situation, I could only use the 2.2.0 version because I have to obfuscate Cesium.js
Thanks:)

**Comment by mramato** [comment]
@pasu if you are ultimately using the yui compressor, you would probably be better off including the unminified version of Cesium in your project (build/CesiumUnminified), since it will get compressed at the end anyway.

I also encourage everyone to use our AMD modules directly, but obviously that's a bigger move.

**Comment by pasu** [comment]
@mramato , yes, you said it, thanks for your suggestion, my situation is a little complicated,  I will make a full consideration
