### ISSUE TITLE
Less greenkeeper noise

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4697]
Is it possible to improve the signal-to-noise ratio of this repo's pull requests by configuring greenkeeper to only do pull requests at some interval, perhaps biweekly?  Since the updates are rarely significant, it has created an incredible amount of noise in our pull request history.

**Comment by kring** [comment]
I don't know of a way to set an interval.  But one way to cut down on the nonsense is to loosen up your package versions.  Cesium requires exact package versions, which means that every single new version of anything you depend on generates a PR in Cesium.  If you used the carat or tilde, you'd get a fraction of the PRs.

The idea with Greenkeeper is that you trust semver (non-major versions won't break you), and Greenkeeper is your insurance policy to make sure that is true.  In the rare event that a minor version or patch breaks something, you hear about it quickly and fix it.

So there are a few places where the versions in package.json matter, with different concerns:
* _In GitHub, especially the master branch_: The carat is almost certainly what you want, so any version with the same major version will be used.  When something breaks due to unexpected incompatibility, Greenkeeper tells you almost immediately and you fix it, either by adjusting for the breaking change or by temporarily pinning to an older release.
* _In versions published to npm_: Cesium's current approach of requiring exact version numbers is actually quite antisocial here.  It means that any project that uses Cesium must use the exact same versions that Cesium uses.  If libraries commonly did this, npm would be a mess.  Your chances of having a version conflict when using more than one library from npm would be basically 100%.  At best, a version conflict means two copies of the library loaded by node or built into your browserify/webpack app.  At worst, it just flat out breaks.  When Greenkeeper detects breakage, you should publish a new patch version to npm that fixes it, again by adjusting for the breakage or by temporarily pinning to an older version of the library.
* _In release zip files_: This is the tricky one.  Since these are on end-user machines, you can't easily update them after the fact.  So if a new package is published to npm which breaks a Cesium release ZIP, it's pretty painful.  The right way to deal with this is to generate a [shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) file at build time and include it in the ZIP.  That way `npm install` will install those exact versions by default.  Since people using the ZIP generally aren't using NPM, this is perfect.  But an NPM user can easily delete the shrinkwrap file if they instead want any semver-compatible version.

**Comment by mramato** [comment]
I agree that Cesium using full version numbers for everything kind of goes against the tide of how npm is supposed to work, I've been thinking about going "full caret" for a while.  My only concern (as @kring already pointed out) is things breaking do to a version upgrade.  However, this would be a much rarer event then my concerns warrant and it would only affect Cesium developers, since all of our dependencies except for `requirejs` are devDependencies and I doubt requirejs will break anytime soon.

I'm not sure shrinkwrapping for the zip is worth it, if an old zip was broken, it would be trivial to fix it by simply going in and removing the caret from the dependencies, since that would cause it to use the exact version number and like I said, I think this would be an incredibly rare event.

Not to mention, if this whole thing went sideways for some reason (doubtful) we can just go back to doing things the old way or try something else.

So if everyone is in agreement, I can open a PR to use the caret for everything (except stuff we need version locked because of breaks).  We should also update our other modules to follow this rule as well (and any coding guides that may mention it).

**Comment by kring** [comment]
Yeah we probably get broken maybe once or twice a year by third party libraries not following semver, and our projects have a lot more dependencies than Cesium.  So hopefully it'll be rare.

Keep in mind that it's not quite true that you can just remove the carat from package.json if something breaks in a release zip.  That will make it install a version that is almost certainly older than whatever everyone was using before the broken package was released.

**Comment by mramato** [comment]
> Keep in mind that it's not quite true that you can just remove the carat from package.json if something breaks in a release zip. That will make it install a version that is almost certainly older than whatever everyone was using before the broken package was released.

Why?  By definition the code works with the explicit version in package.json, how would it not?

**Comment by mramato** [comment]
I mean, I agree it will be an older version, but it will definitely be a working version.

**Comment by kring** [comment]
Yeah, true, it's almost guaranteed to be a working version.  But it'll be a version that no one has tried in ages, so it's possible it no longer works (due to incompatibility with other packages released since, for example).  But yeah, that's getting a bit paranoid.

**Comment by pjcozzi** [comment]
> So if everyone is in agreement, I can open a PR to use the caret for everything (except stuff we need version locked because of breaks). We should also update our other modules to follow this rule as well (and any coding guides that may mention it).

Big +1 from me.
