### ISSUE TITLE
Geocoder lon/lat bug

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4713]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/pbt7SSTR6CY

> Type 39N 75W in geocoder - Cesium takes you to Philadelphia and replaces the text in geocoder with 39, -75
> But if you type 39, -75 you end up in Antarctic at 39E 75S

**Comment by hpinkos** [comment]
@erikmaarten could you look at this when you're making other improvements to the geocoder during the code sprint?

**Comment by mramato** [comment]
So we have special code that handles numbers-only entries that uses Cesium lon/lat/alt order to zoom instead of Bind.  I'm guessing 39N 75W ends up using Bing for the geocode while 39, -75 uses Cesium.  This is probably easy to change, but I'm not sure how we really want it to work.  I'm 90% sure we will end up leaving it as-is, since it's imperfect input anyway, but I'm open to ideas.

**Comment by mramato** [comment]
It's also possible that Bing didn't handle numbers when we added the Cesium-specific code path, we could probably go Bing-only if it now fits the bill.

**Comment by hpinkos** [comment]
yep, i'm sure that's exactly what's happening.  Bing is geocoding it and returning lat/lon and then if you hit enter again it goes into our custom code that does lon/lat

**Comment by erikmaarten** [comment]
I'll change the geocoder service for lat/long take this into account after https://github.com/AnalyticalGraphicsInc/cesium/pull/4723 has been merged.
