### ISSUE TITLE
No maps but webGL supports

### ISSUE THREAD

**Issue by Tonyhzw** [AnalyticalGraphicsInc/cesium#4804]
In my environment, I could not found any maps with:
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=CZML%20Model%20-%20Node%20Transformations.html&label=CZML

![default](https://cloud.githubusercontent.com/assets/16284848/21637860/da1a99ea-d2a3-11e6-9939-b51aa356c134.PNG)

while there exit no errors or warnings.

How to solve this problem? If no, how to identify the situation.

**Comment by hpinkos** [comment]
Hello @Tonyhzw, 

A lot of the time a completly blank screen is due to a networking problem.  Check the network tab in your debugger to see if there are files your browser was unable to load in.

If you have any follow up questions, please ask on our [forum](https://groups.google.com/forum/?hl=en#!forum/cesium-dev).  More people see those posts so it is more likely that another user might have experienced a similar problem and have a suggestion for how to fix it.  Thanks!
