### ISSUE TITLE
crunch <-> fs

### ISSUE THREAD

**Issue by chris-cooper** [AnalyticalGraphicsInc/cesium#4838]
There's a webpack build issue in our app when running from the latest 3d-tiles branch...
```
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'fs' in /path/to/our/app/node_modules/cesium/Source/ThirdParty
```
I notice [this PR](https://github.com/AnalyticalGraphicsInc/cesium/pull/4814) contains ```var nodeFS=require("fs")``` in [crunch.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/73fc5890920b8a752bda7770e0988036457e35dd/Source/ThirdParty/crunch.js) so is a likely cause of the problem.

**Comment by mramato** [comment]
Looking at the code, this sounds like a bug in webpack where it is trying to parse and handle those requires even though they are contained inside an if block that does not get executed in the browser.  Assuming webpack does not handle dynamic requires, is there at least a way to have them ignored?

Since crunch.js is output from emscripten and I believe is generated to work both in Node and the browser, I'm not sure what a good solution would be here.  Have you filed an issue with webpack?

**Comment by chris-cooper** [comment]
One of my colleagues has pointed out that you can add fs as an external in your webpack config to get around this issue...
```
    externals: {
        'fs': true,
    },
```
