### ISSUE TITLE
Massive models and upper LOD levels implementation

### ISSUE THREAD

**Issue by ibesora** [AnalyticalGraphicsInc/cesium#4908]
Have you considered using impostors, or something not geometry-based, for the far away 3d tiles? 
I'm thinking something like the [Visualization of Large-Scale Urban Models through Multi-Level Relief Impostors](http://moving.cs.upc.edu/papers/CiutatsPublicat.pdf) paper, published on the _Computer Graphics Forum_ in 2010 or this one [Interactive inspection of complex multi-object industrial assemblies](http://www.sciencedirect.com/science/article/pii/S0010448516300628) published  on _Computer Aided Design_ on 2016.

**Disclaimer:** I'm one of the authors of the second paper and I was working with the group that published the first. The first one it's something I've seen implemented with great results on cities and the second one works great for what you want to do with massive models.

**Comment by hpinkos** [comment]
Thanks for sharing @ibesora!  Those papers look like good resources for us to check out.
This topic is probably better suited for discussion in the forum.  You can share this in the 3D Tiles thread: https://groups.google.com/d/msg/cesium-dev/tCCooBxpZFU/O4VZ2dFdBAAJ
@pjcozzi and other members of the team working on 3D Tiles check that thread regularly.

I'm going to close this issue for now since it's not directly related to Cesium.  Thanks again!

**Comment by pjcozzi** [comment]
@ibesora thanks again for your note here and [additional info](https://groups.google.com/forum/#!topic/cesium-dev/tCCooBxpZFU%5B101-125%5D) on the forum.  I have actually been thinking about a similar approach for quite a while and am glad to see that you have everything figured out. :smile: 

I've added this to the 3D Tiles roadmap, #3241.

Also, we are organizing examples of folks using 3D Tiles.  Can you share any info about your GeoJSON to 3D Tiles pipeline and perhaps a screenshot so we can list it here: https://github.com/AnalyticalGraphicsInc/3d-tiles#whos-using-3d-tiles

Reply here or email me, pcozzi@agi.com
