### ISSUE TITLE
Scene unit tests crash tab in Firefox 51

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4942]
Run them here: http://cesiumjs.org/releases/1.29/Specs/SpecRunner.html?spec=Scene%2FScene

Tested on Windows with Firefox 51 and Nightly (54).

This does not happen in FF 50 on Mac.

This is likely due to the WebGL 2 updates in FF 51.  Will do more investigation before submitting a FF issue.

via @hpinkos 

CC @jdashg

**Comment by shehzan10** [comment]
I ran this test in "safe mode" on Firefox and it doesn't crash the tab. I get the following failure: `Scene/Scene debugShowBoundingVolume draws a bounding sphere`.

Continuing to investigate.

**Comment by pjcozzi** [comment]
> Scene debugShowBoundingVolume draws a bounding sphere

Looks like a pretty fragile test.  Perhaps the camera local is not ideal, e.g., it is too close to the sphere and not catching the wireframe.

Check out the other `debugShowBoundingVolume` tests and also consider using a non-rendering test with a spy instead of checking the rendered pixel.

**Comment by shehzan10** [comment]
I fixed this test by changing the position/radius of the bounding sphere. Seems to be a lot more stable now. Haven't pushed the code yet.

I've dug into the crash in firefox. Turns out its coming from https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/Scene/SceneSpec.js#L296.

The last point I could go into was the render call in globeDepth. Its crashing at drawElements. At first look the parameters seem to hold good.

```
continueDraw (Context.js:927)
Context.draw (Context.js:959)
DrawCommand.execute (DrawCommand.js:503)
GlobeDepth.executeCopyDepth (GlobeDepth.js:211)
executeCommands (Scene.js:1832)
executeCommandsInViewport (Scene.js:2201)
updateAndExecuteCommands (Scene.js:2059)
render (Scene.js:2512)
Scene.render (Scene.js:2551)
renderAndReadPixels (addDefaultMatchers.js:436)
renderEquals (addDefaultMatchers.js:443)
compare (addDefaultMatchers.js:232)

<async stuff from test>

SceneSpec.js:296
```

To test (and not make firefox crash), add a `debugger;` statement where necessary, and then when running the URL, click F12 so that the debug point gets caught.

**Comment by lilleyse** [comment]
Fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/6290
