### ISSUE TITLE
computeViewRectangle not compute rectangle properly in 3D

### ISSUE THREAD

**Issue by esraerik** [AnalyticalGraphicsInc/cesium#4960]
Hi .  
When  I try to get camera view rectangle in 3D with computeViewRectangle function not compute viewing rectangle properly.
When I very close an area like a city , It usually compute rectangle properly. But I try same thing like a continent area this method compute approximate area. I want to accurate area .

My cesium version is 1.26 . I hope this issue can be solving. 

Thanks.

**Comment by hpinkos** [comment]
Hello @esraerik,
Sorry, but I believe the `computeViewRectangle` function is working as expected for the further away camera locations. Depending on how the globe is tilted and how much of it is in view, the rectangle may be a little larger in order to make sure it covers everything in view.

In the future, please post things like this on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev

Thanks!
