### ISSUE TITLE
Does not layout correctly inside of a flexbox

### ISSUE THREAD

**Issue by lucastheisen** [AnalyticalGraphicsInc/cesium#4994]
I have created this jsfiddle to demonstrate the problem:

https://jsfiddle.net/lucastheisen/cpqfhws5/5/

In the run window, there is a button for leaflet and one for cesium.  If you click leaflet, everything is happy.  Resize the window and everything works as expected.   If, however, you click cesium, it may immediately fail, but if you start resizing the window it will eventually just start growing and growing...

**Comment by mramato** [comment]
@lucastheisen What browser and OS are you using?  Because your example has different behavior for me in Chrome and Firefox on Windows (In Chrome, leaflet doesn't show up at all but Cesium works, in Firefox I get the behavior you are describing).  

I think there is a problem with your example layout.  You have a `#cesiumContainer` element marked at 100% height.  If you remove that, everything appears to work fine on the Cesium side.

As an FYI, Cesium just relies on the browser layout engine for sizing, we don't do anything special so it should just size like any other div.  However, I'm not very familiar with flexbox, so if there's something specific we need to do on our end, please let us know.

**Comment by emackey** [comment]
This is not a Cesium bug, just a quirk of the way CSS flexbox interacts with a WebGL canvas.  I posted [a workaround on StackOverflow](http://stackoverflow.com/a/42183900/836708), give that a try, thanks!

**Comment by lucastheisen** [comment]
@mramato, I am using Firefox, Chrome, and Microsoft Edge on Windows 10.  In all 3 cases:

1) Navigate to https://jsfiddle.net/lucastheisen/cpqfhws5/5/
2) Make browser large enough to see content in the map area
3) Click `Cesium`, and let it load
4) Grab the browser window corner and resize up and down for a few seconds

However, it appears one of your committers (@emackey) provided an explanation and workaround on stackoverflow: http://stackoverflow.com/a/42183900/516433

Thanks for looking into this!

**Comment by KingHuaBo** [comment]
> https://jsfiddle.net/lucastheisen/cpqfhws5/5/

this url can't open,
could you post another，tks
