### ISSUE TITLE
Cesium Julian Date Related Question

### ISSUE THREAD

**Issue by tikhonovits** [AnalyticalGraphicsInc/cesium#5095]
Hi!

I am wondering why `JD = new Cesium.JulianDate(0,0);` returns: `Object { dayNumber: 0, secondsOfDay: 10 }`. Strangely enough JD advances with respect to the Julian Day by 10sec.

Shouldn't `JD.secondsOfDay` above be equal to zero?

Thanks,
Nikos

_Cesium Version: 1.29
Windows 10, Firefox DE 54.0a2 (2017-03-10) (64-bit), node.js 7.2.1 (x64) and npm_

**Comment by shunter** [comment]
10 seconds is the offset between UTC and TAI as of 1972.  JulianDates are stored internally in TAI, but the constructor you are calling defaults to UTC because you have omitted the TimeStandard.

In the future, please use the forum for general questions.  We use GitHub issues to track bugs and new features.
