### ISSUE TITLE
Quaternion.fromHeadingPitchRoll documentation is incorrect

### ISSUE THREAD

**Issue by shunter** [AnalyticalGraphicsInc/cesium#5264]
The `Quaternion.fromHeadingPitchRoll` function does not document the `headingOrHeadingPitchRoll` parameter, specifically that it can be a `HeadingPitchRoll` (and also does not mention the deprecating of the individual HPR parameters).

Code was apparently added in #4896 but documentation was not correctly updated.

**Comment by emackey** [comment]
The intermediate API has the first parameter as `headingOrHeadingPitchRoll`, but after the deprecated API is removed, presumably the name of the first parameter will then change to just `headingPitchRoll`.

Question, should the jsDoc parameter name match what's there right now, or match what the public API will become once the deprecated stuff is removed?  I would think the latter, otherwise the doc would have to explain what the oddly-named `pitchOrResult` parameter is supposed to be.

**Comment by pjcozzi** [comment]
> I would think the latter...

Sounds good.

**Comment by emackey** [comment]
@klingerj use `headingPitchRoll` as a single parameter in place of the first three (heading, pitch, roll) and leave the existing `[result]` parameter doc untouched.  Thanks!
