### ISSUE TITLE
Sandcastle CSS broken

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5265]
This is for all versions of Cesium, looks like CSS is no longer being loaded: http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=3D Models Coloring.html&label=Showcases

@emackey if I recall, we are abusing CSS in some way (inclusion outside of head maybe?) Is Edge possibly disallowing that?

Doesn't have to hold up this release, since it's been broken a while, but we should definitely fix it for next release.

**Comment by emackey** [comment]
> we are abusing CSS in some way (inclusion outside of head maybe?)

Yes.  This happened because of an old desire to have CSS share an edit window with HTML, for fewer editing tabs.  None of the other live-editors do this.  We should probably adopt a more jsFiddle-like layout, with JS, HTML, and CSS windows all visible at the same time as the result window.

**Comment by mramato** [comment]
I don't disagree with you, but in the short term we just need to fix Edge.  Can you provide some guidance on what the minimum we can do here is?  Just add another tab for CSS?

**Comment by emackey** [comment]
I believe so, yes.  The new tab would inject the CSS into the head, not the body.  If backwards-compatibility is a consideration, the load code could be adapted to look for `<style>` blocks in the body of the loaded file, and move them to the CSS window.  New files should be saved with the styling in the head of course.

**Comment by mramato** [comment]
@emackey any chance you can open a PR for the bare minimum change needed to work in Edge.  Having it completely broken is embarrassing.  If you don't have the time, can you provide some more detail regarding what has to happen.  Do we really need to add a third tab?

**Comment by hpinkos** [comment]
I've started seeing this in Chrome recently:

![image](https://user-images.githubusercontent.com/3451886/36816421-b7ac9fd6-1cab-11e8-809c-c6592d1dd107.png)

**Comment by hpinkos** [comment]
^^^^ 
This is becoming a real problem in Chrome

**Comment by mramato** [comment]
Yep, this is what I see most of the time these days.

![image](https://user-images.githubusercontent.com/1495196/45429304-09fdfc80-b671-11e8-913a-d139e57ebd94.png)

@emackey what's the most trivial way to fix this, would it be easy to add a third css tab in a backwards compatible way?  Or perhaps we can programmetically extract the style block from the HTML panel and programmetically inject it properly?

**Comment by mramato** [comment]
Either way, I'm marking this next release, it's embarrassing.

**Comment by hpinkos** [comment]
@emackey do you have time to look at this for the release on Oct 1st?

**Comment by emackey** [comment]
I've seen this happen on the main website, but I can't seem to reproduce it locally.

We theorized above about the desire for CSS in a separate tab, but I don't think we know for certain that's the root cause.  There could be some kind of caching or network race condition involved.

I'll spend some time investigating this afternoon, but I can't commit a ton of time to this.

**Comment by emackey** [comment]
I'm starting to wonder if we're being haunted by a very old problem here...  👻 

Looks like, when the widget is white, the CSS is indeed still being loaded.  What's broken appears to be SVG internal references, which are needed for the gradients on the animation widget.  It may finally be time to ditch the SVG gradients and go with a solid color theme on that widget.

**Comment by hpinkos** [comment]
@emackey clicking that button did fix the white widgets.

There's a separate problem with how viewer positions all of the widgets which results in the timeline widget going missing.  Calling `viewer.forceResize` will fix this:
![image](https://user-images.githubusercontent.com/3451886/45901160-06c0ea00-bdb0-11e8-846b-e3db3ef03577.png)

**Comment by mramato** [comment]
So this sounds like a Sandcastle specific race condition that happens because we are loading the CDD in the body and not waiting for it to finish before injecting the JavaScript?

If I got that correct, Couldn't this be fixed by waiting for the HTML to load in the iFrame in `activateBucketScripts` before injecting the JavaScript?

**Comment by mramato** [comment]
@hpinkos as a test, change line 628 to `setTimeout(loadScript, 2000);`  This obviously adds a 2 second delay, but I think it proves my above theory.

**Comment by hpinkos** [comment]
@mramato what was changing that line supposed to do?

**Comment by mramato** [comment]
Fix the problem.  I guess it didn't?

**Comment by hpinkos** [comment]
It's hard to say because like @emackey, I can't reproduce this issue locally.  I'm going to see if running the built version or throttling the network makes this reproducible locally

**Comment by mramato** [comment]
This won't make today's release, but I still want to see us figure it out before Nov 1st so I'm leaving the label.

**Comment by lilleyse** [comment]
@mramato @hpinkos @emackey Is there any chance that a fix can make it in by tomorrow? If not this is going to get pushed again.

**Comment by mramato** [comment]
Since we don't even have a PR open yet, I think this has to get pushed.

**Comment by hpinkos** [comment]
Yeah, @emackey spend some time looking into it last month but there wasn't a good easy fix.

**Comment by OmarShehata** [comment]
The fix was deployed by now right? 

I'm still seeing the white widget sometimes (in Chrome) as of today online...

**Comment by hpinkos** [comment]
@OmarShehata no, this probably won't be deployed until the next release at the beginning of December

**Comment by OmarShehata** [comment]
Oh, perfect! I thought it went out with the last release and was quite dismayed.

**Comment by mramato** [comment]
Bad news, this appears to still be a problem, though I think it might be a similar manifestation of the same issue:

![image](https://user-images.githubusercontent.com/1495196/49450190-8143b800-f7aa-11e8-83c1-2a5f4670df83.png)

**Comment by hpinkos** [comment]
This issue was actually two separate problems.  I think @OmarShehata fixed the problem where the CSS wasn't being applied, but the other issue is that `viewer.resize` is being called before the elements are ready and it doesn't know where to put the toolbar.  Viewer either needs to wait for the container to be ready, or we need to call `viewer.forceResize` somewhere.

**Comment by OmarShehata** [comment]
The real solution for this to simply compile all our CSS into one file. This was easy to test in the Standalone mode https://github.com/AnalyticalGraphicsInc/cesium/pull/7250 where it happens consistently locally. The problem is specifically that the `@import` tags are async. Another experiment to prove this is to put a dummy HTML element and style it, then poll every frame to see if that style is applied. 

So if this is `bucket.css` and my dummy element is called `#loader`:

```
@import url(../../../Source/Widgets/widgets.css);
@import url(../../../Source/Widgets/lighter.css);
#loader { width : 121px!important }
```

Then the style `#loader { width : 121px!important }`  will get applied **before** the styles in `../../../Source/Widgets/widgets.css`! It looks like the deeper you go into this @import chain the longer it takes for the CSS to get applied. It takes about 4 frames for the final `Viewer.css` to get applied (compared to the loader element's CSS which gets applied after 2 frames). 

If you just copy paste the content of `Viewer.css` into `bucket.css` the issue is resolved. 

I think it's strange that Sandcastle code, even built one, is reaching into the source code to grab CSS anyway. That means the built Sandcastle will not work unless the source code is in the same directory?

**Comment by tfili** [comment]
@OmarShehata I'm assuming this is getting pushed again?

**Comment by OmarShehata** [comment]
@tfili yeah this is fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/7250 but I couldn't get it reviewed in time.

**Comment by OmarShehata** [comment]
Yeah, since it was already "fixed" before I was going to wait a week or two into release before celebrating. (Or we can close and re-open if we enjoy these emotional rollercoasters).

**Comment by mramato** [comment]
![bob](https://user-images.githubusercontent.com/1495196/52075885-651a8800-255b-11e9-9e01-c55605183baf.gif)
