### ISSUE TITLE
Consider defaulting to the Fetch API, instead of XmlHttpRequest, when available

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5322]
Not sure what the timing of this should be or if it is worth it.

https://css-tricks.com/using-fetch/

**Comment by mramato** [comment]
There are undeniably benefits to `fetch`, but none of them apply to Cesium as it is today, for a few reasons:

* IE11 will never have `fetch` support, so we need a fallback path anyway.
* `XMLHttpRequest`isn't going anywhere and there's no immediate benefit to simply using `fetch` instead.
* As far as I can tell, none of the new features, such as response streaming, really apply to our use cases.  Perhaps CZML and GeoJSON loading, but the code would have to be updated to use them and I'm not sure how much benefit it would provide).

Since we only create `XMLHttpRequest` instances in two places (which looking at the code should probably be one), switching it over to use fetch on supported platforms would be trivial, but I'm just not sure there's any reason to do it.

If anyone else has any ideas or benefits that I might have overlooked, please speak up.  Otherwise, I vote we just close this and revisit when we have a use case for it that doesn't need to support IE11.

**Comment by pjcozzi** [comment]
Let's close.  If anyone has additional feedback, please comment.

**Comment by denverpierce** [comment]
`fetch `with JSON parsing has lower performance in Chrome 58 than `XMLHttpRequest`, and higher perf in Firefox 53 per [performance tests](https://github.com/arendjr/fetch-vs-xhr-perf).

Heavy JSON parsing doesn't map well to Cesium xhr load, but it does show that there are performance considerations for switching.

**Comment by mramato** [comment]
Thanks for the link @denverpierce, I don't think it changes the current plan but it's something we definitely need to consider when we eventually do move to fetch.
