### ISSUE TITLE
 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by chenp1204** [AnalyticalGraphicsInc/cesium#5464]
When compiling with webpack, the following is error message.

WARNING in ./~/_cesium@1.34.0@cesium/index.js
11:35-42 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

ERROR in ./~/_requirejs@2.3.3@requirejs/bin/r.js
Module parse failed: E:\iview-project-2.0\node_modules\_requirejs@2.3.3@requirejs\bin\r.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node
| /**
|  * @license r.js 2.3.3 Copyright jQuery Foundation and other contributors.
 @ ./~/_cesium@1.34.0@cesium/index.js 5:16-36
 @ ./src/main.js
 @ multi ./~/_webpack-dev-server@2.4.5@webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main

**Comment by mramato** [comment]
Thanks @chenp1204, this is an issue with webpack, not with Cesium.  The good news is it's fixable, you just need to set some additional configuration options. See https://github.com/AnalyticalGraphicsInc/cesium/issues/4876 for more info but if you still need support please create a post [on the forum](https://groups.google.com/forum/?fromgroups#!forum/cesium-dev) (none of the Cesium team uses Webpack so you'll get better help from the greater community).  In the future, we definitely want to make using Cesium and Webpack more straightforward (but like I said, the issue is ultimately on the webpack side of things).

**Comment by chenp1204** [comment]
Thank you very much !

**Comment by DomDomHaas** [comment]
> 
> 
> Thanks @chenp1204, this is an issue with webpack, not with Cesium. The good news is it's fixable, you just need to set some additional configuration options. See #4876 for more info but if you still need support please create a post [on the forum](https://groups.google.com/forum/?fromgroups#!forum/cesium-dev) (none of the Cesium team uses Webpack so you'll get better help from the greater community). In the future, we definitely want to make using Cesium and Webpack more straightforward (but like I said, the issue is ultimately on the webpack side of things).

Could a give more specific answer to what in the See #4876 is mentioned to fix the "Critical dependency" issue?
