### ISSUE TITLE
Simple way to see precise CI failure

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5688]
Unless there is an option that I am missing, right now we need to manually search by clicking through the drop downs:

![image](https://user-images.githubusercontent.com/782098/28720234-8c32df26-737a-11e7-8a2b-ad674c1a7993.png)

**Comment by mramato** [comment]
The drop downs are there because otherwise there is too much output and travis won't show the entire log.  We actually opt-in to the drop downs for this reason.

I think there are two options here:

1. (preferred) Get rid of the dropdowns and cut down our output so there's not so much noise on successful builds and only output pertinent error information,
2. Update the travis.yml to figure out which task failed and put that information at the end (may be a little tricky, but doable).

**Comment by mramato** [comment]
With #7207, we might be able to get rid of dropdowns.

However, travis has enhanced GitHub integration now as well, so I think if we enable that it will tell us exactly which stepped failed within github without looking at the logs. I want to look into this as part of other CI improvements: https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com
