### ISSUE TITLE
Cesium Viewer crashes on MacOS (Safari) and iOS (all) with rapid mouse movement

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5691]
The Viewer reference app uses `replaceState` pretty much every time the camera moves, this leads to a security error on all Safari versions and results in a crash.  Just move them camera a whole bunch and you'll crash. Basically, you aren't allowed to call `replaceState` or otherwise much with history more than 100 times over 30 seconds.

While Apple having a check like this is questionable, we probably shouldn't be calling it that often to begin with.

NOTE: This only applies to the CesiumViewer reference app, which updates the URL to match the camera position, not the Viewer widget.

**Comment by avalan4e57** [comment]
Hello. I'm new to contributing on open source projects. Don't know if I got you exactly, but there's a pull request with how I see the fix of the problem. By the way I can't test the stuff locally because I get this type of errors in browser js console `error for: Cesium/Shaders/...`. A `404` one if to be exact. Can you please help me with that?

**Comment by hpinkos** [comment]
Thanks for looking into the problem @avalan4e57!  For running the code locally, see the information in our [Build Guide](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/BuildGuide).  When you're ready to open a pull request, take a look at our [contributing documentation](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#opening-a-pull-request) for guidelines.

I saw your commit and I think that's a good start (that code is clearly incorrect and you're change fixes that), but I think we can make it even better by listening to the [`Camera.changed`](http://cesiumjs.org/Cesium/Build/Documentation/Camera.html#changed) event instead of `moveStart`/`moveEnd`, and using a `setTimeout`/`clearTimeout` instead of a `setInterval` to make sure `replaceState` is only called at most once a second.

And yes, the `camera` parameter passed to the `setInterval` function looks like it can be removed

**Comment by avalan4e57** [comment]
Thanks for reply @hpinkos ! Everything works ok on my local now. Made some changes there. And there's a question in the comment to some code lines in the commit. So, if everything is ok, guess I need to make a pull request since I've read already contributing documentation?

**Comment by hpinkos** [comment]
@avalan4e57 Go ahead and open the pull request.  It'll be easier for us to review it that way instead of looking at your individual commits

**Comment by avalan4e57** [comment]
#5699

**Comment by avalan4e57** [comment]
Made pull request #5699 yesterday. Maybe I should mention about it here.
