### ISSUE TITLE
Web Map Tile Service with Time Sandcastle demo logs a lot of errors

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5712]
@tfili can we avoid this?

```
An error occurred in "WebMapTileServiceImageryProvider": Failed to obtain image tile X: 1 Y: 3 Level: 2.
An error occurred in "WebMapTileServiceImageryProvider": Failed to obtain image tile X: 0 Y: 3 Level: 2.
An error occurred in "WebMapTileServiceImageryProvider": Failed to obtain image tile X: 1 Y: 3 Level: 2.
An error occurred in "WebMapTileServiceImageryProvider": Failed to obtain image tile X: 0 Y: 3 Level: 2.
An error occurred in "WebMapTileServiceImageryProvider": Failed to obtain image tile X: 1 Y: 3 Level: 2.
...
```

**Comment by tfili** [comment]
@hpinkos Nope. The way GEE for enterprise works, is that we retrieve the metadata for 4 levels at a time (3 for the root tile). So when a tile is requested that we don't have metadata for, we have to return a promise for the metadata request instead of `undefined`, which would be a correct response for a missing tile. Then later we realize there isn't an imagery tile, so the promise returns undefined which is what causes this error.
