### ISSUE TITLE
Clean up czm_alphaWeight

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#5727]
via @pmconne 

In `czm_alphaWeight` we compute the fragment position in eye space when it isn't needed. It was used in previous versions, but can be removed.

**Comment by lilleyse** [comment]
@loshjawrence 

The shader can be simplified a lot since `q`, `x`, and `y` are not actually used.

After making shader changes you'll need to run `npm run build` which converts the .glsl files to .js files. In general, `npm run build` is required when adding or removing files or making shader edits.

You can also use `build-watch` which auto-detects shader changes.

For testing, make sure OIT still works, for example in [Geometry And Appearances](http://localhost:8080/Apps/Sandcastle/index.html?src=Geometry%20and%20Appearances.html).
