### ISSUE TITLE
Page load fails on successful compile, assets 404 do not load, tree shake removes lib

### ISSUE THREAD

**Issue by CHBaker** [AnalyticalGraphicsInc/cesium#5863]
- [x] bug report
- [ ] feature request

## Versions.

```
@angular/cli: 1.4.1
node: 8.2.1
os: linux x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.1
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4
```

*also tested on macOS latest, page loads but with issues.

## Repro steps.

reproduce this issue by cloning [this repo](https://github.com/CHBaker/Cesium-Injection)
npm install, ng serve

more: this bug occurs in attempt to use cesium with Angular, using dependency injection to allow coding with all the modules IN TYPESCRIPT

*when using ng serve --prod, tree shake removes lib, how do I stop this?

## The log given by the failure.

Google chrome loads for a long time, then displays 'Oh snap' page load failer
Firefox asks to wait or stop page 3 times, after clicking wait everytime, page loads with all failed requests for assets

Angular says compile was successful

## Desired functionality.

Page to load in normal time

Cesium dependencies like terrain assets not loading? 404 not found for all assets like globe, terrain, etc

for some reason all the requests are failing. why is the load time so crazy long?

**Comment by hpinkos** [comment]
Hello @CHBaker.  Sorry you're having trouble with this.  Unfortunately, no one on the Cesium team is familiar with angular.  Cesium also doesn't have typing support so that may be part of the issue.  I would recommend posting your question on the forum: https://groups.google.com/forum/?l=en#!forum/cesium-dev
The forum has a lot more visibility to the larger Cesium community, so it is more likely that someone who is using Cesium+angular will see your post and be able to help out.   We use GitHub exclusively for tracking bugs in Cesium and planning new features.

**Comment by bampakoa** [comment]
@CHBaker although this issue is a bit old, I would be happy to help you in case your problem persists 😃
