### ISSUE TITLE
gltf model looks different in cesium than in other viewers (transparent)

### ISSUE THREAD

**Issue by tkazik** [AnalyticalGraphicsInc/cesium#5880]
Hi folks

I have a model that I exported from blender to gltf 2.0 using the [official exporter from khronos](https://github.com/KhronosGroup/glTF-Blender-Exporter).
It looks nice in [donmccurdy's viewer](https://gltf-viewer.donmccurdy.com/). However, it looks opaque in [cesium](https://cesiumjs.org/) or [virtualgis](https://www.virtualgis.io/gltfviewer/):

![comparison](https://user-images.githubusercontent.com/15689124/31134076-7bb7a732-a861-11e7-8840-36e2dbed8158.png)

I asked this question already [here](https://github.com/mrdoob/three.js/issues/11990#issuecomment-333893257)  in three.js and was asked to report it here. :)

In the zip, you will find the blend file including texture and the .gltf.
[aircraft_blend_and_gltf.zip](https://github.com/mrdoob/three.js/files/1352842/aircraft_blend_and_gltf.zip)

Thank you very much for your advice!

**Comment by emackey** [comment]
That's a beautiful aircraft.  You've got two materials there, one named `DefaultWhite` for most of the body, and another named `transparent` for the windows.  In the glTF, both of these materials are set to `"alphaMode" : "BLEND"`.  The first one, `DefaultWhite`, should be `"alphaMode" : "OPAQUE"` on line 5217.  There's probably a change you can make in Blender to fix this, try turning off the "transparency" section of the Materials GUI for this material, and re-exporting to see if this line changes.

Why does it look this way in Cesium?  A couple of reasons.  First, although the virtualgis viewer is showing a white background, it does not appear to be *blending* with the white background, it looks like it's blending against black, the default.  If you look at this model in Cesium against a black background, you can see the model looks "faint", very translucent, blending against itself in all kinds of places where the other engines (Babylon and ThreeJS) don't blend.

That brings me to the second point:  Cesium, by default, uses a system called OIT, or "Order Independent Translucency."  The OIT system allows transparent surfaces to render the same way regardless of render order, but there's a price:  No translucent surface can be more than 50% opaque, such that if it were swapped in order with the other surface, one does not appear to "win" over the other one (as the other two rendering engines are doing in this case).  So with translucent materials limited to 50% opacity, the whole aircraft looks wispy and shadowy and blends with the scene's background color (black, not white, in this case).

If you look closely at the Babylon and ThreeJS versions, you'll find other subtle problems stemming from the fact that the aircraft body is not set to opaque, but rather blended at 100% alpha.  You can fix these problems in all 3 engines by turning off the blending.

I'm going to close this because I don't think there's much for us to do here.  Let us know if you disagree. 
 Good luck!

(PS. Can we modify/use that model?  What are the distribution rights? 😄 )

**Comment by tkazik** [comment]
> There's probably a change you can make in Blender to fix this, try turning off the "transparency" section of the Materials GUI for this material, and re-exporting to see if this line changes.

That did exactly the magic: By unchecking transparency, DefaultWhite does not have an alphaMode anymore and the model looks as you predicted. Also thank you very much for your awesome explanation!

![nomorealphamode](https://user-images.githubusercontent.com/15689124/31167195-822b5e66-a8f1-11e7-9fe0-1343f9bf9841.png)

Regarding the model, thanks for the compliment, but you will have to forward it and ask [Heliah](https://github.com/FGMEMBERS/Falcon-50) regarding the rights...I am just fiddeling a bit with it because I also like it :)

**Comment by emackey** [comment]
Oh, nice, thanks for the link.  Following that I found his [webpage on it](http://helijah.free.fr/flightgear/hangaren.htm), with an embedded [SketchFab viewer of it](https://sketchfab.com/models/zl1ZHdqCY5bYbwbWNypasS7VT6N).  The GitHub repo is GPL-2.0, but Sketchfab has it available for free download under [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/).

**Comment by tkazik** [comment]
Sweet, thanks for the Sketchfab link! 
If by any chance you happen to do some animations with it, I would be very happy to learn more about it. There was just an update in [kupoman's blender exporter](https://github.com/Kupoman/blendergltf/issues/103), however I am still missing the link to 'states', e.g. gear up/down which can then be controlled from within cesium. Do you have a clue on how to tackle that?
