### ISSUE TITLE
Better KML Network Link Error Handling

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5921]
In #5871 we added a catch when a network link fails.  This makes it impossible to detect and handle errors programmatically.  We might want to consider adding support for a callback when a network link fails.

**Comment by thw0rted** [comment]
It looks like failed network links already raise the `errorEvent`, which is good, except for [this one overlooked case](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.41/Source/DataSources/KmlDataSource.js#L2256), which is an easy fix.  Compare with L2427 -- basically, any `loadBlob.otherwise()` should be raising the error event and the linked PR didn't follow that pattern.

This bit me today. I loaded a file (from a "good" server) that includes a NetworkLink on a "bad" server, with a self-signed cert I hadn't manually added an exception for.  The initial (KML) load was fine, so the error handler I'd attached to the promise returned by `src.load()` didn't fire, but the NetworkLink load (which of course fires asynchronously) didn't work.  Anyway, easy one-line fix and I think this can be closed.  I'd do it myself but I never got my dang management to sign off on the CLA.  (I'll bug them again, I swear!)
