### ISSUE TITLE
Does the geometryinstanceAttribute support gradient color like polylineGeometry colors

### ISSUE THREAD

**Issue by hanaimin** [AnalyticalGraphicsInc/cesium#6007]
following code will cause a error:  TypeError: Cannot read property 'x' of undefined

var instance = new Cesium.GeometryInstance({
                    geometry: polyline,
                    attributes: {
                        //color:Cesium.ColorGeometryInstanceAttribute.fromColor(new Cesium.Color(1.0, 0.0, 0.0, 1))
                        color : new Cesium.GeometryInstanceAttribute({
                            componentDatatype : Cesium.ComponentDatatype.UNSIGNED_BYTE,
                            componentsPerAttribute : 4,
                            value : **//can i set a unit8Array here for gradient color**
                            normalize : true
                        })
                    },
                    id: 'circle' + index
                });

**Comment by hpinkos** [comment]
Hello @hanaimin, please ask your question on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
The forum has much higher visibility and it is more likely that someone will see your post and be able to help.  We use GitHub exclusively for tracking bugs and planning new features.  Thanks!

**Comment by mramato** [comment]
@hanaimin to answer your question, no, per-vertex colors can't be used and are specific to the PolylineGeometry.  You could probably write a custom material to do what you want, but I don't have any examples handy.  As @hpinkos states, you might have better luck asking on the forum since this might have come up before.  I know one workaround might be to generate a gradient with the canvas and then use an image material; but there could be better options
