### ISSUE TITLE
Clipping planes broken in IE

### ISSUE THREAD

**Issue by ggetz** [AnalyticalGraphicsInc/cesium#6048]
See discussion in #6038.

There is an issue with the GLSL compilation in IE that disables clipping plane functionality.

**Comment by pjcozzi** [comment]
For example:

http://localhost:8080/Apps/Sandcastle/index.html?src=3D Tiles Clipping Planes.html&label=All

![aaa](https://user-images.githubusercontent.com/782098/34486542-6ef40eb2-ef9e-11e7-96af-f8be8ede4753.gif)

@likangning93 perhaps your infinite clipping planes and clipping boxes will fix this...

**Comment by pjcozzi** [comment]
Perhaps related to #6077

**Comment by pjcozzi** [comment]
@likangning93 as part of your infinite clipping plane and box work, we also want to fix this (post 1.41) - which I think will just happen by moving from uniform arrays to textures - but also by adding the infrastructure to `Model.js` so that shaders can be recompiled to add/remove the clipping plane code like `Globe` currently does.

@lilleyse can help once everything else is done for infinite clipping planes/boxes.

**Comment by likangning93** [comment]
Herm... not fixed yet, and also not working in Edge (although I don't think it's working in Edge in `master` either).

**Comment by likangning93** [comment]
Okay. This should be fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/6201, but the bug wasn't just uniform arrays. See https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Shaders/Builtin/Functions/windowToEyeCoordinates.glsl#L34.

IE and Edge were always having this check (`mat4` inequality) return false, which seems like a bug with their WebGL implementation.

**Comment by pjcozzi** [comment]
Good catch, thanks @likangning93

**Comment by mramato** [comment]
Removing priority next release, this will come in with #6201
