### ISSUE TITLE
Chrome crashes (out of memory) when adding > ~100k entities

### ISSUE THREAD

**Issue by greenlaw** [AnalyticalGraphicsInc/cesium#6081]
I'm attempting to add a large number of SVGs (>100k) to the map.  This works fine when using simple Billboard Primitives, but when using the Entities API, Chrome (63.0.3239.84) crashes.  Developer Tools indicates "Paused before potential out-of-memory crash".  (IIRC I've had Firefox crash on me before as well, but can't confirm that right now...it seems to be working even with 120k entities)

Working example (using Billboards):  https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=15e289eefc2d71246b7b81f7c1dd3aad

Crashing example (using Entities):  https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=ebe7cb3c20394e45efdd5e47ea226d3a

**Comment by vatsalpande** [comment]
were you able to find an answer to this?

**Comment by greenlaw** [comment]
No, I just abandoned Entities and stuck with Billboards

**Comment by hpinkos** [comment]
Hi @greenlaw, yes unfortunately there is a little more memory overhead when using entities.  Using a `BillboardCollection` directly is probably the way to go when you're adding this many billboards to the scene.  Ultimately, I think using 3d-tiles vector tiles will be the recommended solution for adding a large amount of billboards like this.  The vector tiles specification is still in progress, but we have a roadmap issue here: https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/25

I'm going to close this issue because I don't think there is anything actionable for us at this time.  I'm glad you were able to use billboards to solve your problem!
