### ISSUE TITLE
cutting models  failed

### ISSUE THREAD

**Issue by c-y-q** [AnalyticalGraphicsInc/cesium#6105]
Why load the JSON format exported by smart3d to the graph without cutting effect? 

the jsonFile  url： http://mapapitest.tygps.com/fb_cesiumapi/Model/WJJSM/Data5/Tileset.json

**Comment by c-y-q** [comment]
How are the model files generated under the Apps/SampleData/models folder? Thank you for your guidance.

**Comment by ggetz** [comment]
Hi @c-y-q , I'm not sure what the problem is here exactly, could you provide more context, or perhaps a [Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases)? 

If this is a question, please ask over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev).  There are members of the community and developers from the team who answer these kinds of questions there. Additionally, Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!

**Comment by c-y-q** [comment]
Hi @ggetz @rutsky 
Cesium Forum cannot be accessed in China. I am very sorry... I refer to https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=3D%20Tiles%20Clipping%20Planes.html&label=Showcases，I redirected < loadTileset('http://mapapitest.tygps.com/fb_cesiumapi/Model/WJJSM/Data5/Tileset.json'); >,
But there is no cutting effect ,as shown in the figure

![jdfw2](https://user-images.githubusercontent.com/24750024/34814950-7dc99490-f6ea-11e7-9e68-646c6933f87c.gif)

**Comment by ggetz** [comment]
I think all you'll need to do is set the [`ClippingPlanesCollection.modelMatrix`](https://cesiumjs.org/Cesium/Build/Documentation/ClippingPlaneCollection.html?classFilter=clipp#modelMatrix).

```
tileset.clippingPlanes.modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(tileset.boundingSphere.center);
```

**Comment by c-y-q** [comment]
@ggetz  I thank you very much. It  has worked. 
![jdfw3](https://user-images.githubusercontent.com/24750024/34858708-cb38fcf0-f78c-11e7-83be-ac6165904e37.gif)

**Comment by ggetz** [comment]
Great!
