### ISSUE TITLE
cloc does not work on Windows?

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#6161]
`npm run cloc` reports "The command line is too long."  Perhaps because of the number of source files and their length?

Works on Mac and Linux (via CI).

I am running Windows 7 still.  If this works in Windows 10, let's just close.

**Comment by mramato** [comment]
Doesn't work on Windows 10 either, this is because we list every glsl file on the command line instead of using a wildcard (to ignore the generated `.js` files that sit next to the glsl.)  But I'm not sure that's the correct thing to do either.  I think we want to have cloc depend on `clean` instead of `build` and then just add the `Source/Shaders/` directory.
