### ISSUE TITLE
Remove assets.agi.com deprecation notice

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6279]
For the September 1st release, when we shut down assets.agi.com, the deprecation code in `CesiumTerrainProvider` can be removed.

**Comment by ggetz** [comment]
@mramato Is the assets.agi.com shutdown still targeted for this release?

**Comment by mramato** [comment]
No, we are pushing it to 1.50 but including a slightly different message for Sep 1, expect a PR later today.  I already updated the label.

**Comment by mramato** [comment]
Actually, thinking about this some more it makes more sense to do this in 1.51.  This way if anyone attempts to use assets.agi.com in the next release, they still see the deprecation message even though the server itself is gone.

**Comment by hpinkos** [comment]
Okay, I'll just double check the text of the warning to make sure it still makes sense.  Since this will likely impact a bunch of people I think you're right that it makes sense to leave the warning to hopefully avoid getting a ton of 'why is my globe invisible' questions.  I think we should leave it through the end of the year.
