### ISSUE TITLE
glTF 2.0 animations can't target unspecified targets

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#6323]
I have a sample model, that came from the Khronos Blender exporter, that has an animation like this:

```
    "animations" : [
        {
            "channels" : [
                {
                    "sampler" : 0,
                    "target" : {
                        "node" : 1,
                        "path" : "rotation"
```

This one targets `rotation`.  But the node in question, `"node": 1`, looks like this:

```
        {
            "mesh" : 0,
            "name" : "Cube"
        },
```

What's missing from Node 1?  There's no `rotation` specified in that node.

Cesium is currently disregarding the animations in this model, and the correct behavior only appears if I add `"rotation" : [ 0.0, 0.0, 0.0, 1.0 ]` to the node in question.  But I don't think anything in the glTF spec disallows applying an animation to a default value.  So, I think this should be supported (but I can check in with the working group if there's any question).

To reproduce this problem, grab a copy of [AnimatedTriangle.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedTriangle/glTF-Embedded/AnimatedTriangle.gltf) and delete [line 11](https://github.com/KhronosGroup/glTF-Sample-Models/blob/c589f377c84b4767ef1532e51e92173f47b1eb42/2.0/AnimatedTriangle/glTF-Embedded/AnimatedTriangle.gltf#L11) where the node is given a default rotation of the identity quaternion.  (Also remove the comma on line 10 so that the JSON remains valid).  The resulting model works fine in Babylon and ThreeJS, but does not animate in Cesium.

**Comment by lilleyse** [comment]
@emackey and I talked about this a bit offline:

To fix this we can either:
* Improve `gltf-pipeline/addDefaults` so that it adds translation/rotation/scale defaults instead of a matrix default when targeted by an animation.
* Add checks for missing translation/rotation/scale in the animation code only.

Questions:
* What happens if a node uses a `matrix` but an animation targets a `rotation`? Does the spec say anything about this case?
