### ISSUE TITLE
Use legacy environment enabled build for draco decoder module

### ISSUE THREAD

**Issue by ggetz** [AnalyticalGraphicsInc/cesium#6404]
CC #6399

There's an error when loading the draco decoder module in IE as the build of the deocder we are using (https://github.com/google/draco#javascript-encoderdecoder) does not support IE as it is a "Legacy environment". We need to use a version built with legacy support.

**Comment by pjcozzi** [comment]
Isn't this duplicate with #6399?

Did we ship 1.44 with Draco not working IE?  Does it at least fail gracefully?

**Comment by ggetz** [comment]
Closed #6399 to allow it it fail gracefully, and opened this as we need to rebuild the draco module itself.

**Comment by mramato** [comment]
@ggetz is this fixed with #6420?  If not, is it still planned for May 1?

**Comment by ggetz** [comment]
This was not fixed in #6420, I will try to take a look this afternoon or tomorrow to see if we can get this in for May 1.

**Comment by ggetz** [comment]
@mramato Sorry, I know it's holding up PRs, but I'm not sure I'll be able to get to it this week with other deadlines.

**Comment by mramato** [comment]
@pjcozzi any thoughts here?  Lack of Draco in IE11 is holding up both Draco point cloud support and updating all of the default ion tilesets to Draco. I was really hoping to have Draco assets in Cesium for FOSS4G since they are so much smaller/faster.

One option is to just not worry about IE11 in master but make sure we fix in for June 1.

**Comment by pjcozzi** [comment]
Sorry we need to finish the 3D Tiles spec tweaks first - will only be a few days.
