### ISSUE TITLE
[ION][asset][terrain] terrain asset not properly integrated into cesium terrain

### ISSUE THREAD

**Issue by tkazik** [AnalyticalGraphicsInc/cesium#6651]
Hi folks

I am encountering some issues in cesium ion's composer: I created a locally flat terrain in QGIS and exported it as geotiff, which can be loaded into cesium's composer (basically following this [tutorial](https://cesium.com/docs/tutorials/getting-started/)). When zooming closer to the asset, it vanishes...some sort of clipping issue, see:

![cesium_terrain_asset_short](https://user-images.githubusercontent.com/15689124/40878472-11ebc122-6692-11e8-91b3-d15653801150.gif)

Thx for any hints and tipps!

PS: geotiff is here:
[outputRiad_700m_skew.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/2065165/outputRiad_700m_skew.zip)

**Comment by hpinkos** [comment]
Hmm, I haven't seen this problem before.  Thanks for including the screen capture and the geotiff!  That will make it a lot easier for us to debug the issue.
We'll give you an update once we have a chance to look into this.  Thanks!

**Comment by hpinkos** [comment]
Actually, I thought you had made this post in a different repo.  We have a repo set up specifically for ion issues here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community

I've created an issue for you related to this problem here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/17

I think this might be an issue with the tiler, not a problem with CesiumJS, so I'm going to close this issue and we'll track progress in https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/17 instead.  Thanks!
