### ISSUE TITLE
Escape key doesn`t work sometimes

### ISSUE THREAD

**Issue by jatskopolina** [AnalyticalGraphicsInc/cesium#6653]
Hello,
we have noticed uncomfortable behaviour. Users can switch to fullscreen using key "F11" and then try switching back using escape button. This fails, they can only use "F11" again.. Are you going to deal with it?

**Comment by mramato** [comment]
This is browser-specific behavior and not something Cesium has control over.

1. F11 puts most browsers in full-screen mode and they will stay in this mode until F11 is pressed again.  This means even if you navigate to a new website, the browser stays fullscreen.  Cesium has no control over this because it's browser application level behavior.
2. The Cesium full-screen button uses the JavaScript fullscreen API, this is different from F11 and will exit fullscreen when escape is pressed.  This is the API Cesium uses for its fullscreen button (and the only API available to JS developers).  As far as I know, there's no way to change the F11 behavior to use this mode instead.

We recommend questions like this get asked on [our forum](https://groups.google.com/forum/?fromgroups#!forum/cesium-dev).  Many more people will see it and may have some additional ideas.  Thanks.
