### ISSUE TITLE
PolylineVolumeGeometry improvements

### ISSUE THREAD

**Issue by miniergouzi** [AnalyticalGraphicsInc/cesium#6712]
![m 0kz uqgx2 3c58xskxw6b](https://user-images.githubusercontent.com/40375251/41702138-8f8373d6-7561-11e8-8b7a-794ecf4fda1a.png)

var viewer = new Cesium.Viewer('cesiumContainer');

function computeStar(arms, rOuter, rInner) {
    var angle = Math.PI / arms;
    var length = 2 * arms;
    var positions = new Array(length);
    for (var i = 0; i < length; i++) {
        var r = (i % 2) === 0 ? rOuter : rInner;
        positions[i] = new Cesium.Cartesian2(
            Math.cos(i * angle) * r, Math.sin(i * angle) * r);
    }
    return positions;
}

var blueStar = viewer.entities.add({
    name : 'Blue star with mitered corners and outline',
    polylineVolume : {
        positions : Cesium.Cartesian3.fromDegreesArrayHeights(
            [-95.0, 32.0, 0.0,
             -95.0, 36.0, 100000.0,
             -99.0, 36.0, 800000.0]),
        shape : computeStar(7, 70000, 50000),
        cornerType : Cesium.CornerType.MITERED,
        material : Cesium.Color.BLUE,
        outline : true,
        outlineColor : Cesium.Color.BLACK
    }
});

 viewer.zoomTo(blueStar);

**Comment by miniergouzi** [comment]
var viewer = new Cesium.Viewer('cesiumContainer');
 

 function computeStar(arms, rOuter, rInner) {
    var angle = Math.PI / arms;
    var length = 2 * arms;
    var positions = new Array(length);
    for (var i = 0; i < length; i++) {
        var r = (i % 2) === 0 ? rOuter : rInner;
        positions[i] = new Cesium.Cartesian2(
            Math.cos(i * angle) * r, Math.sin(i * angle) * r);
    }
    return positions;
}

 
var blueStar = viewer.entities.add({
    name : 'Blue star with mitered corners and outline',
    polylineVolume : {
        positions : Cesium.Cartesian3.fromDegreesArrayHeights(
            [-95.0, 32.0, 0.0,
             -95.0, 36.0, 100000.0,
             -99.0, 36.0, 800000.0        //Vertical change
            ]),
        shape : computeStar(7, 20000, 50000),
        cornerType : Cesium.CornerType.MITERED,
        material : Cesium.Color.BLUE,
        outline : true,
        outlineColor : Cesium.Color.BLACK
    }
});

**Comment by hpinkos** [comment]
Hello @miniergouzi, thanks for opening this issue!  I've known about this behavior for a while, but it looks like we don't have a GitHub issue open for it.  I designed the `PolygonVolumeGeometry` so that the end caps are always perpendicular to the earth's surface, but that was the wrong decision.  They should be perpendicular to the center line instead.

I started making changes to it on this branch a few years ago: https://github.com/AnalyticalGraphicsInc/cesium/tree/polylineVolumeOverhaul
I'm not sure how soon we'll be able to revisit this to finish the changes, but I'll give you an update when we have one.  Or if you have time to look into it, we're always happy to review a Pull Request.  You can find resources for building and making changes to the library in our [Contributor Documentation](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors)
