### ISSUE TITLE
The error in computing the bbox value (WMS Imagery Provider)

### ISSUE THREAD

**Issue by ollazarev** [AnalyticalGraphicsInc/cesium#6719]
1. The WMS Imagery provider start from the third level computes the BBOX values with an error. Example:

> x=6, y=1, "level: 2" => bbox: [90, 0, 135, 45]
> x=7, y=2, "level: 2" => bbox: [135, -45, 180, 0]
> x=5, y=3, "level: 2" => bbox: [45, -90, 90, -45]
> x=10, y=0, "level: 3" => bbox: [45, 67.5, 67.49999999999997, 90]
> x=11, y=0, "level: 3" => bbox: [67.49999999999997, 67.5, 90, 90]
> x=11, y=1, "level: 3" => bbox: [67.49999999999997, 45, 90, 67.5]

![untitled-0](https://user-images.githubusercontent.com/5917702/41769272-6511a1e8-7617-11e8-8eb0-c773a04e7924.png)

2. WMS Imagery provider code:

```javascript
new Cesium.WebMapServiceImageryProvider({
  url : `${config.server}/fp3d_fcgi/wms/wms`,
  layers : datasetName,
  parameters: {
    format: 'image/jpg',
  },
  tileWidth: 256,
  tileHeight: 256,
});
```

3. Cesium version: 1.46.1

**Comment by hpinkos** [comment]
@ollazarev I'm sorry, I don't understand what the problem is.  Can you please elaborate a little on the error you're seeing and what you expect the results to be?

**Comment by ollazarev** [comment]
I see an error in calculating the the BBOX values after the decimal point.
For example, for coordinates `x=10, y=0, "level: 3"` BBOX should take a value `[45, 67.5, 67.5, 90]` but in the current Cesium release takes the value `[45, 67.5, 67.49999999999997, 90]`

**Comment by hpinkos** [comment]
@ollazarev what you're seeing is a floating point precision issue.  This is a side effect of how decimal numbers are represented in binary on the computer.  There can be very small rounding errors because not every decimal number can be represented exactly in binary.  For an example of this, type `0.1 + 0.2` in your console.  The result will be `0.30000000000000004` instead of `0.3`.  Since the error is so small, it can usually be ignored.
