### ISSUE TITLE
 How to achieve the wind field？

### ISSUE THREAD

**Issue by xyjwyq** [AnalyticalGraphicsInc/cesium#6800]
Excuse me , How to achieve the wind field? thanks!

**Comment by likangning93** [comment]
Hi @xyjwyq,

Do you mean something like the WebGL wind map from [this blog post](https://blog.mapbox.com/how-i-built-a-wind-map-with-webgl-b63022b5537f)? We don't have wind fields built into Cesium, but it may be possible to implement it yourself using custom shader materials for a `Primitive` that wraps around the Earth. I almost want to try this myself now... if you end up implementing this we'd love to see it!

Also, for future reference, we prefer you ask questions over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev), since more people from the community can chime in on your questions. Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!
