### ISSUE TITLE
怎么导出图片png，像截图一样的效果？

### ISSUE THREAD

**Issue by Short-and-fast-cache** [AnalyticalGraphicsInc/cesium#6807]
怎么导出图片png，像截图一样的效果？
charts.canvas.toDataURL("image/png") 得到的图片是空白的黑色背景

**Comment by hpinkos** [comment]
Hi @Short-and-fast-cache, sorry I don't understand Chinese but from a rough translation it sounds like you're trying to capture the Cesium canvas in an image.

`toDataUrl` only works reliably from inside of the `postRender` call because the frame can be cleared at any time after `postRender` is done.  Try something like this:

```js
var removePostRender = scene.postRender.addEventListener(function () {
    removePostRender();
    var image = canvas.toDataURL("image/png")
}); 
```

**Comment by xuetao72** [comment]
Thankes @hpinkos ！ I succeeded，after trying your above example.
