### ISSUE TITLE
Issue on Billboards and Labels on Terrain Improvements

### ISSUE THREAD

**Issue by onderaltintas** [AnalyticalGraphicsInc/cesium#6917]
Hello, 

I liek cesium so much. Right now I have an issue about billboards and labels' partial visibility (some parts are visible some are not)

Version: 1.48 using npm package.
Browser: chrome

As it was mentioned in blog post I was expecting labels and billboards will be totally visible if any part of them are visible on the terrain. Related blog post:
https://cesium.com/blog/2018/07/30/billboards-on-terrain-improvements/

It works partly. When camera is near to the billboards (around 700 or such meters) this check works. When camera is further away from the billboards and labels, again billboards and labels becomes half, %25, %35 or such.

![problem](https://user-images.githubusercontent.com/4962955/44094878-004e8774-9fe0-11e8-83c8-194546d98f76.PNG)

Test case in yer cesium sandcastle:
1- use the codes
2- zoom in zoom out, move camera
```
var viewer = new Cesium.Viewer('cesiumContainer');
var terrainProvider = viewer.terrainProvider;
viewer.terrainProvider = Cesium.createWorldTerrain();
viewer.scene.globe.depthTestAgainstTerrain = true;
    
viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-122.1958, 46.1915),
    billboard : {
        image : '../images/facility.gif',
        heightReference : Cesium.HeightReference.CLAMP_TO_GROUND
    }
});
    
viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-122.1958, 46.1915),
    label : {
        text : 'Philadelphia',
        heightReference : Cesium.HeightReference.CLAMP_TO_GROUND
    }
});
viewer.zoomTo(viewer.entities);

```

**Comment by hpinkos** [comment]
Hello @onderaltintas, this is by design.  We do the better depth test against terrain check only when the camera is within some distance of the billboard, otherwise there could be a slight impact to performance if there were a large number of billboards all over the globe.  However, the distance at which this happens is configurable using the `disableDepthTestDistance` property.  It's set at 5000 by default.  If you pass in a larger number it will start doing that check when the camera is zoomed out further.  This value can be set to `Number.POSITIVE_INFINITY` to always perform this check, but that can sometimes cause the billboard to show through the globe if one of the edges is visible from behind the globe.

```js
var viewer = new Cesium.Viewer('cesiumContainer');
var terrainProvider = viewer.terrainProvider;
viewer.terrainProvider = Cesium.createWorldTerrain();
viewer.scene.globe.depthTestAgainstTerrain = true;
    
viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-122.1958, 46.1915),
    billboard : {
        image : '../images/facility.gif',
        heightReference : Cesium.HeightReference.CLAMP_TO_GROUND,
        disableDepthTestDistance: 15000
    }
});
    
viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-122.1958, 46.1915),
    label : {
        text : 'Philadelphia',
        heightReference : Cesium.HeightReference.CLAMP_TO_GROUND,
        disableDepthTestDistance: 15000
    }
});
viewer.zoomTo(viewer.entities);
```
