### ISSUE TITLE
Loading GLTF crushes browser, Loading GLB loads root

### ISSUE THREAD

**Issue by AmitMY** [AnalyticalGraphicsInc/cesium#7001]
I am trying to load a `gltf` file (around 75MB) to cesium, but when I do:
```js
var model = viewer.scene.primitives.add(Cesium.Model.fromGltf({
    url: 'data/example.gltf',
    modelMatrix: modelMatrix,
    scale: 1.0
  }));
```
The browser tab crushes (stuck for hours, have to manually close) at the moment I am in a position where the model should be visible.

I converted it to GLB using `gltf-pipeline`, and just change the URL to `data/example.glb`.
Now the console reports:
> GET http://localhost:3000/data/ 404 (Not Found)

And nothing shows.
Why does it call the root directory of the glb file?

**Comment by AmitMY** [comment]
Unfortunately, no.

**Comment by hpinkos** [comment]
Sorry, I'm not sure what all we can do to help.  I think Cesium should be able to load a 75MB model, but it's possible the size is causing your browser to run out of memory.  Our team primarily uses Chrome because it seems to have the best performance, so you can try that if you're not using Chrome already.

It's also possible your GLTF didn't convert correctly and that's what's causing it to now display.  You can try debugging it in VS code using the VS code plugin: https://github.com/AnalyticalGraphicsInc/gltf-vscode

You can also try converting the model again.  You might have better luck if you convert your source model directly to `glb` instead of converting it to gltf then to glb.
https://github.com/KhronosGroup/COLLADA2GLTF
https://github.com/AnalyticalGraphicsInc/obj2gltf

Here's a code example for loading one of our glb models.  I don't see it calling the root in the console.  Your model might be trying to find some external texture files that aren't included in the glb.

```js
var viewer = new Cesium.Viewer('cesiumContainer', {
    shadows : true,
    shouldAnimate : true
});

var entity = viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-123.0744619, 44.0503706, 5000),
    model : {
        uri : '../../../../Apps/SampleData/models/CesiumAir/Cesium_Air.glb'
    }
});
```

If you're still having trouble, I would recommend posting on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
More people see the forum and may have experienced similar problems and have suggestions for how to help.  Our team also monitors the forum to make sure all questions get answered.  We use GitHub exclusively for tracking bugs and planning new features, so the forum is a better place to ask something like this.

Thanks!  Hope you're able to track down the problem.
