### ISSUE TITLE
sampleHeight bug

### ISSUE THREAD

**Issue by hieeyh** [AnalyticalGraphicsInc/cesium#7120]
code:
let cartographicPosition = new Cesium.Cartographic()
cartographicPosition.longitude = mapUtil.angleToRadian(113.939499)
cartographicPosition.latitude = mapUtil.angleToRadian(22.5262237)
let takeOffheight = scene.sampleHeight(cartographicPosition)

result:
TypeError: Cannot read property 'x' of undefined
    at n (Cesium.js:445)
    at Function.s.fromCartesian (Cesium.js:445)
    at we.sampleHeight (Cesium.js:526)

**Comment by lilleyse** [comment]
Hi @hieeyh

What happens when you click "Sample height" and "Sample height supported" in this demo?

[Demo](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=lZJPT8JAEMW/yqYXSmK2ofgnxIJGLh40GDGeehm3Q7th2SW70xo0fnd3WyEgxMTeZub93sy+tAHLGonvaNmYaXxnU3SyXvHXthf3RFtOjSaQGm2vf53rxjNOoEaPdCxvSz/K9Rx0IcCRQg5F8WKMegN7VxMZHffmsForZBXKsqLeGVvUWpD0kz77zDXzX/AWYMmUFtaVFE/GyaA4vG66p4jDSQE9hXFldCmpLsKtP/AjUMXJPEMhQbt4MBjy0XB0Phr9bQT0t0+a8ov0Mk2HV1uf8BaCJc4Wi+7Fnm2D4q7N4b5txqfW7U4x2hkfpTJlfGAVBF/9fybOXL1eG0tY3JwMf3/b8aHzLbzbHZ1FmaONwknH38pVULDaqpjzhNDDQOiSt1oskbhwLmBZsoWyQjZMFuM8+vWf5RETCpzzk0Wt1Fx+YB5NssTrDzBlfPq6nDVoFWyCpBpMHrom5zxLfHlMUZfRnuM3)

It's possible that `sampleHeight` isn't supported on your setup. [`sampleHeightSupported`](https://cesiumjs.org/Cesium/Build/Documentation/Scene.html?classFilter=scene#sampleHeightSupported) would be the first thing to check.

**Comment by hieeyh** [comment]
> Hi @hieeyh
> 
> What happens when you click "Sample height" and "Sample height supported" in this demo?
> 
> [Demo](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=lZJPT8JAEMW/yqYXSmK2ofgnxIJGLh40GDGeehm3Q7th2SW70xo0fnd3WyEgxMTeZub93sy+tAHLGonvaNmYaXxnU3SyXvHXthf3RFtOjSaQGm2vf53rxjNOoEaPdCxvSz/K9Rx0IcCRQg5F8WKMegN7VxMZHffmsForZBXKsqLeGVvUWpD0kz77zDXzX/AWYMmUFtaVFE/GyaA4vG66p4jDSQE9hXFldCmpLsKtP/AjUMXJPEMhQbt4MBjy0XB0Phr9bQT0t0+a8ov0Mk2HV1uf8BaCJc4Wi+7Fnm2D4q7N4b5txqfW7U4x2hkfpTJlfGAVBF/9fybOXL1eG0tY3JwMf3/b8aHzLbzbHZ1FmaONwknH38pVULDaqpjzhNDDQOiSt1oskbhwLmBZsoWyQjZMFuM8+vWf5RETCpzzk0Wt1Fx+YB5NssTrDzBlfPq6nDVoFWyCpBpMHrom5zxLfHlMUZfRnuM3)
> 
> It's possible that `sampleHeight` isn't supported on your setup. [`sampleHeightSupported`](https://cesiumjs.org/Cesium/Build/Documentation/Scene.html?classFilter=scene#sampleHeightSupported) would be the first thing to check.

If theris a 2D billboard, it will report this error. But if exclude this 2D billboard, sometimes success, sometimes fail.

**Comment by lilleyse** [comment]
The example I posted should now work in #7115.

[Example on offscreen-picking branch](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/offscreen-picking/Apps/Sandcastle/index.html#c=fVNtb9owEP4rHl8IEjPhna0UTaOdioSgKlGnSpEm4xhizbEj24HRqf99F5vQtJXGB+Tn7p57ee5yIBodODsyja6RZEc0Z4YXGX50tqBJHZwraQmXTDdbV7E8AMdQJhlQPBc7CK5Y8h0KPjmIDclywe4Y36d2U+S50pYlLfQ3lgh+VEmjBMNC7YNmlHKDtlodDTSSKGaQVBYZT0L1RNi18FKWKvsQSu65LZKyl8893B1MwuFgOBn2xsN+d9Q/dyuIrYJCPB5NJr1BGPZHX/rjbti9qnJRoq3aa5KnnL5VY17zBJeS7UveSpVcGW65ksCuMeFFZB/vtMoeSAJv878cTAI+vUrrMGcGkyQJztpd6ny9PNuVh0sL5nOgM/E/TGz4MwNzL2y/OqgSSoOxarWE+Ol2uVz/rEUl3JCtYDcst2nEjL3hxhJJy2yrIttCh/frzSJaPN7+Wqx+LFaL6MmTYUcvLS+un+RZqSxSgR/QezZEJpQYC3cA40VKiS3R3wtrlQyaG7d2lLq9N9toV0hajhpcbqjUy7tBr49HF9Q3WhZ8f3ee6w6q/Gu0G1NjT4LNfOg3nrn7K7QIMO5YBqkJrLOzLehvZjE1pqRNOxVpmvAD4sl13Hj33cQNRAUxBjy7QrhtxI3ZtAPxb2hCwYHI/frAtCCnMiTtzpbeiDGedgB+ZFmvWy3jPw)

@hieeyh if you have a chance would you mind testing your app with this build to see if it fixed your problem?

A link to download the build is here: http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/offscreen-picking/Cesium-1.49.0-offscreen-picking29051.zip
