### ISSUE TITLE
Detailed Terrain Disappears from Foreground

### ISSUE THREAD

**Issue by bbehling-trimble** [AnalyticalGraphicsInc/cesium#7125]
When zooming in, shadows or detailed terrain (not sure which one it is) disappears from foreground when showing Bing roads, OSM, or a layer that is not imagery.

These screen shots are from the Terrain Sandcastle example.
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Terrain.html&label=All

 Image showing the detailed terrain.

![screen shot 2018-10-09 at 12 01 34 pm](https://user-images.githubusercontent.com/43279306/46688764-6a725200-cbbb-11e8-9c6a-78651fd34d32.png)

Zoom in a very little bit, notice the detail disappears.

![screen shot 2018-10-09 at 12 01 12 pm](https://user-images.githubusercontent.com/43279306/46688812-9097f200-cbbb-11e8-88b4-b984ad62f73d.png)

 Some more examples

![screen shot 2018-10-09 at 12 02 06 pm](https://user-images.githubusercontent.com/43279306/46688834-9db4e100-cbbb-11e8-9338-4e629418c598.png)

![screen shot 2018-10-09 at 12 01 50 pm](https://user-images.githubusercontent.com/43279306/46688908-cccb5280-cbbb-11e8-9409-e6eb9f4d0640.png)

**Comment by hpinkos** [comment]
Hello @bbehling-trimble, I believe what you are seeing are changes in the level of detail of imagery tiles loaded in.  If you look at the Bing Maps Roads imagery using the `EllipsoidTerrainProvider` it has some mountainy looking shading:

![image](https://user-images.githubusercontent.com/3451886/46689673-6e5b9f80-cbce-11e8-8882-265bce95497d.png)

I could not reproduce this with the Natrual Earth imagery which does not have the same shading effect in the imagery in that area.

**Comment by bbehling-trimble** [comment]
@hpinkos I don't believe this should be closed.

I used the bing road view and osm map tiles with various terrain providers and can reproduce the issue.

What should be happening is the detail should disappear from the tiles in the background, not the foreground. Current behavior seems backwards.

**Comment by mramato** [comment]
@bbehling-trimble To further elaborate on what @hpinkos was saying, the problem is that Bing Roads has built-in shading for lower levels of detail, but does not have any shading at the higher levels.  When there is no shading, you have to have lighting enabled in order to see any definition. 

Lighting disabled, terrain disabled, around Everest, slightly zoomed out:

![image](https://user-images.githubusercontent.com/1495196/46693243-458bd800-cbd7-11e8-9d42-43c65e1be7e0.png)

Lighting disabled, terrain disabled, around Everest, zoomed in further:

![image](https://user-images.githubusercontent.com/1495196/46693282-589ea800-cbd7-11e8-9ef1-eff015ec6d85.png)

So the above images are simply what the imagery looks like at different levels.

The problem you are seeing in a horizon view is that areas closer to the camera have higher level of detail tiles loaded (as they should), however for Bing Roads this means we end up with unshaded imagery.  This is a Bing data problem but the best way to mitigate it in Cesium is to enable lighting.

Unshaded high LOD tiles, with and without lighting.

![peek 2018-10-09 15-34](https://user-images.githubusercontent.com/1495196/46693806-e038e680-cbd8-11e8-920d-358aca4b4d32.gif)

I hope this helps understand the issue.

**Comment by bbehling-trimble** [comment]
@mramato Thanks for reply, but really doesn't explain why an area in the foreground has the shading, while another area in the background, or even next to it at the same zoom level, does not have shading. 

Like this screen shot. These areas are right next to other.

![screen shot 2018-10-09 at 12 01 50 pm](https://user-images.githubusercontent.com/43279306/46697252-70732d80-cbd1-11e8-8e5c-180374177a40.png)

**Comment by mramato** [comment]
@bbehling-trimble Your arrows are pointing to two different tiles.  The "Shading" one is a zoom level 12 tile, while the "No Shading" one is a zoom level 13 tile (the level at which Bing stops shading).  Because Cesium is a 3D engine, zoom level is not constant across a view and areas further away from the camera use lower zoom levels.

I tried to recreate your view and added `TileCoordinatesImageryProvider` to the scene. Notice the shading/no shading happens at the boundary between higher zoom tiles and lower zoom tiles (The yellow line running down the mountain)

![image](https://user-images.githubusercontent.com/1495196/46698065-2182c380-cbe4-11e8-9c9b-75e0701c655b.png)

**Comment by mramato** [comment]
I'm not sure what you mean by tighter calculation, it's based on the amount of geometric error so we fetch the ideal tiles for a given view.  The crux of the problem here is that Bing Roads provides radically different tiles between levels 12 and 13.  If their data was consistent, you wouldn't notice the difference in shading.  I would suggest either turning on lighting in Cesium to mitigate the issue or switching to a different imagery provider.

Another option you can play with is the [scene.globe.maximumScreenSpaceError](https://cesiumjs.org/Cesium/Build/Documentation/Globe.html#maximumScreenSpaceError) setting, which will control the resolution of tiles being loaded.  The default is 2, lowering the value will cause more high resolution tiles to be requested, increasing the value will cause it to show lower resolution tiles for longer.  I'm not sure tweaking this value will have the affect you want though.

A final solution would be to tell Cesium to ignore all tiles greater than level 12, which would mean you permanently stay on the lower resolution tiles even when higher res data is available, but it will provide you consistent shading.  You can do that by passing the `maximumTerrainLevel` option with a value of 12 when constructing the layer.

**Comment by bbehling-trimble** [comment]
@mramato I guess this discussion isn't so much a discussion about map services anymore, but about calculating zoom levels for tiles that appear to be directly next to other. 

I compared behaviors between OSM and Map Box. OSM does not have shading. Mapbox has shading, but this issue doesn't happen. 

So now, looking at the screen grab above, I think it's quite clear that there are tiles that appear to be neighboring tiles in the same zoom level. There even appears to be a line split right down the middle. So what I'm asking is, whatever algorithm calculates the zoom level, can't it be 'tightened' up so what we see above wouldn't occur?

Maybe I'm just having a difficult time to trying to explain the issue and a possible solution.

**Comment by lilleyse** [comment]
@bbehling-trimble I think cases like this are just inevitable since distance from tile is used as part of the metric from converting geometric error to screen space error. The unshaded area seems to be close enough that it is a different zoom level than its neighbors. These are the relevant areas in the code:

Screen space error calculation: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/QuadtreePrimitive.js#L694-L712

Distance computation: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/TileBoundingRegion.js#L249-L316

I'm not totally sure what would need to change to improve the results. Maybe a planar distance instead of a point-to-point distance, if I'm reading `TileBoundingRegion` correctly. But I sense that there will always be some sort of seam between the shaded and unshaded sections.

I checked out Mapbox and it seems like it has shaded tiles in all its zoom levels, so the problem isn't noticeable.
