### ISSUE TITLE
Can the Cesium add the DEM service published by arcgis?

### ISSUE THREAD

**Issue by RemoteSensingFrank** [AnalyticalGraphicsInc/cesium#7146]
I want add the DEM service published by arcgis. I want to know the method to add DEM layer. I tried all the API about 
![image](https://user-images.githubusercontent.com/25923674/46935371-8bd8af80-d08d-11e8-9b21-a6eb3ee65f32.png)but did not work. My code is like:
var viewer = new Cesium.Viewer('cesiumContainer', {
    imageryProvider : new Cesium.ArcGisMapServerImageryProvider({
        url : 'https://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer'
    }),
    terrainProvider : new Cesium.CesiumTerrainProvider({
        url : 'http://kn-gis-43.gedi.net:6080/arcgis/rest/services/HKDEM/ImageServer',
        requestVertexNormals : true
    }),
    baseLayerPicker : false
});

**Comment by hpinkos** [comment]
Hello @RemoteSensingFrank,  the `CesiumTerrainProvider` is only compatible with heightmap and quantized mesh terrain tiles (see https://cesiumjs.org/data-and-assets/terrain/formats/)

CesiumJS does not have an ArcGis compatible terrain provider because ArcGis Image Server does not output terrain tiles in a web friendly format.  This is something we might look into soon, but in the meantime you can try tiling your terrain data on Cesium ion.  See more at https://cesium.com/

Thanks!

**Comment by RemoteSensingFrank** [comment]
Ok，thanks a lot
