### ISSUE TITLE
Bug that causes browser crash

### ISSUE THREAD

**Issue by githubhanjunjun** [AnalyticalGraphicsInc/cesium#7198]
cesium 1.47
windows 10
Chrome
![image](https://user-images.githubusercontent.com/27795864/47631868-c0b32f00-db82-11e8-833a-945f1e0ae3a5.png)

**Comment by hpinkos** [comment]
@githubhanjunjun can you create a reproducible code example in [Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/)?

**Comment by hpinkos** [comment]
@githubhanjunjun I'm going to close this issue since we haven't heard from you.  I would recommend asking questions on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
The forum is visible to many more people so it is more likely that someone will be able to help.  Our team also monitors the forum.

Otherwise, feel free to comment on this issue if you have a code example that reproduces the problem so we can take a further look at this.  Thanks!
