### ISSUE TITLE
Flickery polygon on mouse over

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#7223]
There's a bit of flickering when hovering over an entity and changing its color. It's much easier to see when running the demo, the gif only does an ok job.

Git bisect leads to https://github.com/AnalyticalGraphicsInc/cesium/commit/8ba647bf8bf850c3c72ebe1afedf4c4e601a38db / https://github.com/AnalyticalGraphicsInc/cesium/pull/7163. @hpinkos could you check this out?

[Local example](http://localhost:8080/Apps/Sandcastle/index.html#c=dVNdb9MwFP0rVh+2RMrcTmXqYE0FlCCQOjKt+xBSJOTGt5vBsSPbySjT/js3cdqmQ/jJPr7nnHuPk5oZUgt4AkNiouCJzMGKqqB3LRYc5+1xrpVjQoE5jshzpgguB8YgdGV0LTiYd1tiboA5uNdG8htfEoSZegkvMlWjl81BAVp5T9oe8cpfgnLCbfa37VmApYzzoPMttUVMK7JznDPjcMfUmK6NLj7BgwGwwcnkjJ69nUwmEXkzoqPx+fk4jLzGSv9GeifYLC4KUBZVLeK9FPbSwemoXXQUkd527Ddb4WYVOL4RTPYa1FIbOk+vv31epPfJ9cfFbeLrX7pk/PiPTHH5+iGWGCioZclySGoM5IsvCtrkaM6QaRuJjkwtuK+qrNyHvEkpWFfKbwpdAw7pwu3cjWMp8l/A09VPyB3aes0G3JXjG/CrLvLGpmGKNQm67jis8bPgQV8oJEdH5AChgpM4jrv3DcN+9B6j+CR0l1x8mNz3ZIG5Xewji/4Xzs2mBHqZ3i6TH5fpXdI0PIgGU+s2Emae/14UpTaOVEYGlA4dFKVEXztcVdiwo7lt45wOt6QpFzURPM4Gr/6FbEByyazFm3Ul5VL8gWwwmw6x/oAmNeNCPaQ1GMk2Tcnj6WzhQUrpdIjHf1lOa7lipqf4Fw)

![flickery](https://user-images.githubusercontent.com/915398/47873518-d2494080-dde7-11e8-81e7-656b740797f2.gif)

**Comment by hpinkos** [comment]
This turned out to be a bug in the sample code, not in Cesium.  However, there is a change in behavior for people who had this bug in their code because Cesium was doing something incorrect before that was fixed in #7163.

The reason for the flickering is that the box is being re-created every time you set the material.  This was the case before #7163 as well, but we made the mistake of not removing the previous box, so it didn't look like it was flickering because we accidentally had 2 copies of the box being drawn.

To change the color without flickering, you need to use a dynamic property for the color.  The example below uses a dynamic `CallbackProperty`:

``` js
var color = Cesium.Color.CORNFLOWERBLUE;
var colorProperty = new Cesium.CallbackProperty(function() {
    return color;
}, false);
var entity = viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883),
    box : {
        dimensions : new Cesium.Cartesian3(1000000.0, 1000000.0, 30000.0),
        material : new Cesium.ColorMaterialProperty(colorProperty)
    }
});

var handler = new Cesium.ScreenSpaceEventHandler(scene.canvas);
handler.setInputAction(function(movement) {
    var pickedObject = scene.pick(movement.endPosition);
    if (Cesium.defined(pickedObject) && (pickedObject.id === entity)) {
        color = Cesium.Color.YELLOW;
    } else {
        color = Cesium.Color.CORNFLOWERBLUE;
    }
}, Cesium.ScreenSpaceEventType.MOUSE_MOVE);
```
