### ISSUE TITLE
Map control switches from spinning to moving up and down when you drag to horizon

### ISSUE THREAD

**Issue by bmr74** [AnalyticalGraphicsInc/cesium#7232]
When looking a shallow pitch, with the horizon in view, at zoom level ~12, drag the mouse upward to spin the globe, the navigation switches from spinning the globe to pivoting around some point on the horizon.  The expected behavior is to keep spinning the globe.

Sandcastle: Hello World (or presumably any)
Browser: Chrome version 70.0.3538.67
Operating System: Windows 7

Commenting out the code below in spin3D (ScreenSpaceCameraController.js:1309) seems to yield the desired behavior.  If some really prefers this behavior, can an option flag be added to control it?

``
        if (defined(globe) && height < controller._minimumPickingTerrainHeight) {
            mousePos = pickGlobe(controller, movement.startPosition, scratchMousePos);
            if (defined(mousePos)) {
                var ray = camera.getPickRay(movement.startPosition, pickGlobeScratchRay);
                var normal = controller._ellipsoid.geodeticSurfaceNormal(mousePos);
                tangentPick = Math.abs(Cartesian3.dot(ray.direction, normal)) < 0.05;

//                if (tangentPick && !controller._looking) {
//                    controller._rotating = false;
//                    controller._strafing = true;
//                }
            }
        }
``

**Comment by hpinkos** [comment]
@bmr74 I'm pretty sure the behavior you're seeing is intentional.  When you click and drag on the sky, we change the camera behavior to allow the user to look up and down.  This is helpful for adjusting the camera to view terrain features or features of 3D Tilesets when the camera is in a horizon view.

If you think what you are seeing is different than what I'm describing, feel free to reopen this issue.  It would be helpful if you could share a short video of the behavior you're seeing.

Thanks!

**Comment by bmr74** [comment]
Thanks for the prompt reply!  To clarify: when you click the sky, the pivot point appears to be the camera.  But in this case the pivot point is the horizon(?).  Maybe it's intentional, but if it is, it would be nice to have a feature to turn it off.  I can't seem to attach a video, so I attempt to email it.

**Comment by bmr74** [comment]
Brandon Reynolds
IEWTPT Software Task Lead
General Dynamics Mission Systems
12001 Research Parkway, Suite 500 ● Orlando, FL  32826
Desk: (407) 281-5618
Email: brandon.reynolds@gd-ms.com<mailto:brandon.reynolds@gd-ms.com>

This message and/or attachments may include information subject to GD Corporate Policies 07-103 and 07-105 and is intended to be accessed only by authorized recipients.  Use, storage and transmission are governed by General Dynamics and its policies. Contractual restrictions apply to third parties.  Recipients should refer to the policies or contract to determine proper handling.  Unauthorized review, use, disclosure or distribution is prohibited.  If you are not an intended recipient, please contact the sender and destroy all copies of the original message.

**Comment by hpinkos** [comment]
Ohhh, I see what you're talking about @bmr74.  No need to send a video.

Yes, that behavior is intentional as well.  Otherwise if you clicked too far into the distance and started to drag it would zoom the camera really fast and far away from your current position.  We found people did this more often by accident than on purpose.  We actually have a PR open to make that panning camera movement even more minimal than it is now when the camera is close to the ground: https://github.com/AnalyticalGraphicsInc/cesium/pull/7057

**Comment by hpinkos** [comment]
I'm not sure if we have a way to configure that though if you wanted to disable it. @bagnell?
