### ISSUE TITLE
event-stream npm/node disaster fallout

### ISSUE THREAD

**Issue by nmccready** [AnalyticalGraphicsInc/cesium#7291]
This is to bring attention to any possible developers that could be building AGI cesium library locally.

As `event-stream@^3.3.4` is a direct `developerDependency` for everything except latest on master. I am bringing this up as there has yet to be an announcement regarding this security breach for this repo.

This is regards to [event-stream malware (npm link)](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident)

For more detail see: https://schneid.io/blog/event-stream-vulnerability-explained/ . 

From my initial digging 1.48, 1.49, 1.50 and 1.51 and probably more are at risk.

Please put a notification somewhere in the README and elevate the issue at hand.

Referencing other tickets:

https://github.com/dominictarr/event-stream/issues/115

https://github.com/dominictarr/event-stream/issues/116

Master fix:

https://github.com/AnalyticalGraphicsInc/cesium/blame/master/package.json#L44

**Comment by hpinkos** [comment]
Thanks for bringing this to our attention @nmccready.  We were made aware of this issue yesterday, but since we've already updated the dependency to the latest version of `event-stream` in master, I'm not sure if there's any further action we need to take here.  Do you have any recommendations?

**Comment by nmccready** [comment]
I am not really sure how to proceed as this library is extremely unique in that many are encouraged to either use the raw build or compile the existing source (webpack, rollup etc).

The latter (compiling source) is where I am worried where a developer is just trying to get the library to work and this puts the said malware on their machine. 

A notice to clear out your cache and artifactory repos also should be sufficient as the offending event-stream version is gone from npm.

Here is an example of one such [project](https://github.com/nmccready/cesium-webpack-config/blob/master/src/index.js), but it does not call or run cesiums developerDependencies directly.

**Comment by hpinkos** [comment]
@pjcozzi thoughts?

**Comment by mramato** [comment]
@nmccready thanks for bringing this up.

Just to clear up any possible confusion for everyone:

* While `event-stream` is a developer dependency used in our build tasks, it is not part of the actual Cesium code base; i.e. building and distributing a Cesium application will not include event-stream's code or dependencies.

* Because it is a devDependency, depending on the `cesium` module in npm would not include `event-stream` (through Cesium). i.e. `npm install --save cesium` would not install the malware.

* Since the dependency itself does not ship with Cesium, past releases are unaffected since the bad packages have already been purged from the npm server. Unzipping 1.48 and running `npm install` will not install the malware.

So in order to have been affected by this attach via Cesium a user would have needed to:

1. Be a Copay user
2. Downloaded or cloned Cesium while the malicious package was available
3. Ran `npm install` from inside of Cesium's root directory to install Cesium's developer dependencies.

 I hope this answers any questions anyone might have, but please continue to use this issue for further discussion and clarification.

Thanks
