### ISSUE TITLE
Add polygon error when use cesium with excel-export.

### ISSUE THREAD

**Issue by dminor112** [AnalyticalGraphicsInc/cesium#7439]
When I import Nodejs module excel-export, cesium add polygon will occur an error.
![image](https://user-images.githubusercontent.com/7435641/50396356-935eb800-07a4-11e9-8ad3-1c03dc6d0180.png)

My code:
```
import excelExport from 'excel-export'
var viewer = new Cesium.Viewer('cesiumContainer');
let polygon = viewer.entities.add({
    name: 'area polygon',
    polygon: {
        hierarchy: [new Cesium.Cartesian3(2000,1789,2000), new Cesium.Cartesian3(2000,1799,2000), new Cesium.Cartesian3(2000,1789,2050)],
        perPositionHeight: true,
        material: Cesium.Color.fromCssColorString('rgba(217, 48, 53, 1.0)'),
        outline: true,
        outlineColor: Cesium.Color.fromCssColorString('rgba(217, 48, 53, 1.0)'),
        outlineWidth: 2
    }
})
```
cesium version: 1.50
browser: electron

**Comment by OmarShehata** [comment]
This is strange. Does that code work if you remove the first line? 

The only thing is that this polygon happens to be under the surface I think. If you set a height instead of perPositionHeight and use `viewer.zoomTo` you can see it. [Here's a live Sandcastle](https://cesiumjs.org/releases/1.50/Apps/Sandcastle/index.html#c=rVJNT9wwEP0ro1ySSJaTLEVACKtKe+kBiUpU5dBw8CbDxqpjr8ZO0FLx3+t8bAkgIQ71yfPmvTczHveCoJf4iARXoPERNmhl1/KfIxaF1RhujHZCaqQwvix17zV7ow47o71oUnPUTjqJlou6jv6UGvzRosUcQkEojoKQTak5zGGmDqeRSIKq5pDDr0UrG0HO34Q+iVZpmrLs7PyCDbeYwYe0i8/RRrfTNL5nL60kyR7pu7F+JKO/odw1LgdHHS44zQxn6QJshUOSQuX/6hlliD+QaTfWjsGtI6l3UUi7rYhW2RmDL+cMTk8YZDyNw3jhZjqn/LO/Kz3jo91/rXQna9fksJoSz6V+HhbuVz4t+cmY9oeJ5uXFlwELCusOCteT4Kts94YcdKQizhOH7V75B7HJtqt+o+OVtYNfkRxFRS17kPVVGbz5aGUAlRLW+sxDp9StfMIyWBeJ57+SKSNqP+NNj6TEYaA02fp6AjnnReLD9ypnjNoKWjj+BQ).

If you can provide more information it would be helpful. Running the unminified version of CesiumJS and posting the full error message here would help a lot too.

**Comment by hpinkos** [comment]
no longer crashes
