### ISSUE TITLE
How to use Polyline in cesium version 1.52.0 to connect points with Rhumb lines?

### ISSUE THREAD

**Issue by dasseya1** [AnalyticalGraphicsInc/cesium#7547]
I am currently using Cesium version 1.52.0 and cannot upgrade at this time. But My goal is to show the polyline is rhumb format on the map . In version 1.54.0, arcType: Cesium.ArcType.RHUMB is the property to get rhumb lines. How can I achieve the same result with version 1.52.0?

THIS IS WHAT I WANT TO ACHIEVE (Cesium version 1.54.0)
var viewer = new Cesium.Viewer("cesiumContainer" );

viewer.entities.add({
    polyline: {
        positions: Cesium.Cartesian3.fromDegreesArrayHeights([-112.3268785,29.1673139,1000,139.1652182,9.6235915,1000,11.4423255,50.0235941,1000,-41.2873034,-5.1132736,1000]),
        width: 8,
        arcType: Cesium.ArcType.RHUMB,
        material: new Cesium.PolylineOutlineMaterialProperty({
            color: Cesium.Color.YELLOW,
            outlineWidth: 4,
            outlineColor: Cesium.Color.BLACK
        })
    }
});

**Comment by hpinkos** [comment]
Hello @dasseya1, Rhumb line support was added in 1.54 and there is not a way to achieve the same result in 1.52.  If you can't upgrade, the only workaround I can think of would be to write a function to compute the subdivision of the polyline positions before you pass them in to create the polyline.  For example, you would pass in 
`positions: Cesium.Cartesain3.fromDegreesArray([-112, 30, -111, 30, -110, 30, -109, 30, -108, 30]) `
instead of 
`positions: Cesium.Cartesain3.fromDegreesArray([-112, 30, -108, 30]) `

In the future, if you have questions like this please ask them on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for planning new features and tracking bugs.  Thanks!
