### ISSUE TITLE
Getting the mouse position incorrectly

### ISSUE THREAD

**Issue by XBC125905** [AnalyticalGraphicsInc/cesium#7602]
Getting the mouse position incorrectly with billboad's heightReference  Cesium.HeightReference.CLAMP_TO_GROUND.
[Test Demo with Sandcastle.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/2913181/Text.Demo.with.Sandcastle.txt)

![1](https://user-images.githubusercontent.com/17061454/53538472-bad95480-3b48-11e9-9213-de7c755269c7.jpg)
![2](https://user-images.githubusercontent.com/17061454/53538473-bad95480-3b48-11e9-9d83-f772c323df2d.jpg)

![uhsxm-u5wap](https://user-images.githubusercontent.com/17061454/53538437-967d7800-3b48-11e9-93a8-0f44648bba59.gif)

**Comment by OmarShehata** [comment]
I think when you're not using terrain `viewer.camera.pickEllipsoid` will give you a more accurate position. See this forum thread for a discussion and examples on that:

https://groups.google.com/d/msg/cesium-dev/mwW1mQ7kKgw/iyLWMmFlGQAJ

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/mwW1mQ7kKgw/iyLWMmFlGQAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/7602 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Comment by XBC125905** [comment]
@cesium-concierge @OmarShehata  I'm not using terrain <code>viewer.camera.pickEllipsoid</code> give me a accurate position,but when I'm using terrain <code>viewer.scene.pickPosition</code> give me a inaccurate position.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17061454/54103553-d0cbfc80-4407-11e9-8fbd-55ec2a79ede2.gif)
Here's my test code(can run in Sandcastle) :
<code>
var viewer = new Cesium.Viewer('cesiumContainer');

viewer.scene.globe.depthTestAgainstTerrain=true;
viewer.cesiumWidget.screenSpaceEventHandler.removeInputAction(Cesium.ScreenSpaceEventType.LEFT_DOUBLE_CLICK);
viewer.cesiumWidget.screenSpaceEventHandler.removeInputAction(Cesium.ScreenSpaceEventType.LEFT_CLICK);

viewer.camera.setView({
    destination : Cesium.Cartesian3.fromDegrees(102.4015231617376,25.098599524525778,2055.187396666107),
    orientation: {
        heading : Cesium.Math.toRadians(29.5733956517178), // east, default value is 0.0 (north)
        pitch : Cesium.Math.toRadians(-20.04812063948662),    // default value (looking down)
        roll : Cesium.Math.toRadians(0.07756279328150492)                             // default value
    }
});

function CustomLine() {    
    this.positions=[];
    this.markers=[];

    var that=this;

    this.line=viewer.entities.add({
        polyline : {
            // This callback updates positions each frame.
            positions : new Cesium.CallbackProperty(function(time, result) {
                return that.positions;
            }, false),
            width : 3,
            clampToGround:true,
            material : Cesium.Color.YELLOW
        }
    });
}


CustomLine.prototype.addPoint=function (position) {
    var that=this;
    var n=this.positions.length;
    this.positions[n]=position;
    var pinBuilder = new Cesium.PinBuilder();

    var marker=viewer.entities.add({
        position : new Cesium.CallbackProperty(function(time, result) {
            return that.positions[n];
        }, false),
        billboard : {
            image : pinBuilder.fromText(n+1, Cesium.Color.RED, 48).toDataURL(),
            heightReference:Cesium.HeightReference.CLAMP_TO_GROUND,
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

    this.markers.push(marker);
};
CustomLine.prototype.removeAll=function () {
    for(var i=0;i<this.markers.length;i++){
        viewer.entities.remove(this.markers[i]);
    }

    this.markers=[];
    this.positions=[];
};

var customLine=new CustomLine();
var drawing=false;

function getMousePosition(screenPosition){
     var pos;
     if(viewer.terrainProvider instanceof Cesium.EllipsoidTerrainProvider){
        pos=viewer.camera.pickEllipsoid(screenPosition);
     }else {
        pos=viewer.scene.pickPosition(screenPosition);
     }

    return pos;
}

var handler = new Cesium.ScreenSpaceEventHandler(viewer.canvas);
handler.setInputAction(function(event) {
    if(!drawing){
        return;
    }    
    var mousePosition = getMousePosition(event.position);
    
    if (Cesium.defined(mousePosition)) {
        customLine.addPoint(mousePosition);
    }
}, Cesium.ScreenSpaceEventType.LEFT_CLICK);

handler.setInputAction(function(event) {    
        if(!drawing){
            return;
        }
    var mousePosition = getMousePosition(event.endPosition);
    
    if (Cesium.defined(mousePosition)) {        
        var n=customLine.positions.length;
        if(n===0){
            customLine.addPoint(mousePosition);
        }else {
            customLine.positions[n-1]=mousePosition;
        }
    }    
}, Cesium.ScreenSpaceEventType.MOUSE_MOVE);

handler.setInputAction(function(event) {
    if(!drawing){
        return;
    }

    drawing=false;    
}, Cesium.ScreenSpaceEventType.RIGHT_CLICK );


// setup alternative terrain providers
var ellipsoidProvider = new Cesium.EllipsoidTerrainProvider();

var worldTerrain = Cesium.createWorldTerrain({
    requestWaterMask: true,
    requestVertexNormals: true
});

Sandcastle.addToolbarMenu([{
    text : 'CesiumTerrainProvider - Cesium World Terrain',
    onselect : function() {
        viewer.terrainProvider = worldTerrain;
    }
}, {
    text : 'EllipsoidTerrainProvider',
    onselect : function() {
        viewer.terrainProvider = ellipsoidProvider;
    }
}], 'toolbar');

Sandcastle.addToolbarButton('StartDraw', function() {
    drawing=true;
    customLine.removeAll();
    
});
</code>

**Comment by OmarShehata** [comment]
@XBC125905 I think the formatting of the code got messed up when you pasted it here.

[Here is your Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=tVdtT+M4EP4rPr6QiK5bdvekW9qgg7YHaMu1agvoRBEyybSxcO3Iccpxq/73m7y/QJflXvKpmcw8M37m8djdME02HJ5AE4dIeCJ9CHm0pteJzdp3k9e+koZxCXq/Rb4tJMHHgNZommi14R7oozzQ1cAM3CgtvHnqYtkLubW7C7mQaSYauiCBroR6AOpBYPw5hOZkhb6hyYIcoyPoFhFpGTfcW4HBcA0gZwFzYbgBac6Z9AQ6aVirDVzIIDInruFKWllNs0bA/DkAOhr+Nr8fjK9OR8P7/uii/9X+/9MVecpMbA2a0RBMzLiVkeshH1yyGJQUzPaZNviLyU90qdV6ACtME1qHnY/0c4t8/Jketshhp9OhHbuVwijNMX0Cc5T3LX58YB6XqxL6khmfGjVFM5Oh9SXBIO02ARaaFpazZJEwZMNEBISHBL8TSyptfLtEDbhx/Z2YH77EkPggah3PEko9xuV46klW8LQSAuHiXN97mngpwLbQ3DKSSXdIPwqNWo9QxpZNvsVOmZJ9HtJAhTz2Cp3bu27Fvmb6EXRmTe0b3DLGZ8aJHQpr4i0Q3Mk6i8wjIoSUeZ5VIT9Q4jn2I7WWZCuZIwpxmRAPzH0kUeDhXgpJURz2AyleahQNrceWLkfVbdzPoHCbBqDNs5WzYRm+hhbRECJxdrOShH4wkZbJSkt2unW/bYssmQghF1z+PHHPxFL41LC7gq2DuTrTKpLeUbzFGw5rXK/mTFRUr4TS9I/haDS+KX23WZfjFm/jFixk2V4aaGWUiXcdcj9RXBqnUIGVr6VYdLOfuU06dWVQAXJl/O5rqrmVd07+UoEIuDyNuPCa03VS2C27pqtUbm9LKM30n/T61T7jeiqtfq3NDxyzKaa9lzrma7aK5V2uPhlYc/jTWPIAp1SttdPhoEU+/2LjrBgww66mI6spJx/4yjdTWIIG6cJRFn9eN9P+6ORycj8f359Nx1e/DxogG+SE49Yaa77ilbF6XbPT0/F8Pr58XWkv5wINotC30pdEi90dQkwPixMhKkosWrFU2oq7z51Ol/dq+Jnm+MGBXWG5qY8U3apG3vI7u1vMwl0Tbdf826ZnFNbkFqtxEq1Vhmg39fA0e8Lx7SQSKeL89JSs6372+lFqFYchhoYxbhYdn4vVA7ZQNMTRBX98af2UVVFlKVV2SUKxyVQUwiTfQw6p3UoCjjso+5amKbjJ+eRLkh/1ePIgFZ5Vg7Rre6wksJhGDfeywm2LvOcO8aMslWfdd9h6wdi/ZA2kN/kHxOWZK2JPZnGFxh0TOVubdByn01zYDzchWTSgkMluhMqU/HB459RwXnL3dlsvx1ez4f3l+Hr4vra+S/zZxbK2V1Oe36huenF2nqmOpPXNsD4XL4YiIXOuFB47+jQyBmvbnxm8pg4wDf5VKCouis3zZ7f7BrHFkLTydiS3uL3WXi80zwKOU+OvfB3g3ZNEWliUtg2sAxHfk9oPkfuIF3Y3TGZIr50H9Ty+IdxzFnuNvzOLvfhKEob4ZRkJMeN/wWLvuNdG/1qYUMmFeYxniGDPsYt/eDxKjZTSXhtfX0aZlJkK4t8) with terrain on.

When you say inaccurate results are you referring to the flickering that happens in your gif? I believe this is happening when the mouse picks the billboard instead of the terrain. (You can verify this by putting your mouse over one of the billboards that has already been placed).

@hpinkos I don't know if there's a good way to solve this with the public API. [Scene.pickPosition](https://cesiumjs.org/Cesium/Build/Documentation/Scene.html#pickPosition) doesn't have a way to ignore certain objects in the way [Scene.sampleHeightMostDetailed](https://cesiumjs.org/Cesium/Build/Documentation/Scene.html#sampleHeightMostDetailed) does. I seem to recall there was an issue open about adding a way to set a flag on an entity to say it isn't pick-able, but I can't find it.

**Comment by hpinkos** [comment]
@OmarShehata @XBC125905 I would recommend using `getPickRay` to pick terrain instead of using `pickPosition`.

```
        var ray = scene.camera.getPickRay(mousePosition);
        position = scene.globe.pick(ray, scene);
```

**Comment by XBC125905** [comment]
@hpinkos @OmarShehata  Please forgive my poor English. Using <code>scene.globe.pick</code> can solve my issue,but it referring to inaccurate results when I using 3D Tiles.Using <code>pickPosition</code> pick 3D Tiles can  referring to inaccurate results. so I must switch pick Method(<code>getPickRay</code>、<code>pickPosition</code>、<code>pickEllipsoid</code>),and I must  to decide whether there is a terrain or not,and I must  to decide whether there is a 3D Tiles or not.  Is there a good way to solve this?

**Comment by hpinkos** [comment]
@XBC125905 you'll want to do something like this:

```js
var pickedObject = scene.pick(mousePosition);
var position;
if (defined(pickedObject) && (pickedObject instanceof Cesium3DTileFeature || pickedObject.primitive instanceof Cesium3DTileset)) {
    scene.render();
    position = scene.pickPosition(mousePosition, cartesianScratch);
} else {
    var ray = scene.camera.getPickRay(mousePosition, rayScratch);
    position = scene.globe.pick(ray, scene, cartesianScratch);
}
```
