### ISSUE TITLE
Use cesium on react native

### ISSUE THREAD

**Issue by giantss** [AnalyticalGraphicsInc/cesium#7629]
Hello everyone:
Is there a successful case of using cesium on a react native? Our company recently wanted to use cesium to do all clients (PC browser, mobile app, mobile browser, etc.)
I need your help.

**Comment by hpinkos** [comment]
Hello @giantss, yes, Cesium works well with react.  See this guest blog post: https://cesium.com/blog/2018/03/05/integrating-cesium-and-react/

If you have any follow up questions, please post on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev
We use GitHub exclusively for tracking bugs and planning new features.  A lot more users see the forum so it's more likely you'll be able to strike up a conversation with someone who used react with their cesium app.

**Comment by sparsematrix** [comment]
This was closed with a less than useful answer. The cesium-react library, now called Resium, does not support React Native as Resium has a dependency on react-dom which is browser only. I believe the answer to the original question is no, there is no widely published successful case of using Cesium with React Native. Just trying to help save time of people like me who get their hopes up only to be dashed after wasting time. Just because something works with React does not mean it will work with React Native.

**Comment by OmarShehata** [comment]
@sparsematrix I have seen others publish apps with Cesium and React Native (I believe this is how this Satellite AR app was made: https://play.google.com/store/apps/details?id=com.agi.android.augmentedreality&hl=en_US). Although this was just embedding CesiumJS in a web view.

If you ran into specific issues it'd be great to share them here.

**Comment by itsezc** [comment]
@OmarShehata Do you have any benchmarks on the performance of this method? From the looks of it, doesn't sound like the ideal approach but looks to be the only way forward.

**Comment by OmarShehata** [comment]
In general it looks like it should be possible to write a wrapper to call into the OpenGL ES directly on the device rather than going through WebGL in a web view with React Native as [suggested here](https://stackoverflow.com/a/45000693/1278023) but I don't know how much work that would be or how much benefit you'd get.
