### ISSUE TITLE
How to get the user defined property from czml by CzmlDataSource?

### ISSUE THREAD

**Issue by LZS1991** [AnalyticalGraphicsInc/cesium#7635]
I user the czml-writer in java and add the user-defined property in a packet,but when i load the czml file in cesium by using CzmlDataSource, i can not get the  user-defined property,so how to do that?

**Comment by shunter** [comment]
Custom properties are added to the Cesium entities underneath the `properties` property on the entity, so a particular property would be accessible as `entity.properties.custom_property_name`, and then you can call `getValue` as you would with any other entity property.

There is a Sandcastle example that demonstrates compute the current value of a custom CZML property:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=CZML%20Custom%20Properties.html&label=CZML


If you have additional questions, please post on the forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev instead of GitHub.
We use GitHub exclusively for tracking Cesium bugs and planning new features.

**Comment by LZS1991** [comment]
I have tryed and it works very well , thank you!
