### ISSUE TITLE
2DView has lower render FPS than 3DView?

### ISSUE THREAD

**Issue by forest21000** [AnalyticalGraphicsInc/cesium#7694]
When I load world contries geojson in 3DView,cesium works well and smoothly.But when I changed to 2DView,it has low FPS.I cann't even wander!Can you tell how to solve the problem?

**Comment by hpinkos** [comment]
Hello @forest21000, this is a known issue: #5026
I'm going to make a comment in that issue so we can alert you when we have a chance to look into the problem.

As a workaround, performance is better using the rotatable 2D map mode instead of the infinite scrolling one: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Rotatable%202D%20Map.html
