### ISSUE TITLE
VRTheWorld terrain provider broken

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#7697]
VRTheWorld terrain provider is broken in master but not in 1.55. Git bisect points to https://github.com/AnalyticalGraphicsInc/cesium/commit/b772d527599c787968ba2d5b3e652811b0e3b82f. It probably has something to do with flipY getting set incorrectly for heightmap terrain.

@OmarShehata could you check this out?

![vr-the-world](https://user-images.githubusercontent.com/915398/55340555-ee264080-5472-11e9-9e5a-163f0e345646.jpg)

**Comment by OmarShehata** [comment]
Can confirm it's the image bitmap. If you add:

```
Cesium.Resource.supportsImageBitmapOptions = function(){
    return Cesium.when.resolve(false);
};
```

To the beginning of the [terrain Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html?src=Terrain.html) it works fine. Looking into a fix now.

**Comment by OmarShehata** [comment]
Ok, I got it. It was peculiar because, what you see there isn't imagery flipped. It's the wrong terrain geometry. 

Now why would an upside down image cause it to load the wrong terrain tiles? It's because `VRTheWorldTerrainProvider` constructs geometry from a heightmap by reading the pixels! The fix is just to make sure flipY: false in the `requestTileGeometry` function. Opening a PR now.
