### ISSUE TITLE
如何加载多个terrainProvider

### ISSUE THREAD

**Issue by HuZhuangQiang** [AnalyticalGraphicsInc/cesium#7841]
如何在cesium中加载多个terrainProvider?
  可不可以不断添加   viewer.terrainProvider, 类似于viewer.imageryLayers.addImageryProvider(provider);

**Comment by OmarShehata** [comment]
The question as I understand it asks if it's possible to add more than one terrain provider in Cesium. Currently this is not possible to do at runtime. You can upload your terrain files to Cesium ion (http://cesium.com/ion/) to combine them.  There is a PR that adds multiple globes to the scene:

https://github.com/AnalyticalGraphicsInc/cesium/pull/6450

that might help with that depending on your use case. I think the long term goal is to support time dynamic 3D Tiles, and then terrain becomes part of 3D Tiles, so that way you can dynamically change individual areas of terrain.
