### ISSUE TITLE
Polylines are not drawn correctly 

### ISSUE THREAD

**Issue by onderaltintas** [AnalyticalGraphicsInc/cesium#7843]
Hello there,

Let's say we have 2 polylines. One of them has coordinates [0,0] to [50,50], the other one has coordinates [50,0] to [0,50]. We can say that both lines will be passing the point [25,25]; in other words, they will intersect at [25,25] coordinate. Unfortunately the sandcastle example shows the different. Tryed with or without clamp the ground. Both ways, it doesn't give expected result:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=5VRdb5swFP0rFi9xJGTSbJGqjEZr0qmalCpRl1aaxh4ccKjVi41sk4xU+e+1ISmQTdte9jTgAR/fcz/OwWypQlvOdkyhKyTYDs2Y5kVGHisM9+JqOZPCUC6Y6vU/RMLdNYcwYbjhTBOaJPglEshePEFj1FtKKMFSLnp+DedHwG4eA2tU2wRSaAsfS8+oMvaNindko2R2w1LFmL5Wipb4W8N018C3TxcaWWw0aLDv/VbAjifmyVa6JG1aRg1TnILdaClwGuAW5O7uGLFUMmfKlPilWzS1MUvpRByjARmetRRLkKo1n1uS6fzhUxN2aHe5/ywS9mOM2nlioFm+krdKFsLpu6GgWb19iMShtuWvTRn+Y1NGv3Ll/zPFOmKPV87FtOCQnB+x5RuOnX2/MU/QzDnUmwIVz2gNBXNJGw9rt/5kFh6OfDQcnYZac4C1pCrpes8zmrpiTddVjkof3BHrfvH1eu4U89H7yz4x8oYa+nA/x23ZttYZHlNYKJ7yVouPHZxMF6vV4q4j3ZsieymzlcRn+jjJPN8LtSmBTWrmR57lUhlUKMCEBIZlOdiPRAfrIn5mhsS6ooXBiRQmfGuPxlXknf3nIs+Zq7Xd2RQAX/ieRd4kDGx8hwaSJlykCzsm0NKFPF1M5jVICAkDu/yZZaSENVWtjK8

codes for sandcastle, in case of example disappears:
var viewer = new Cesium.Viewer('cesiumContainer');

viewer.entities.add({
    id : 'Polyline1',
    polyline : {
        positions : Cesium.Cartesian3.fromDegreesArray([
            0, 0,
            50, 50
        ]),
        width : 8.0,
        material : new Cesium.PolylineGlowMaterialProperty({
            glowPower : 0.2,
            color : Cesium.Color.BLUE
        }),
        zIndex: 2,
        clampToGround : false
    }
});

viewer.entities.add({
    id : 'Polyline2',
    polyline : {
        positions : Cesium.Cartesian3.fromDegreesArray([
            0, 50,
            50, 0
        ]),
        width : 8.0,
        material : new Cesium.PolylineGlowMaterialProperty({
            glowPower : 0.2,
            color : Cesium.Color.BLUE
        }),
        zIndex: 2,
        clampToGround : false
    }
})
var pinBuilder = new Cesium.PinBuilder();
viewer.entities.add({
    name : 'Blank blue pin',
    position : Cesium.Cartesian3.fromDegrees(25, 25),
    billboard : {
        image : pinBuilder.fromColor(Cesium.Color.ROYALBLUE, 48).toDataURL(),
        verticalOrigin : Cesium.VerticalOrigin.BOTTOM
    }
})

viewer.zoomTo(viewer.entities);

**Comment by GatorScott** [comment]
This is happening because the lines being drawn are geodesics (great arcs).  Look at the following gist in 2D and you'll see that they intersect "properly" when the lines are drawn directly between the points (through the Earth).

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=5VRRb9owGPwrVl4IUmQoG1LFUjSgVTWJNqijlaZlDyYx1KrjL7IdWKj477MTaBy2aXucNCcP8fnOn31nZ0sk2jK6oxJdIUF3aEYVKzL8VGF+J6m6MxCaMEFlp/shFvapNZgKzTSjCpM09V9jgUxjKRqhzgJ4yY3kohPUcH4EzOCRaBuRybLM6ehUd1L38X10fxM0tByUqQNCoTfmjEhtvoh4h9cSsmu6kZSqiZSk9L82Stv6gXnb0NBgw36Dfes6hB1L9bOpdIldWUY0lYxwM+AYddrnLYfd3ZGxkJBTqUv/tV10YzgLsF6PUB8PzpaUAAfp7M928XT+eNPQDu4q959ESr+PkDtPwkmWL+FWQiFsDGvCFa2HD7E41On9dXaDfyO74a/C+y+z25rbmjMxLRhPz2/s4g33K+rvQxYks0l2ppyIF7TiBbWTNlnXcf0pLX8wDNBgeNrVinG+AiLT9hlhGdnYYs2qqzkqg/yWWw/Rl8ncWhag95ddrOGaaPL4MPdd37YmGpYQHkm2Yc4Sn1o4nkbLZXTneOcc+z1AtgT/zB9rmRd4odIlp+Na+ZFlOUiNCsl9jHuaZjk3p0T1VkXyQjVOVCULeydRmLKtuUJXsXf224w9m65SZmRdcP6Z7WnsjcOe4bdkHEjKxCYy2+SktJTni/G8BjHGYc90f1ZpAL4i0pnxBw

Scott

**Comment by emackey** [comment]
Right.  The two points at latitude 50 are physically closer together than the two points on the equator.  So 25, 25 is not the center.  Lat/Lon positions don't work like 2D positions on a plane.

**Comment by onderaltintas** [comment]
I see, actually I am using mercator projection for visualization so the 2 lines doesn't pass by 25,25 :S Instead they pass by 25,27.somethingsomething. To be able to get intersection, also the lines' coordinates should be converted to mercator projection and these kinds things should happen. Thank you for providing the info, I think this one is false positive then. Have a nice day. I am closing the issue.
