### ISSUE TITLE
How to get parameters （urgent）

### ISSUE THREAD

**Issue by simonasdmd** [AnalyticalGraphicsInc/cesium#7880]
I want the perspective to jump to the target object.
What I know now is the bounding box of the target object.
I know to use viewer.camera.flyToBoundingSphere.
But how should I get the entry?
![image](https://user-images.githubusercontent.com/42527845/58622032-4eafed80-82fd-11e9-91ee-da637d34887f.png)

The API is provided but the method is not used.
This should be considered a "bug".

**Comment by likangning93** [comment]
Hi @simonasdmd, the bounding sphere for a 3D Tileset is available as a member of the tileset object, please see the documentation here: https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileset.html?classFilter=cesium3dtileset#boundingSphere

Keep in mind that the bounding sphere is only available when the tileset is `ready`, which is why the example in the documentation waits on the tileset `readyPromise`.

I put together an example of how to use the bounding sphere with `camera.flyToBoundingSphere` [here on Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=rVJLb9QwEP4rJpe4UuWAQCBBuoKWSyUkELuCSy5ee9K1cDyr8TjVgvrfsfOouvSKL86Mv9fEHjWJ0cE9kLgSAe7FDUSXBvVj6snaTOUNBtYuANWX4k8XRF4MRLn1jXB0Fuj9SjQEmuEnkre7GSIvuvBw8aELXRizGzsPEfjcbt5ef97Nh3IxSeQfhW8xfIeIiQyonnD4FDPw1sq3L9+9eeIw5VbRQAB1JDc4diNEpa2Vi3MBLp8qh7WnPMPgIig+QJB9CoYd5tTrpIuk0QOQVr0/7fAaU7Au3G2PByBYhdX+rF18llRbHazRkT2UIDtEv9d0nZizT50VBaNYySJO7Pynn0dxvZAvzrI/HpVlMETMHh7vZB2QxQSpS4YVQsCJwtJ4+E8DFpHqsmojnzxs5vqjG45IXK5QKtUwDEefH0Zs9sn8ylImxkJtm5XUWjcKZ6+66p8311XCeB1jPumT91v3G7pq0zYZf0bzqEu2ryOQ16cCObzafJmbSqm2yeVzFs+X8UTxLw).
Feel free to move the camera around and then click the `fly to bounding sphere` button to fly back to the tileset.

Note that if the goal is just to have the camera look at the tileset without a flight, you can also use `viewer.zoomTo(tileset)`. Please see the documentation here: https://cesiumjs.org/Cesium/Build/Documentation/Viewer.html?classFilter=viewer#zoomTo

**Comment by simonasdmd** [comment]
@likangning93
hi~
 I mean that there is a lot of 'children' and a lot of "boundingVolume" in a tileset.json: {"box": []}. How do I use the flyToBoundingSphere API to implement a camera jump to each 'children' position?
I see that 'flyToBoundingSphere' has a set of coordinate parameters. How is this parameter obtained, is there a computing API?
I am looking forward to your answer.

**Comment by likangning93** [comment]
Hi @simonasdmd,

`Camera.flyToBoundingSphere` has a `complete` callback, please see the documentation here: https://cesiumjs.org/Cesium/Build/Documentation/Camera.html?classFilter=camera#flyToBoundingSphere.

It should be possible to chain flights together with this callback using recursion.
I think one way could involve an array of targets, a counter, and a callback function that either does nothing if the counter indicates there are no remaining targets or increments the counter, computes a bounding sphere, and then calls `Camera.flyToBoundingSphere` with itself as the `complete` callback.

I'm not sure where the bug is in the code example provided, but if this answers your question feel free to discuss more details on how to implement flight chaining on the forum: https://groups.google.com/forum/#!forum/cesium-dev
