### ISSUE TITLE
When add a polyline entity with option'sshow equal to false, it will not show up again.

### ISSUE THREAD

**Issue by dminor112** [AnalyticalGraphicsInc/cesium#7881]
Example url: https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=1VZdb9owFP0rFi8EiYavomqMogHNmDQKKKOrprEHkxhi1bEj2wHRiv8+O04LpFkLavuwPJHrew7X51zfeAU5WGG0RhxcAorWoI8EjkP7ZxKzil7y2mdUQkwRL5Y+z+iMrhSKI3+oQgpm8DaiEkuMhA1933qYUaAeCkMEWqDoIh8Qnc0okIhzRVYsm5SIkU2y1AIpyESFImNUqHBaUh9yqX5B2rAXnIVXaMkREl1FtrF+n100y6DRLO8YTn3OavWE4k9pj2SNfRmoEvaJQ6h2gCHZq4wRxm3XudrL8ggMoykbcBZTX6VKHiOzup3R7U5GvQnqBnE4P17NgcYArkGJqv+tlJB7002EdoV1TcB2v91c947QfOA6zmgvTwRs3QILSERGbIHkFIeIxdKySuCy8yiQp3RhBNmELa1avXFeMuFDV2xNq6wxHm7LoFmtVktPDhK2xnR5gn0GAOYkRrtTESAgYr6A3ofYefF2Oy9y7axV823amyWTdB9639dpxoSzCHG5sR4O69JiTpgeRy1QteuZqiVUoN1ytkc93RPZFumP3dHX4fjWcXvDG2cH2JbyjiPjkC7ROJa6YP84P8cJxji5xkqVOYHeHWCGBEAJAoSXgQRQTYIFI6n9H+T4t+S/xKPxn8qgrtu1+oYGOOyDJ8ZTJmVOO6Qiv9YRuaaO3e5o4GS2lAp+m1ZSz1/u5/H1ht3+99d6I4p5RJASORkGRzTGJAEAIdX3LvE/gT71w8e5ft4wM+r9XN8xvj4F/jnVR+ORc3R7JDo/a44D1yY37mTo5HrlQxGcckHp6VlsQO/+Sc1403x3b5ovenN+tORXav9HHcfsiP3VHb14eIz+94yFU2Zl3NAphXKhLeSGoI6BfsFhxLgEMSeWbVckCiOi6hKVeezdIWl7IoG1K4+gto9XAPuXs0Lmwjor6JuYEGplERPyA9+jWaHTrqj8Axhh0FdDebxCnMCNTglqnaEJ2rbdrqjX5yjJGJlDvsf4Fw

```js
var greenRhumbLine = viewer.entities.add({
    name : 'Green rhumb line',
    polyline : {
        positions : Cesium.Cartesian3.fromDegreesArray([-75, 35,
                                                        -125, 35]),
        width : 5,
        arcType : Cesium.ArcType.RHUMB,
        material : Cesium.Color.GREEN,
        // here
        show: false
    }
});
setTimeout(() => {
    console.log(1234)
    greenRhumbLine.show = true
}, 5000)
// It will not show up again
```

**Comment by GatorScott** [comment]
The problem is that you are setting the entity's show property in the timeout function rather than the polyline's show property.

**Comment by dminor112** [comment]
@GatorScott So what should be the correct way? If I set show true first, and switch show true/false later, it work quite well. It make me very confused why it not work by set fale first.

**Comment by GatorScott** [comment]
Because your entity has only a single graphic element defined, polyline, I would control everything with the entity's show property.

`
var greenRhumbLine = viewer.entities.add({
    name : 'Green rhumb line',
    polyline : {
        positions : Cesium.Cartesian3.fromDegreesArray([-75, 35,
                                                        -125, 35]),
        width : 5,
        arcType : Cesium.ArcType.RHUMB,
        material : Cesium.Color.GREEN
    },
    show: false
});
setTimeout(() => {
    console.log(1234);
    greenRhumbLine.show = true;
}, 5000);

`
Notice that all I did was move the setting of the show flag onto the entity from the polyline when the entity was created.  Alternatively, I could have modified the timer callback to set greenRhumbLine.polyline.show = true.

The entity's show property is a convenient way to hide all of an entity's graphic elements.  It cannot be used to force all of the entity's graphic elements to be shown if any of those graphic elements have their individual show properties set to false.

Hope that helps.
Scott
