### ISSUE TITLE
The problem has not been solved

### ISSUE THREAD

**Issue by simonasdmd** [AnalyticalGraphicsInc/cesium#7883]
I want the perspective to jump to the target object.
What I know now is the bounding box of the target object.
I know to use viewer.camera.flyToBoundingSphere.
But how should I get the entry?
image
![image](https://user-images.githubusercontent.com/42527845/58674887-74340a00-8384-11e9-819c-5aa86a539bcf.png)

The API is provided but the method is not used.
This should be considered a "bug".

I mean that there is a lot of 'children' and a lot of "boundingVolume" in a tileset.json: {"box": []}. How do I use the flyToBoundingSphere API to implement a camera jump to each 'children' position?
I see that 'flyToBoundingSphere' has a set of coordinate parameters. How is this parameter obtained, is there a computing API?

I know the bounding box and min max values for each component but I don't know how to calculate the four data above the image. please tell me. Very urgent

**Comment by OmarShehata** [comment]
@simonasdmd have you seen this 3D Tiles Interactivity Sandcastle example?

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Interactivity.html

Particularly, the "zoom to feature", which will fly the camera to any particular building. This works in this tileset because each feature (building) contains the latitude, longitude and height batch table properties. If you have similar properties in your tileset you could do a similar approach.

Otherwise, given a Cesium3DTile, you can get its bounding sphere like this: https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTile.html?classFilter=Cesium3DTile#boundingSphere

And then you can tell the camera to fly directly to that bounding sphere with this method: https://cesiumjs.org/Cesium/Build/Documentation/Camera.html?classFilter=camera#flyToBoundingSphere

There are also lots of other options, like getting the bounding sphere's center and flying to that destination instead. Since it's unclear if there is a bug here, I'm going to close it. Please start a thread in the Cesium forum (https://groups.google.com/d/forum/cesium-dev) if you'd like to discuss this further and I'd be happy to take a look there. If we do discover a specific bug or a specific feature request we can open a GitHub issue for that.
