### ISSUE TITLE
Reduce Cesium footprint?

### ISSUE THREAD

**Issue by mrlubos** [AnalyticalGraphicsInc/cesium#7912]
Hey,

I noticed a lot of Cesium stuff gets loaded even though I know in advance that I will never use it. For example, I download `VRButton.css` but there is no VR functionality in my app. Is there a way to reduce the network impact Cesium currently has? It would be great if I didn't have to download so many resources I will never use.

**Comment by OmarShehata** [comment]
This is definitely something we've been wanting to do - I think it would be easier as part of the move to ES6 modules, to do this kind of tree shaking, see https://github.com/AnalyticalGraphicsInc/cesium/issues/2524#issuecomment-358839234.

As far as I know, you can do this today if you're using CesiumJS as a requireJS module with AMD syntax. So if your app does something like:

```
define([
    'Cesium/Core/Cartesian3',
    'Cesium/Core/Ion',
    'Cesium/Core/IonResource',
    'Cesium/Scene/IonImageryProvider',
    'Cesium/Core/HeadingPitchRoll'
], function (Cartesian3,
             Ion,
             IonResource,
             IonImageryProvider,
             HeadingPitchRoll) {
    // ... Your code here ...
});
```

The final bundle will contain only these classes. In practice however, I think since a lot of the core classes depend on a large amount of classes, it might not end up saving a lot.

**Comment by mrlubos** [comment]
@OmarShehata Awesome, thanks for the update!

**Comment by mramato** [comment]
As @OmarShehata stated, this is something we are aware of and AMD modules are what we currently offer.  Once we switch to ES6, treeshaking should help a lot here; but pulling in the Viewer widget currently ends up pulling in a lot of Cesium.  Switching to CesiumWidget if you don't use the built-in UX is probably your best bet if you really want to trim things down further.

**Comment by mrlubos** [comment]
Thank you for the update @mramato! Is there any related issue or roadmap I could consult in the future?

**Comment by mramato** [comment]
Most of the ES6 discussion has taken place in #2524. We don't have an official timeline or roadmap as to when we'll get there, but it is important to us (it's a pretty large undertaking and we just need to find the time).
