### ISSUE TITLE
Is there any params to set the tinge of layer?

### ISSUE THREAD

**Issue by RenZachary** [AnalyticalGraphicsInc/cesium#7931]
I found that osm layer has a shadows or dark tonal,and so did other layer loaded by ImageryProvider.is it a new feature added on purpose.

![cesium_OSM](https://user-images.githubusercontent.com/3363381/59318354-5312d800-8cf9-11e9-9f88-9e83fd481ff6.png)

**Comment by OmarShehata** [comment]
I think this is due to HDR. Try turning it off with `viewer.scene.highDynamicRange = false;`. Does that fix it?

**Comment by RenZachary** [comment]
Thank you! it works.
how does this affect performance?

**Comment by OmarShehata** [comment]
There should be no performance penalty. If anything, you might see better performance. What HDR does is allow for rendering a higher range of colors, and then tonemapping that to reduce it a standard range that monitors can display, so with HDR turned off it's one less step the shader has to do. 

I'm going to close this but mention this issue in https://github.com/AnalyticalGraphicsInc/cesium/issues/7732 since I think this will cause unexpected dimness for most imagery layers.
