### ISSUE TITLE
taking more time for loading

### ISSUE THREAD

**Issue by chaitanyajalluri** [AnalyticalGraphicsInc/cesium#8096]
When I am loading own terrain(from "geoserver" using "geoserver terrain provider")+ 3D tile(size 1.78MB, contains the 2D road information) , it is taking the loading time of 8.42 sec to load on the cesium globe.  similarly when i am loading own terrain(from "geoserver" using "geoserver terrain provider")+3D tile(size 6.6MB, containing building) , it is taking the loading time of 6.3 minutes to load on the cesium globe. I am not able to find the reason for this. How to minimize the loading time.  I have attached the images of 3D tiles.
![buildings tile](https://user-images.githubusercontent.com/41281254/63520106-cc0c8800-c511-11e9-954f-578f57e30b55.JPG)
![roadstile](https://user-images.githubusercontent.com/41281254/63520108-cca51e80-c511-11e9-818a-6cc47abf53a1.JPG)

**Comment by OmarShehata** [comment]
I am surprised it is taking _minutes_ to load such a small tileset. Can you share the dataset that you're loading into CesiumJS, and a full code example I can run on [Sandcastle](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html) ?

I would also try uploading your source data to [Cesium ion](https://cesium.com/ion/) if it's in one of these [currently supported formats](https://cesium.com/docs/tutorials/uploading/) just to narrow down where the issue is coming from.
