### ISSUE TITLE
loading DEM of larger area than given area.

### ISSUE THREAD

**Issue by chaitanyajalluri** [AnalyticalGraphicsInc/cesium#8097]
I have loaded the DEM covering very small size through geoserver, but DEM is loading over larger area on cesium globe even my input doesn't contain any information in rest area.

**Comment by OmarShehata** [comment]
I am guessing the issue is that the terrain tiles aren't reporting the correct `availability` here, or it's possible CesiumJS isn't reading it, but it's hard to know without a reproducible test case. I would suggest posting on the forum, see my answer here: https://github.com/AnalyticalGraphicsInc/cesium/issues/8098#issue-484013064
