### ISSUE TITLE
ol-cesium chrome 76: too many errors

### ISSUE THREAD

**Issue by edejin** [AnalyticalGraphicsInc/cesium#8105]
After chrome update:
```
256[.WebGL-0x2588fcac5300]GL ERROR :GL_INVALID_OPERATION : glDrawElements: GL_BLEND with floating-point color attachments requires the EXT_float_blend extension
7796ee5f-aab2-46bf-8f30-340669acc40a:1 WebGL: too many errors, no more errors will be reported to the console for this context.
```
And no features on screen.
Before Chrome 76 everything works fine.
Cesium `1.60.0`
Is it chrome, ol-cesium or cesium bug?

**Comment by edejin** [comment]
Thank you!

> Do you have a link to an example that reproduces this issue?

No, because it's too big and confidential.

> Do the examples on Sandcastle load for you?
>
> https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html

Yes, it's work fine.
 
> This sounds like it could be this issue, which was a bug in Chrome [#7798 (comment)](https://github.com/AnalyticalGraphicsInc/cesium/issues/7798#issuecomment-488253436).
> 
> Can you try running Chrome Canary 77 to see if the issue is fixed there?

In Chrome 77 everything works fine.

**Comment by thw0rted** [comment]
I've started seeing warnings about `EXT_float_blend` lately.  In Firefox 70, the message is

> Error: WebGL warning: drawElements: Using format enabled by implicitly enabled extension: EXT_float_blend. For maximal portability enable it explicitly.

Should I open a new issue?  I get the warning when viewing the "Billboards" Sandcastle demo.

**Comment by thw0rted** [comment]
Also, I started seeing "Error: WebGL warning: generateMipmap: Tex image TEXTURE_2D level 0 is incurring lazy initialization."  I don't know if they're related.  If I don't hear anything here soon I'll open a new issue for both warnings at once.

**Comment by OmarShehata** [comment]
@thw0rted there's some discussion here about that extension: https://github.com/AnalyticalGraphicsInc/cesium/issues/7798#issuecomment-489602999

My comment there links to where the extensions are requested in the source code. Kai's comment here https://github.com/AnalyticalGraphicsInc/cesium/issues/7798#issuecomment-493564027 mentions there was a spec change and that extension now needs to be requested explicitly. Can you see if adding it fixes the warning? And if so open a PR?

And if the other warning is still there, I think that would be a separate issue if you can reproduce it in Sandcastle.

**Comment by thw0rted** [comment]
Your link points to a set of lines in the master branch but it looks like the file has changed significantly since May.  I set a breakpoint in my browser's devtools and called `getExtension(gl, ["EXT_float_blend"])` on [L240 in the current Context.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Renderer/Context.js#L240) and the warning went away.  It looks like the presence of all the extensions that are requested are exposed on the Context object via a getter so it would seem a bit weird to just call `getExtension` for this one thing and ignore the return result.

I can put together a PR but it seems like somebody with more knowledge of the internals than I have might want to look into the implications of failing to get the extension -- is there a fallback path in a renderer somewhere that should be activated when the extension is missing?  Also, would there be further implications in Chrome, on mobile, etc?  That thread you linked made it sound more complicated than just adding this one line.

Also: I opened #8360 to track the other warning.
