### ISSUE TITLE
CallbackProperty no longer working for Polygon Entities

### ISSUE THREAD

**Issue by rcologgi** [AnalyticalGraphicsInc/cesium#8135]
1. A concise explanation of the problem you're experiencing.

```
var dynamicPositions = new Cesium.CallbackProperty(function () {
 return positions;
}, false);
```

This used to be a valid input for a polygon entity hierarchy, but now since CesiumJs version 1.60 this no longer works. This approach follows what was (at some point at least) the suggested method from one of the Sandcastle examples to allow users to draw in the scene. This approach still works for at least polylines and billboards. Seems very likely the issue must be related to this update in the 1.60 release "Added support for polygon holes to CZML." The example below should clarify the problem.

2. A minimal code example. If you've found a bug, this helps us reproduce and repair it.

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=fVLfa9swEP5XhF/qQCa369qV1A0d2WAPgwUKfZn7oMrn5KgsmZPs4o3875MiJ3GabmeQrO+7735xVaulQ6OZJBAOloQ1OuzAph3CK9CE/Sk089YJYs2eZXcs8txK0MAPzG2hRwJjMUQP/guw2NZ8Icj5P6EveUWm/gorArBfiESf/orKvX34/JGfT9mnc3+eUAFkl1fvUVdb6j+q96jrm12up8ltJMdnaKfstahRLkddaXg9dKbUs5AvSzINkOvTaphtuh9iMALXkj6MZsi1mbJKKAvHueMQVb8y+pt26HqfchRroGYBK1zhArZGIEFy3c9O682yccHLqP6+E6Rv/Scx6mYa7xKsJGwCNWNF4j8Pb4Z6h3WAUCWC5aIs06PKQ2ObsByhp+h9PL/HLZaeye1zYbQTqIHOgvBf2+mpZJrk1vUK5rGQe6wbQ461pFLOMwd1o7zWZs+tfAHHpbVBlmc7UV5ix7C8K5I3mYuESSWs9UzVKvWAv6FI5nnm/Y9kyogS9epnB6REH1zWF/MfEeSc55l/nqqcMX5daBTxLw

Switching to the commented out code provides a more helpful error report, but also fails. Changing "hierarchy: dynamicPositions" to just "hierarchy: positions" behaves normally, but of course if this example actually leveraged the callback in a meaningful way this would be undesirable.

3. Context. Why do you need to do this? We might know a better way to accomplish your goal.

We're using position callback properties for dynamic editing.

4. The Cesium version you're using, your operating system and browser.

Last working in Cesium 1.59.
Broken in Cesium 1.60 and 1.61.
(Ubuntu 19.04 + Chrome)

**Comment by shunter** [comment]
Here's the corrected version of your example:

[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=fVJNT+MwEP0rVi4EqeuUr91VSStQQeKAtJVW4kL2YJxJO8Kxo7ETFFD/O3bSlpSyTCQ7njfP82Y8Ra2lQ6OZJBAOFoQlOmzAxg3CC9Axe8s089YIYtUOZVPW49xK0MA/kMtMDwjGYrg9xM/BYl3yuSDn/4Q+4wWZ8gaWBGCviUQbP/bMnf34dcrHI3Y+9usBFJzs7OIr6KKDvmF9Bf38vc317/iyB4drKCdvtShRLgZVaXj5qEypJyGfF2QqINfGxaa38a6JwQhcTXpIXBjVLo2+QyBBctXGu7ZthaxHrBDKwr6wvsMd91Y7dK3XM0i0gSZDX7DVNs/koCD/di5z61G/52AlYRWQCcsi/3n3eiNh8/wQEiNYLvI83hMTtK7DMASZffR+vx46X3wku+PcaCdQAx0F4v+m0UPRKEqtaxXMeiFXWFaGHKtJxZwnDspKea5Nnmr5DI5L27UxTbakNMeGYT7Nok+Zs4hJJaz1SFEr9RdfIYtmaeLj92jKiBz18k8DpEQbQlYns/veyTlPE388ZDlj/HjQ4MZ3)

`PolygonGraphics.hierarchy` was always documented as a property of type `PolygonHierarchy`, meaning that any `Property` must produce a value of that type.  That would include the `CallbackProperty` from your example:

```javascript
var dynamicPositions = new Cesium.CallbackProperty(function() {
    return new Cesium.PolygonHierarchy(positions);
}, false);
```

Adapting a constant Cartesian array to a `PolygonHierarchy` was left for backwards compatibility, but using a Cartesian array was undocumented behavior since the `hierarchy` property was introduced.

**Comment by TheMrCoder** [comment]
good
