### ISSUE TITLE
"freeze frame" crashes cesium when 3D tiles are large

### ISSUE THREAD

**Issue by chendabo** [AnalyticalGraphicsInc/cesium#8141]
I have been using "freeze frame" in the 3D tile inspector, but when the scene loads more 3D tiles, an error occours.
<img width="1080" alt="Screen Shot 2019-09-07 at 3 59 47 PM" src="https://user-images.githubusercontent.com/4674477/64471827-9cec4c80-d188-11e9-9c0a-da420878a653.png">
when it loads less models, it can freeze properly. I'm wondering what has caused this.

**Comment by OmarShehata** [comment]
@chendabo how big is your 3D Tileset? How was it generated? Is this something you only noticed after upgrading to a new CesiumJS version? If so, what version are you on?

One easy way to test older versions of CesiumJS to see if this was caused by a recent change is on the hosted examples. So this link is for version 1.59:

https://cesiumjs.org/releases/1.59/Apps/Sandcastle/index.html?src=Offline.html

And you can change the version in the URL to get a different release. 

Just from looking at that minified stracktrace, my best guess is for some reason there's a tile there that loads but doesn't have any valid loaded content. You could try putting a breakpoint in Cesium3DTile.js's `updateContent` function when `content` is undefined and see if that helps you isolate which tile it is.

**Comment by hpinkos** [comment]
duplicate #7680
