### ISSUE TITLE
CI requestRenderMode tests suddenly randomly failing pretty often

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#8260]
I've had to restart travis several times because the below tests seem to randomly fail in all branches  

```
1) moving the camera causes a new frame to be rendered in requestRenderMode
     Scene/Scene
     Error: Expected 2019-10-07T12:37:58.5349999999998545Z not to equal 2019-10-07T12:37:58.5349999999998545Z.
    at <Jasmine>
    at Build/Specs/Specs.js:162885:46
    at UserContext.<anonymous> (Build/Specs/karma-main.js:943:34)
    at <Jasmine>
2) successful completed requests causes a new frame to be rendered in requestRenderMode
     Scene/Scene
     Error: Expected 2019-10-07T12:37:58.5540000000000873Z not to equal 2019-10-07T12:37:58.5540000000000873Z.
    at <Jasmine>
    at Build/Specs/Specs.js:162935:46
    at UserContext.<anonymous> (Build/Specs/karma-main.js:943:34)
    at <Jasmine>
```

The top of the render function looks a little odd to me, why are we doing so much work before deciding to render?  Why do we update the framestate even when a new frame isn't needed?  And why don't we return if `shouldRender` is false?  @ggetz I know you wrote this feature initially, do you have any thoughts here?  Of course it doesn't look like this code has changed in several months (@loshjawrence you were the last person in here) so I'm not sure why this is a problem now.

https://github.com/AnalyticalGraphicsInc/cesium/blob/b5cf72aa3fbffb6e94ae93a46b8f24df7e97c5b5/Source/Scene/Scene.js#L3278-L3311

**Comment by loshjawrence** [comment]
> why don't we return if shouldRender is false?

This is related to traversals that need to keep going so requests can be made (I thought there was tighter control over when they can go out but it looks like they always execute.. it should probably check if any tilesets need a non-render traversal and traverse only those tilesets needing their specific traversals.)

As far as the spec failures go, the first one is probably related to  view.checkForCameraUpdates  failing to detect changes, not sure if there were any recent changes to that code path. The other is probably an odd logic failure at the top of scene.update (it looks like it should go through and update the time stamp since the previous _renderRequested test passes).

**Comment by mramato** [comment]
This is becoming a real problem for CI, but if fails locally often enough too.

**Comment by lilleyse** [comment]
Let's keep an eye out, but this should be fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/8269
