### ISSUE TITLE
如何将 CylinderGraphics 将中心位置 移动到顶点位置

### ISSUE THREAD

**Issue by HuZhuangQiang** [AnalyticalGraphicsInc/cesium#8262]
如何将 CylinderGraphics 将中心位置 移动到顶点位置？
如图 
![捕获1](https://user-images.githubusercontent.com/33933148/66362185-56228a00-e9b4-11e9-94a3-cb839cddfbb3.PNG)
--->
![捕获](https://user-images.githubusercontent.com/33933148/66362195-5d499800-e9b4-11e9-9d48-143d0c044a25.PNG)
使用 viewer.selectedEntity 时，选中点为顶点

**Comment by OmarShehata** [comment]
There isn't a built-in way to offset entity graphics off their origin, but you could compute this offset yourself. This [forum thread](https://groups.google.com/d/msg/cesium-dev/bSQYW-oAXPM/sgNV0nqDAwAJ) talks about a method of doing so. Here's a [Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=5VVbT9swFP4rVl+WbsEpjGpSadFYB9okNjpgTJP64iYnjYVjR7bTUib++45zadwOXnhdFCn2uX4+5zvOimmy4rAGTSZEwppMwfAyp3eVLHgTV9upkpZxCfpN/2Qu53KFXoUy3HIl0a/xmTJtccXke5pqlX+GpQYwwcGHYUiOB7VnFF1pvuSSiZBIJQ+0ssxCQmIlgaRK4yIvmOZGSYp5KhQUpMVUYChLksADee7km+DPXBJ8WkCj7SpsFVzaEWnM3BMrofRoi9vt6O/zy8urX2FnZDK1HhGrS/CEBX8AccMfYUSOBrX4qVHHG8FlAnonk1XFNUt4aUZk4IVZKGtV3mqGnkaAXNrMRfeEOdZIcyaehUzX3GZnoshYMKDDfgNqLp/6XbOYXArATn1jNqOzr9FRrXldeT2TKRNiweL7mVYFaDROSxk7q6DvFSGKbriMgdgMSN1wwg3hshLEmB50SNaAgZEJVhGVpgYs4dYPsdhU5nV9WmepNG4SrqHKSjsHd+omzmQXcUvSYBDW9TBcBlWB+uQtOUTpQSWOlfHFdTE7PFMN7iAMGcKkQermFX8dqjrvHhiQ5e3WcjszW5GhwIz97s7zs7hVF8iz5EKzHIK28PsAumhdzk7fxMeTaP5wTPNSWF6IzafNzE3DmbnDiikd+KjCJkj73U94liReKteoatfMc3choGLp9KhMK82KiRK8cmiwpZbPXBuOgNvhJVs4L/Sv4nc9gSRlwkC/GRmEhKRir2RrPSvvJmRAB8OTl1B7jcsA51guZ9zG2bUS4kfpxlW6uJ23P0LhrthD+GUvlOMovjUNXzru/36/1bfYo1L5rQr27rT+SS/sjY3dCDitPT/yvMApI6UWAaWRhbwQmN5EizK+x6mNjXFxx1HrNE74ivBkMu/t/QznPRILZgxq0lJUVZv3TscR2u+4CVU19WoFWrCNM8kOTy9rIaV0HOH2Xy+rFJJVexH/Ag) where it shows how you could rotate a cylinder around its tip instead of its center as an example application.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/bSQYW-oAXPM/sgNV0nqDAwAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/8262 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
