### ISSUE TITLE
Option to have user input interrupt camera flight

### ISSUE THREAD

**Issue by puckey** [AnalyticalGraphicsInc/cesium#8264]
We are working on a feature where need to have user input override a camera flight tween. Currently all controller input is ignored when a camera flight is active.

I was wondering if we might be up for making this configurable by adding something like `interruptable` or `interruptByInput` as a boolean option to `Camera.flyTo`..

I could propose a PR if this is a welcome addition..

**Comment by mramato** [comment]
I believe a long long time ago Cesium worked liked this but we took it out for some reason or another. It might be because the `Camera` object which manages the flight is not the object that handles various input control, so it's an odd connection to make in the lower-level API (but I could be wrong).  


I'm not against the idea, but this should also be trivial to implement at the application level by simply calling `Camera.cancelFlight` if the user does anything that you want to interrupt the flight for.  However, if it's equally trivial to add as an option, I'm sure we'll consider taking it.

**Comment by puckey** [comment]
I used `Camera.cancelFlight` in a `LEFT_DOWN` event handler to have clicks/taps cancel flights, but this leaves zoom gestures. I would want a pinch to also interrupt any existing flight, but since zooming gestures are swallowed during flight, I think it is currently impossible at the app level:

https://github.com/AnalyticalGraphicsInc/cesium/blob/d26ccfea38dcf4623cf5da3faca141913c64cfe1/Source/Scene/CameraFlightPath.js#L360

https://github.com/AnalyticalGraphicsInc/cesium/blob/d26ccfea38dcf4623cf5da3faca141913c64cfe1/Source/Scene/ScreenSpaceCameraController.js#L386

**Comment by puckey** [comment]
Fixed it on app level using the `WHEEL` input action to also cancel flights. @mramato: Thanks for reminding me to take another look at solving it on the application level!

**Comment by mramato** [comment]
Glad you got it working!
