### ISSUE TITLE
gltf model load error

### ISSUE THREAD

**Issue by leation** [AnalyticalGraphicsInc/cesium#8285]
test gltf model:https://github.com/leation/mydata/blob/master/Bee.glb.

Cesium.js:254066 An error occurred while rendering.  Rendering has stopped.
undefined
TypeError: Cannot read property 'parents' of undefined
TypeError: Cannot read property 'parents' of undefined
    at createRuntimeNodes (http://localhost:8888/test/cesium/Cesium.js:153548:33)
    at createResources (http://localhost:8888/test/cesium/Cesium.js:153704:9)
    at Model.update (http://localhost:8888/test/cesium/Cesium.js:154606:21)
    at PrimitiveCollection.update (http://localhost:8888/test/cesium/Cesium.js:135195:27)
    at updateAndRenderPrimitives (http://localhost:8888/test/cesium/Cesium.js:242236:27)
    at executeCommandsInViewport (http://localhost:8888/test/cesium/Cesium.js:242075:13)
    at updateAndExecuteCommands (http://localhost:8888/test/cesium/Cesium.js:241883:13)
    at render (http://localhost:8888/test/cesium/Cesium.js:242534:9)
    at tryAndCatchError (http://localhost:8888/test/cesium/Cesium.js:242554:13)
    at Scene.render (http://localhost:8888/test/cesium/Cesium.js:242622:13)

**Comment by mramato** [comment]
@leation thanks for the bug report!

https://gltf-viewer.donmccurdy.com/ loads this model without any issues so I can't think of a good reason Cesium shouldn't load it either.  However it looks like there are some errors in it, you can see these by dragging/dropping it into the glTF Validator here: http://github.khronos.org/glTF-Validator/

@lilleyse or @likangning93 anything obvious going on here?  Perhaps this is a trivial fix?

**Comment by emackey** [comment]
The Bee model fails validation due to duplicate keyframes on the last animation time.

Looks like Unity fails to load the model in https://github.com/KhronosGroup/UnityGLTF/issues/476 with a slightly more helpful error message:

> Unity does not allow you to put two keyframes in with the same time

Perhaps there's a newer version of the Bee model where this was fixed in the glTF file?

**Comment by leation** [comment]
Thank you very much.

**Comment by leation** [comment]
Thank you very much.

**Comment by leation** [comment]
When I use https://gltf-viewer.donmccurdy.com/ to load the Bee.glb，I found it's has three animations,is this the reason？ 
![Image text](https://github.com/leation/mydata/blob/master/BeeAnimal.png?raw=true)

**Comment by leation** [comment]
@emackey  thanks for your detailed explanation.This Bee.glb file is one demo model file of the windows10 3d viewer .As you explained,probably,the Bee.glb file's format is not rigorous.

**Comment by leation** [comment]
@emackey thanks very much. just I try to use gltf-import-export to convert the Bee.glb to gltf file,the command is: gltf-import-export Bee.glb -o Bee.gltf.Then I use Cesium to load this Bee.gltf,happily,it's works,maybe gltf-import-export can solver error of the Bee.glb.but if I try to use blender to convert glb file to gltf file,it's not work,mayby blender has same bug.
![Image text](https://github.com/leation/mydata/blob/master/cesium-BeeAnimal.png?raw=true)

**Comment by emackey** [comment]
Glad you got it working.

It occurred to me that I was reacting to the validation failures, but I didn't actually stop to trap Cesium's actual problem in the debugger.  Turns out the two are not the same.

It looks like Cesium is having trouble with the model's skeleton, and this issue may be related to (or possibly duplicate with) issue #8175.

**Comment by Lemonjay** [comment]
> @emackey thanks very much. just I try to use gltf-import-export to convert the Bee.glb to gltf file,the command is: gltf-import-export Bee.glb -o Bee.gltf.Then I use Cesium to load this Bee.gltf,happily,it's works,maybe gltf-import-export can solver error of the Bee.glb.but if I try to use blender to convert glb file to gltf file,it's not work,mayby blender has same bug.
> ![Image text](https://github.com/leation/mydata/blob/master/cesium-BeeAnimal.png?raw=true)
I tried,it‘s not work

**Comment by emackey** [comment]
Although this issue is closed, the Bee is still marked as a bug (no pun intended!) in issue #8759.

I believe what's happening is that Cesium is computing a bounding sphere around the original mesh, and not accounting for the skin deformations of the mesh.  That's paired with another artifact of the model scale:  small models are sometimes built to "centimeter" scale, where a scaling factor of `0.01` is applied to the whole model.  But scaling doesn't affect skinned meshes directly, it affects them by scaling the skeleton instead, which the bounding sphere is not aware of.

So the bee's mesh, with skinning applied to it, is scaled down to 1/100th of its former size.  The camera is then placed 100 times further away from the bee than it should be, and kept away.

I believe the correct answer is that the bounding sphere needs to somehow account for sizing applied by skinning.
