### ISSUE TITLE
How could i always pick the Cartesian3 from mouse position and the Cesium3DTileset intersects

### ISSUE THREAD

**Issue by lzio** [AnalyticalGraphicsInc/cesium#8298]
I load a city model from Cesium3DTileset as a base scene of my project,
and then i load a lot of models into the scene,
i tried to use pickPosition but when small model front Cesium3DTileset, i picked the Cartesian3 from model, but i expect to pick the Cartesian3 by bigscene

**Comment by OmarShehata** [comment]
If you're only interested in using the height at that position, you could use the [scene.sampleHeight](https://cesium.com/docs/cesiumjs-ref-doc/Scene.html#sampleHeight) function, which takes an array of objects to exclude. So you would pass in the small model to exclude.

Since [pickPosition](https://cesium.com/docs/cesiumjs-ref-doc/Scene.html#pickPosition) returns the position directly from the depth buffer (as opposed to doing its own rendering pass like sampleHeight), it isn't possible to exclude specific objects. To do this, you would need to hide the object(s) you want to exclude, do a `scene.render()` call manually, call the pickPosition function, then unhide the object(s). 

For general questions like this, please use the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev). Feel free to follow up in a new thread there if you're still having issues with this.
