### ISSUE TITLE
KML NetworkLink CORS Issue

### ISSUE THREAD

**Issue by gogo1211** [AnalyticalGraphicsInc/cesium#8381]
Hello, guys.

I was trying to add KML to cesium map using KmlDataSource.
But I am getting the following error on console.

_Access to XMLHttpRequest at 'http://alphaalpha.ddns.net:4181/pp_google.kml' from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource._

This is the content of KML file.
`<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.0">
<Document>
<visibility>1</visibility>
<NetworkLink>
<name>PP1</name>
<flyToView>0</flyToView>
<Url><href>http://alphaalpha.ddns.net:4181/pp_google.kml</href>
<refreshMode>onInterval</refreshMode>
<refreshInterval>4</refreshInterval>
<viewRefreshMode>never</viewRefreshMode>
</Url>
<refreshVisibility>1</refreshVisibility>
</NetworkLink>
</Document>
</kml>
`

**Comment by hpinkos** [comment]
Hello @gogo1211, the site serving your KML file will need to enable CORS. If you don't have control over that site, i would recommend trying to contact the site owner.  You can find resources to learn more about CORS here: https://enable-cors.org/

**Comment by thw0rted** [comment]
For local testing (the error shows your Origin as being localhost) I suggest running your site in a browser with CORS protections disabled.  I believe Firefox may have extensions that facilitate this.  I use Chrome with the arguments 

````
                "--allow-file-access-from-files",
                "--disable-web-security",
                "--disable-session-crashed-bubble",
                "--disable-infobars",
                "--user-data-dir=${workspaceRoot}/tmp/chromium",
                "http://localhost:8080/?debug=true"
````

You can probably get away with just `--disable-web-security --user-data-dir=/path/to/some/profile`, which removes CORS protections and points the browser to a non-standard profile location, so that you won't accidentally have active login sessions with your bank / email / whatever.

**Comment by gogo1211** [comment]
@hpinkos , @thw0rted , thank you!
