### ISSUE TITLE
Cesium will collapse when the screen resolution is 11520*4320

### ISSUE THREAD

**Issue by dogofwangcai** [AnalyticalGraphicsInc/cesium#8387]
Sandcastle example: 
any example in sandcastle

Browser:
chrome  78.0.3904.97 
Operating System:
window 10

At this resolution, as long as I resize the browser, cesium will report an error like webgl rendering stop.
Any example in the sandbox will have a very high chance to report this error.
My screen size is roughly 14 meters wide and four meters high. 
Screen resolution is 11520*4320
Another problem is that when I load 3dtile, I have a very high chance of reporting the drawingBufferWidth must be greater than zero in the method of PerspectiveOffCenterFrustum.prototype.getPixelDimensions.

**Comment by dogofwangcai** [comment]
cesium version 1.61

**Comment by OmarShehata** [comment]
This sounds like an issue with the browser/device unable to render at that high of a resolution, so I'm not sure how much can be done at the library level to resolve this.

Are you able to render with other 3D libraries at this resolution on the same device? Can you share a web-page that reproduces the issue so that others can test? (You could modify the HTML in the [Sandcastle](https://sandcastle.cesium.com/index.html?) to get a bigger canvas, or use something like [CodePen](https://codepen.io/), [jsfiddle](https://jsfiddle.net/)).

**Comment by Dmitry162** [comment]
Good time. Have you tried to solve the problem before (https://github.com/CesiumGS/cesium/issues/8387#issue-521894684)? Did you manage to find a solution? I have a similar error - can you tell me how to solve it? Thanks in advance
