### ISSUE TITLE
cesium versioning

### ISSUE THREAD

**Issue by jony89** [AnalyticalGraphicsInc/cesium#8389]
Hey,

I just wanted to suggest that cesium will start follow `semantic-versioning` for it's versions.

https://semver.org/

Every npm package is split to [major.minor.patch]. for bug fixes we bump the patch and for breaking changes we bump the major.

This is crucial, as for example if the next version is breaking changes and only the minor is bumped, and in case that one has cesium in his package.json with the following configuration :

`cesium: "^1.59.0"`

so for the next `npm install` he will get the new (current) version `1.63` which will break the whole project. since it has breaking changes.

so let's try to follow this convention ?

**Comment by OmarShehata** [comment]
See the past discussion here https://github.com/AnalyticalGraphicsInc/cesium/issues/2422 for some of the reasons why CesiumJS doesn't strictly follow semver. In particular Matt's explanation at the end:

> So calling how we version Cesium semver is inaccurate, but we are close enough that for most practical purposes you can just treat it like it is. Whether semver itself is good or bad for versioning packages is an entirely different discussion.

With that said, it has been almost 5 years since that discussion. If you feel like there are any points worth revisiting feel free to bump the discussion in that issue.

**Comment by ezze** [comment]
@OmarShehata, actually there are no real reasons posted in those discussion. 1.63.0 had broken a lot of things for us.
