### ISSUE TITLE
get boundingSphere from 3dtiles  Cesium3DTileFeature

### ISSUE THREAD

**Issue by lzp0070007** [AnalyticalGraphicsInc/cesium#8415]
can I get the boundingSphere  from 3dtiles  Cesium3DTileFeature???I have make 3dmax to 3dtiles,And I want to  location a model(a Cesium3DTileFeature) in this 3dtiles,or fly to this model，Any help from you will be greatly appreciated!

**Comment by OmarShehata** [comment]
Please use [the Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev) for general questions like this.

If you know the tile that contains this feature, you can get the bounding sphere of that. Otherwise you could put the longitude/latitude as properties in the batch table, which is how this example does it to zoom to individual buildings:

https://sandcastle.cesium.com/index.html?src=3D%20Tiles%20Interactivity.html
