### ISSUE TITLE
Default Ion token does not show Earth anymore

### ISSUE THREAD

**Issue by Juanlu001** [AnalyticalGraphicsInc/cesium#8433]
So far I have been using Cesium with the default Ion token without problems, but today I noticed that the Earth does not render anymore, and instead I see a 401 error in the console:

https://api.cesium.com/v1/assets/2/endpoint?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwMzJhNTk5NS1lMTc5LTQ0MWMtYTc3Mi1lZmE3NjYyZWMwMzAiLCJpZCI6MjU5LCJzY29wZXMiOlsiYXNyIiwiZ2MiXSwiaWF0IjoxNTY5OTMyNDcwfQ.ifTZn9zZ4Tc3UD6yqH8yqwyU-8OgFQN2cqno6HmxWGw

Looks like the Earth renders just fine after I signed up in cesium.com and created a new access token.

cc @fisadev

**Comment by OmarShehata** [comment]
The default token that ships with the library is only meant for testing and expires with every version release, which is why you'll see this warning at the bottom of the screen when using it in your application:

> This application is using Cesium's default ion access token. Please assign Cesium.Ion.defaultAccessToken with an access token from your ion account before making any Cesium API calls. You can sign up for a free ion account at https://cesium.com.

Glad you have it working with your own token now! For general questions like this [the Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev) is a good place to look.
