### ISSUE TITLE
how to translate bim（.ifc.clm）to 3dtiles

### ISSUE THREAD

**Issue by nameglass** [AnalyticalGraphicsInc/cesium#8442]
I need a tool to translate bim to 3dtitle.it isbetter forfree

**Comment by OmarShehata** [comment]
There's an open feature request for this on Cesium ion here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/40

I'm not aware of any tools for tiling IFC into 3D Tiles, but feel free to search/ask in the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev) as well. Closing this since it's not a CesiumJS library issue.
