### ISSUE TITLE
Opacity not working on polygon layer

### ISSUE THREAD

**Issue by iamtekson** [AnalyticalGraphicsInc/cesium#8491]
I want to style my GeoJSON feature in such a way that, I shouldn't get the `feature` but when I click the feature position on the cesium map layer, It will appear the popup content. So I make the feature layers opacity to 0.001. It successfully removes the layer from the view but it also removes the properties. When I click the feature position, this time nothing will appear. I write the following code;
```
var geojsonOptions = {
            clampToGround: true,
            fill: new Cesium.Color(0, 0, 0, 0.001)
        };
var dataSource = Cesium.GeoJsonDataSource.load('../data/venezuela.json', geojsonOptions).then(
            function (dataSource) {
                var p = dataSource.entities.values;
                for (var i = 0; i < p.length; i++) {
                    p[i].polygon.extrudedHeight = 1000; // or height property
                    p[i].polygon.outlineColor = new Cesium.Color(0, 0, 0, 0)
                }
                viewer.dataSources.add(dataSource);
                viewer.zoomTo(dataSource);
            }
        );
```

**Comment by OmarShehata** [comment]
This sounds like an unusual scenario if I'm understanding this right - if the feature is not visible, what is the user clicking on? I wouldn't expect the CesiumJS viewer detecting that the feature was clicked in that scenario to be the desired behavior. 

In any case it looks like perhaps the alpha is getting truncated there. If you set it to `0.01` it appears to be invisible but still clickable. Closing since there isn't enough information here to determine if there's anything actionable on the library side. For general questions please use [the Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev).

**Comment by iamtekson** [comment]
Ok got it. Thank you for the response. My problem solved when I changed the value of opacity to `0.01`

**Comment by emackey** [comment]
Remember this gets used as an 8-bit value, so the lowest non-zero value is `1 / 255`, or about `0.004`.
