### ISSUE TITLE
attribute must have a vertex Buffer or a value

### ISSUE THREAD

**Issue by simonasdmd** [AnalyticalGraphicsInc/cesium#8505]
I have two copies of the b3dm file. Data A can load normally. Data B  cannot be loaded. I compared the two data and found no big difference. What is the cause of this. What is "vertex buffer"?

Sandcastle example: 
![image](https://user-images.githubusercontent.com/42527845/71659009-eb99a400-2d80-11ea-9652-7b2364144e0c.png)

![image](https://user-images.githubusercontent.com/42527845/71659386-5b5c5e80-2d82-11ea-9ffd-e88cf90cfceb.png)

Browser: chrome

Operating System: win10
my data:

[dataA.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/4015344/dataA.zip)
[dataB.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/4015345/dataB.zip)
[obj.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/4015355/obj.zip)

**Comment by OmarShehata** [comment]
The glTF model inside your b3dm is invalid. You can verify this by uploading your gltf to [the gltf-validator](https://gltf-viewer.donmccurdy.com/):

![image](https://user-images.githubusercontent.com/1711126/71667900-f9c1d300-2d34-11ea-9ae7-6857ae7f5a95.png)

I'm closing since this isn't a CesiumJS issue, but it looks like this glTF was generated from [obj2gltf](https://github.com/AnalyticalGraphicsInc/obj2gltf). If you can provide the source OBJ and steps showing how you got an invalid glTF from it, please open an issue in that repository. 

I ran `obj2gltf` on the OBJ you provided and it produced a valid model. What did you do differently for dataB?

**Comment by simonasdmd** [comment]
I want to use obj2gltf to generate b3dm. There was a problem in the middle. Now the problem is solved. Some bytes are missing in the middle. Thank you.
