### ISSUE TITLE
How can I scale a model over time in CZML?

### ISSUE THREAD

**Issue by breeze0512** [AnalyticalGraphicsInc/cesium#8551]
I am studying CZML using an example.
I want to change the scale of the model according to time.
For example. if there is an object moving from 1 pm to 2 pm, I want to make the object bigger or smaller every 10 minutes.

Is this possible in CZML?

**Comment by mramato** [comment]
[Here a simple example](https://sandcastle.cesium.com/index.html#c=pVRhb9owEP0rVr4QJOokUK1bS6t17T5MarVJrfahpJqMbcCqY6OzA6IT/30XYiBApyI1Asnxu3vv5ey7GQPCXwtNLsngb24IPnmkRB6Rc1wIy8tCGp9HnTVmWCEDevN0f0furZC6gc8kOGVNCMlo2sC4tvwlj85JUApqxkuYMV0BedRNs+5J+vkkPX3MPp2nKf6ekt3N09XmhjdwlwDo9FFV9v5HtJdTlNqrqVYSqpQvaVqDyxVqlh1yWBGmgAMbeVLsfXezLtKpsiDXChr41Drl14XZ+X7OwNsxsOlE8Vs5BindKmhwcnbWIT38Zyk+z8HchjE42GMbaz8KPihNHlgx1fKWeZaswl1Sm0NvYfUHl3Ssh3ulcZzp+nsGDfr9AyNHnlh2WP1QtbIY1tXPttC28EdqZm9pdt/X7H5As/uWZu99zd4HNHtHdsOuJhKdNkTX9wgv+PNFbnIzwxEwU3IuAYeAkXNSXwz6e7UXt/jq9cYaz5SR0Nq4dhNbanFtVMG8RBUPpUTW9oZV4L17sCVw+QtsoZxEgVqJbiFHmRBx0LzBUXS7gai2TMTVeGrXpAeE1E+kiUel4VVvxVu8HTwGOQ+Mv0jx3XjlF+hiG0hltafQxlj6b4sfIm7t9nirkl62qUUpmKPmVk4CWFgrzZURdk6xbcAH5GJTDUKiTtR3fqHlVW6+qmJqwZMSdIxN6iU2KZbQJcMSXXrKnavS+sk6oS/UjChxicNi9zDwdLlmziEyKrV+UK/YtFf9BON30qpCKjP+idNZs0UVMsmu7upNSmk/wdfDLG+tHjJoMObmHw) that does what you want.  This uses discrete intervals, but you could also use a interpolated property to have slow grow/shrink instead of being discrete.

CZML properties are consistently all defined the same way, so how you defined a time-based number is the same as all numeric properties. More details here: https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/CZML-Structure

There is a CZML tab in Sandcastle that has a bunch of examples for various types:  https://sandcastle.cesium.com/index.html?label=CZML

In the future, please ask for general help on our forum first, as we try and keep GitHub to confirmed bugs: https://groups.google.com/forum/#!forum/cesium-dev

**Comment by breeze0512** [comment]
Thank you for your help!!
I am so sorry, may I ask you one more question?

I want to size up of model using [x, y, z] value
For example, if the value is [1, 1, 10], I want the model size to be 10
times the z value only.

The value of scale is of type number only and the model is expressed by
multiplying the model's [x, y, z] and scale value in batches.

How can I resize the model using values of [x, y, z] or matrix?

Best Regards

2020년 1월 19일 (일) 오전 12:57, Matthew Amato <notifications@github.com>님이 작성:

**Comment by OmarShehata** [comment]
@breeze0512 there was some initial work done on this, but this is not currently a feature supported at the entity level, see the discussion here: https://github.com/AnalyticalGraphicsInc/cesium/issues/2922

**Comment by shunter** [comment]
If the model has a root node, you can use node transformations on that node to produce a non-uniform scale for the model.  This works through CZML and at the entity level.

See https://sandcastle.cesium.com/?src=development%2F3D%20Models%20Node%20Explorer.html and select the Cesium_Man node which is the root node, then scale can be adjusted with the sliders.
