### ISSUE TITLE
Add a lerp function to Color

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#8605]
Add `Color.lerp` to linearly interpolate between two colors.  Similarly to https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Cartesian4.js#L621

**Comment by mramato** [comment]
Just a note, for interpolating colors you usually want to do it in HSV space, not RGB.  I thought we had this code somewhere in Cesium already, but it could just be a really old TODO.

**Comment by IanLilleyT** [comment]
There's an argument for either RGB or HSV lerping. Maybe it should be exposed as an option?

I'd prefer RGB lerp by default since it's faster + simpler + often good enough (doesn't need to transform to HSV space and back)

There are also some scenarios where you don't want HSV lerp, such as interpolating between two colors with large hue differences, as you would get a rainbowy result.

I already have an RGB Color.lerp on an old branch. I can PR that. Would it help to have a separate function called Color.lerpHSV which converts the RGB inputs to HSV, lerps, then converts back to RGB. There's more advanced color lerps out there, not sure if we want to support those.

**Comment by hpinkos** [comment]
@IanLilleyT sounds good to me!  We use a RGB lerp in some of our other projects, so that's mainly what I was looking for.  We can add a separate `lerpHSV` later when we need it.

**Comment by IanLilleyT** [comment]
@hpinkos here's the PR: https://github.com/AnalyticalGraphicsInc/cesium/pull/8607
